// src/vue/components/shared/RelatedLogs.vue
<script setup lang="ts">
import { ref } from 'vue'
import { formatTime, timeAgo } from '../../../core/formatters.js'
import {
  resolveLogLevel,
  resolveLogMessage,
  resolveLogTimestamp,
  resolveLogRequestId,
  getLogLevelCssClass,
  getStructuredData,
} from '../../../core/log-utils.js'
import JsonViewer from './JsonViewer.vue'

import type { LogEntry } from '../../../core/log-utils.js'

const props = withDefaults(
  defineProps<{
    logs: LogEntry[]
    classPrefix?: 'ss-dash' | 'ss-dbg'
  }>(),
  {
    classPrefix: 'ss-dash',
  }
)

const expandedIndex = ref<number | null>(null)

function toggleExpand(index: number, hasData: boolean) {
  if (!hasData) return
  expandedIndex.value = expandedIndex.value === index ? null : index
}
</script>

<template>
  <div v-if="logs.length > 0">
    <div :class="`${classPrefix}-related-logs-title`">
      Related Logs
      <span :class="`${classPrefix}-related-logs-count`">({{ logs.length }})</span>
    </div>
    <div style="overflow: auto">
      <template v-for="(log, i) in logs" :key="(log.id as string) || i">
        <div
          :class="[
            `${classPrefix}-log-entry`,
            getStructuredData(log) ? `${classPrefix}-log-entry-expandable` : '',
          ]"
          @click="toggleExpand(i, !!getStructuredData(log))"
        >
          <span
            :class="[
              `${classPrefix}-log-level`,
              getLogLevelCssClass(resolveLogLevel(log), `${classPrefix}-log-level`),
            ]"
          >
            {{ resolveLogLevel(log).toUpperCase() }}
          </span>
          <span
            :class="`${classPrefix}-log-time`"
            :title="resolveLogTimestamp(log) ? formatTime(resolveLogTimestamp(log)) : ''"
          >
            {{ resolveLogTimestamp(log) ? timeAgo(resolveLogTimestamp(log)) : '-' }}
          </span>
          <span
            v-if="resolveLogRequestId(log)"
            :class="`${classPrefix}-log-reqid`"
            :title="resolveLogRequestId(log)"
          >
            {{ resolveLogRequestId(log).slice(0, 8) }}
          </span>
          <span v-else :class="`${classPrefix}-log-reqid-empty`">--</span>
          <span
            v-if="getStructuredData(log)"
            :class="[
              `${classPrefix}-log-expand-icon`,
              expandedIndex === i ? `${classPrefix}-log-expand-icon-open` : '',
            ]"
            >&#x25B6;</span
          >
          <span v-else style="width: 14px" />
          <span :class="`${classPrefix}-log-msg`">{{ resolveLogMessage(log) }}</span>
        </div>
        <div
          v-if="expandedIndex === i && getStructuredData(log)"
          :class="`${classPrefix}-log-detail`"
        >
          <JsonViewer
            :value="getStructuredData(log)"
            :class-prefix="classPrefix"
            :default-expanded="true"
          />
        </div>
      </template>
    </div>
  </div>
</template>

// src/react/components/shared/RelatedLogs.tsx
import React, { useState } from 'react'

import { formatTime, timeAgo } from '../../../core/formatters.js'
import {
  resolveLogLevel,
  resolveLogMessage,
  resolveLogTimestamp,
  resolveLogRequestId,
  getLogLevelCssClass,
  getStructuredData,
} from '../../../core/log-utils.js'
import { JsonViewer } from './JsonViewer.js'

import type { LogEntry } from '../../../core/log-utils.js'

interface RelatedLogsProps {
  logs: LogEntry[]
  classPrefix?: 'ss-dash' | 'ss-dbg'
}

export function RelatedLogs({ logs, classPrefix = 'ss-dash' }: RelatedLogsProps) {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null)

  if (logs.length === 0) return null

  return (
    <div>
      <div className={`${classPrefix}-related-logs-title`}>
        Related Logs
        <span className={`${classPrefix}-related-logs-count`}>({logs.length})</span>
      </div>
      <div className={`${classPrefix}-log-entries`} style={{ overflow: 'auto' }}>
        {logs.map((log, i) => {
          const level = resolveLogLevel(log)
          const message = resolveLogMessage(log)
          const reqId = resolveLogRequestId(log)
          const ts = resolveLogTimestamp(log)
          const structured = getStructuredData(log)

          return (
            <React.Fragment key={(log.id as string) || i}>
              <div
                className={`${classPrefix}-log-entry${structured ? ` ${classPrefix}-log-entry-expandable` : ''}`}
                onClick={() => structured && setExpandedIndex(expandedIndex === i ? null : i)}
              >
                <span className={`${classPrefix}-log-level ${getLogLevelCssClass(level, `${classPrefix}-log-level`)}`}>
                  {level.toUpperCase()}
                </span>
                <span className={`${classPrefix}-log-time`} title={ts ? formatTime(ts) : ''}>
                  {ts ? timeAgo(ts) : '-'}
                </span>
                {reqId ? (
                  <span className={`${classPrefix}-log-reqid`} title={reqId}>
                    {reqId.slice(0, 8)}
                  </span>
                ) : (
                  <span className={`${classPrefix}-log-reqid-empty`}>--</span>
                )}
                {structured ? (
                  <span className={`${classPrefix}-log-expand-icon${expandedIndex === i ? ` ${classPrefix}-log-expand-icon-open` : ''}`}>
                    ▶
                  </span>
                ) : (
                  <span style={{ width: 14 }} />
                )}
                <span className={`${classPrefix}-log-msg`}>{message}</span>
              </div>
              {expandedIndex === i && structured && (
                <div className={`${classPrefix}-log-detail`}>
                  <JsonViewer data={structured} classPrefix={classPrefix} defaultExpanded />
                </div>
              )}
            </React.Fragment>
          )
        })}
      </div>
    </div>
  )
}
