// src/react/components/DebugPanel/DebugPanel.tsx
import React, { useState, useCallback, useMemo, useEffect, Suspense, lazy } from 'react'

import { useFeatures } from '../../hooks/useFeatures.js'
import { useTheme } from '../../hooks/useTheme.js'
import { ThemeToggle } from '../shared/ThemeToggle.js'

import type {
  DebugPanelProps as DebugPanelPropsBase,
  DebugTab,
  DebugPane,
} from '../../../core/types.js'
import { TAB_ICONS } from '../../../core/icons.js'

// Lazy-loaded tabs
const QueriesTab = lazy(() => import('./tabs/QueriesTab.js'))
const EventsTab = lazy(() => import('./tabs/EventsTab.js'))
const EmailsTab = lazy(() => import('./tabs/EmailsTab.js'))
const RoutesTab = lazy(() => import('./tabs/RoutesTab.js'))
const LogsTab = lazy(() => import('./tabs/LogsTab.js'))
const TimelineTab = lazy(() => import('./tabs/TimelineTab.js'))
const CacheTab = lazy(() => import('./tabs/CacheTab.js'))
const JobsTab = lazy(() => import('./tabs/JobsTab.js'))
const ConfigTab = lazy(() => import('./tabs/ConfigTab.js'))
const InternalsTab = lazy(() => import('./tabs/InternalsTab.js'))
const CustomPaneTab = lazy(() => import('./tabs/CustomPaneTab.js'))

interface DebugPanelProps extends DebugPanelPropsBase {
  /** Initial open state. */
  defaultOpen?: boolean
  /** Dashboard path for deep links. */
  dashboardPath?: string
  /** Controlled open state (used when parent manages toggle via StatsBar wrench). */
  isOpen?: boolean
  /** Callback when open state changes. */
  onOpenChange?: (open: boolean) => void
  /** Whether the stats bar is connected via Transmit (SSE) for live updates. */
  isLive?: boolean
}

export function DebugPanel(props: DebugPanelProps) {
  const {
    defaultOpen = false,
    dashboardPath,
    isOpen: controlledOpen,
    onOpenChange,
    isLive = false,
    ...debugOptions
  } = props

  const [internalOpen, setInternalOpen] = useState(defaultOpen)
  const isOpen = controlledOpen !== undefined ? controlledOpen : internalOpen
  const setIsOpen = (open: boolean) => {
    if (onOpenChange) onOpenChange(open)
    else setInternalOpen(open)
  }
  const [activeTab, setActiveTab] = useState<DebugTab>('queries')
  const { features } = useFeatures(debugOptions)
  const { theme, toggleTheme } = useTheme()

  const customPanes = features.customPanes || []

  // Close panel on Escape key (matches old debug-panel.js behaviour)
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false)
      }
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [isOpen])

  const builtInTabs: { id: DebugTab; label: string; visible: boolean }[] = useMemo(
    () => [
      { id: 'queries', label: 'Queries', visible: true },
      { id: 'events', label: 'Events', visible: true },
      { id: 'emails', label: 'Emails', visible: true },
      { id: 'routes', label: 'Routes', visible: true },
      { id: 'logs', label: 'Logs', visible: true },
      { id: 'timeline', label: 'Timeline', visible: features.tracing },
      { id: 'cache', label: 'Cache', visible: features.cache },
      { id: 'jobs', label: 'Jobs', visible: features.queues },
      { id: 'config', label: 'Config', visible: true },
      { id: 'internals', label: 'Internals', visible: true },
    ],
    [features]
  )

  const visibleTabs = useMemo(() => builtInTabs.filter((t) => t.visible), [builtInTabs])

  // Ensure the active tab is always visible (e.g. when a feature flag changes
  // and the currently-selected tab disappears from the bar).
  useEffect(() => {
    const allVisibleIds = [...visibleTabs.map((t) => t.id), ...customPanes.map((p: DebugPane) => p.id)]
    if (!allVisibleIds.includes(activeTab) && allVisibleIds.length > 0) {
      setActiveTab(allVisibleIds[0] as DebugTab)
    }
  }, [visibleTabs, customPanes, activeTab])

  const togglePanel = useCallback(() => {
    setIsOpen(!isOpen)
  }, [isOpen])

  const renderTabContent = useCallback(() => {
    const tabProps = { options: debugOptions }

    // Check if it's a custom pane
    const customPane = customPanes.find((p: DebugPane) => p.id === activeTab)
    if (customPane) {
      return (
        <Suspense fallback={<div className="ss-dbg-empty">Loading...</div>}>
          <CustomPaneTab pane={customPane} options={debugOptions} />
        </Suspense>
      )
    }

    const tabMap: Record<string, React.ReactNode> = {
      queries: <QueriesTab {...tabProps} />,
      events: <EventsTab {...tabProps} />,
      emails: <EmailsTab {...tabProps} />,
      routes: (
        <RoutesTab
          {...tabProps}
          currentPath={typeof window !== 'undefined' ? window.location.pathname : ''}
        />
      ),
      logs: <LogsTab {...tabProps} />,
      timeline: <TimelineTab {...tabProps} />,
      cache: <CacheTab {...tabProps} dashboardPath={dashboardPath} />,
      jobs: <JobsTab {...tabProps} dashboardPath={dashboardPath} />,
      config: <ConfigTab {...tabProps} dashboardPath={dashboardPath} />,
      internals: <InternalsTab {...tabProps} />,
    }

    return (
      <Suspense fallback={<div className="ss-dbg-empty">Loading...</div>}>
        {tabMap[activeTab] || <div className="ss-dbg-empty">Unknown tab</div>}
      </Suspense>
    )
  }, [activeTab, debugOptions, customPanes])

  return (
    <>
      {/* Wrench button (only when not controlled externally via StatsBar) */}
      {controlledOpen === undefined && (
        <button
          type="button"
          className={`ss-dbg-btn ${isOpen ? 'ss-dbg-active' : ''}`}
          onClick={togglePanel}
          title="Toggle debug panel"
          id="ss-dbg-wrench"
        >
          <svg
            width="14"
            height="14"
            viewBox={TAB_ICONS.wrench.viewBox}
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            dangerouslySetInnerHTML={{ __html: TAB_ICONS.wrench.elements.join('') }}
          />
        </button>
      )}

      {/* Panel */}
      <div
        className={`ss-dbg-panel ${isOpen ? 'ss-dbg-open' : ''}`}
        data-ss-theme={theme}
        id="ss-dbg-panel"
      >
        {/* Tab bar */}
        <div className="ss-dbg-tabs">
          <div className="ss-dbg-tabs-scroll">
            {visibleTabs.map((tab) => (
              <button
                key={tab.id}
                type="button"
                className={`ss-dbg-tab ${activeTab === tab.id ? 'ss-dbg-active' : ''}`}
                onClick={() => setActiveTab(tab.id)}
              >
                {TAB_ICONS[tab.id] ? (
                  <svg
                    className="ss-dbg-tab-icon"
                    viewBox={TAB_ICONS[tab.id].viewBox}
                    dangerouslySetInnerHTML={{ __html: TAB_ICONS[tab.id].elements.join('') }}
                  />
                ) : null}
                {tab.label}
              </button>
            ))}

            {/* Custom pane tabs */}
            {customPanes.map((pane: DebugPane) => (
              <button
                key={pane.id}
                type="button"
                className={`ss-dbg-tab ${activeTab === pane.id ? 'ss-dbg-active' : ''}`}
                onClick={() => setActiveTab(pane.id)}
              >
                {pane.label}
              </button>
            ))}
          </div>

          <div className="ss-dbg-tabs-right">
            <span
              className={`ss-dbg-conn-mode ${isLive ? 'ss-dbg-conn-live' : 'ss-dbg-conn-polling'}`}
              title={
                isLive
                  ? 'Connected via Transmit (SSE) \u2014 real-time updates'
                  : 'Polling every 3s'
              }
            >
              {isLive ? 'live' : 'polling'}
            </span>

            <ThemeToggle theme={theme} onToggle={toggleTheme} classPrefix="ss-dbg" />

            {dashboardPath && (
              <a
                href={dashboardPath}
                target="_blank"
                rel="noopener noreferrer"
                className="ss-dbg-dashboard-link"
                title="Open dashboard"
              >
                <svg
                  width="14"
                  height="14"
                  viewBox={TAB_ICONS['external-link'].viewBox}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  dangerouslySetInnerHTML={{ __html: TAB_ICONS['external-link'].elements.join('') }}
                />
              </a>
            )}

            <button
              type="button"
              className="ss-dbg-close"
              onClick={() => setIsOpen(false)}
              title="Close panel"
            >
              {'\u00D7'}
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="ss-dbg-content">{isOpen && renderTabContent()}</div>
      </div>
    </>
  )
}

// src/vue/components/DebugPanel/DebugPanel.vue
<script setup lang="ts">
/**
 * Main debug panel with tabs.
 *
 * Expandable overlay panel with lazy-loaded tabs for queries,
 * events, emails, routes, logs, timeline, cache, jobs, config,
 * internals, and custom panes.
 */
import { ref, computed, defineAsyncComponent, watch } from 'vue'
import { useDebugData } from '../../composables/useDebugData.js'
import { useFeatures } from '../../composables/useFeatures.js'
import { useTheme } from '../../composables/useTheme.js'
import type { DebugPanelConfig, DebugPane, DebugTab } from '../../../core/index.js'
import { TAB_ICONS } from '../../../core/index.js'
import ThemeToggle from '../shared/ThemeToggle.vue'

// Lazy-loaded tab components
const QueriesTab = defineAsyncComponent(() => import('./tabs/QueriesTab.vue'))
const EventsTab = defineAsyncComponent(() => import('./tabs/EventsTab.vue'))
const EmailsTab = defineAsyncComponent(() => import('./tabs/EmailsTab.vue'))
const RoutesTab = defineAsyncComponent(() => import('./tabs/RoutesTab.vue'))
const LogsTab = defineAsyncComponent(() => import('./tabs/LogsTab.vue'))
const TimelineTab = defineAsyncComponent(() => import('./tabs/TimelineTab.vue'))
const CacheTab = defineAsyncComponent(() => import('./tabs/CacheTab.vue'))
const JobsTab = defineAsyncComponent(() => import('./tabs/JobsTab.vue'))
const ConfigTab = defineAsyncComponent(() => import('./tabs/ConfigTab.vue'))
const InternalsTab = defineAsyncComponent(() => import('./tabs/InternalsTab.vue'))
const CustomPaneTab = defineAsyncComponent(() => import('./tabs/CustomPaneTab.vue'))

const props = withDefaults(defineProps<DebugPanelConfig & { defaultOpen?: boolean }>(), {
  baseUrl: '',
  debugEndpoint: '/admin/api/debug',
  dashboardPath: '/__stats',
  tracingEnabled: false,
  isLive: false,
  defaultOpen: false,
})

const isOpen = ref(props.defaultOpen)
const activeTab = ref<string>('queries')

const { theme } = useTheme()
const { features } = useFeatures({
  baseUrl: props.baseUrl,
  debugEndpoint: props.debugEndpoint,
  authToken: props.authToken,
})

const dashboardEndpoint = props.dashboardPath
  ? props.dashboardPath.replace(/\/+$/, '') + '/api'
  : undefined

const isCustomTab = computed(() => activeTab.value.startsWith('custom-'))
const isSelfManagedTab = computed(() => isCustomTab.value || activeTab.value === 'internals')

const { data, loading, error, isUnauthorized, refresh, startRefresh, stopRefresh } = useDebugData(
  () => activeTab.value as DebugTab,
  {
    baseUrl: props.baseUrl,
    debugEndpoint: props.debugEndpoint,
    dashboardEndpoint,
    authToken: props.authToken,
  }
)

// Tab definitions
interface TabDef {
  id: string
  label: string
  icon: string
  show?: () => boolean
}

const TABS = computed<TabDef[]>(() => {
  const tabs: TabDef[] = [
    { id: 'queries', label: 'Queries', icon: 'Q' },
    { id: 'events', label: 'Events', icon: 'E' },
    { id: 'emails', label: 'Emails', icon: 'M' },
    { id: 'routes', label: 'Routes', icon: 'R' },
    { id: 'logs', label: 'Logs', icon: 'L' },
  ]

  if (features.value.tracing || props.tracingEnabled) {
    tabs.push({ id: 'timeline', label: 'Timeline', icon: 'T' })
  }

  if (features.value.cache) {
    tabs.push({ id: 'cache', label: 'Cache', icon: 'C' })
  }

  if (features.value.queues) {
    tabs.push({ id: 'jobs', label: 'Jobs', icon: 'J' })
  }

  tabs.push({ id: 'config', label: 'Config', icon: 'G' })
  tabs.push({ id: 'internals', label: 'Internals', icon: 'I' })

  // Add custom panes
  for (const pane of features.value.customPanes) {
    tabs.push({
      id: `custom-${pane.id}`,
      label: pane.label,
      icon: pane.label.charAt(0).toUpperCase(),
    })
  }

  return tabs
})

function getCustomPane(tabId: string): DebugPane | undefined {
  const paneId = tabId.replace('custom-', '')
  return features.value.customPanes.find((p) => p.id === paneId)
}

// Control open/close
function open() {
  isOpen.value = true
  startRefresh()
}

function close() {
  isOpen.value = false
  stopRefresh()
}

function toggle() {
  if (isOpen.value) close()
  else open()
}

function selectTab(tabId: string) {
  activeTab.value = tabId
}

// Pause refresh when panel is closed
watch(isOpen, (open) => {
  if (open) startRefresh()
  else stopRefresh()
})

// Expose toggle for parent components
defineExpose({ toggle, open, close })
</script>

<template>
  <div
    v-if="!isUnauthorized"
    :class="['ss-dbg-panel', { 'ss-dbg-open': isOpen }]"
    :data-ss-theme="theme"
  >
    <!-- Tab bar -->
    <div class="ss-dbg-tabs">
      <div class="ss-dbg-tabs-scroll">
        <button
          v-for="tab in TABS"
          :key="tab.id"
          type="button"
          :class="['ss-dbg-tab', { 'ss-dbg-active': activeTab === tab.id }]"
          @click="selectTab(tab.id)"
        >
          <svg
            v-if="TAB_ICONS[tab.id]"
            class="ss-dbg-tab-icon"
            :viewBox="TAB_ICONS[tab.id].viewBox"
            v-html="TAB_ICONS[tab.id].elements.join('')"
          ></svg>
          {{ tab.label }}
        </button>
      </div>

      <div class="ss-dbg-tabs-right">
        <!-- Connection mode indicator -->
        <span
          :class="['ss-dbg-conn-mode', isLive ? 'ss-dbg-conn-live' : 'ss-dbg-conn-polling']"
          :title="
            isLive ? 'Connected via Transmit (SSE) \u2014 real-time updates' : 'Polling every 3s'
          "
        >
          {{ isLive ? 'live' : 'polling' }}
        </span>

        <!-- Dashboard link -->
        <a
          v-if="dashboardPath && features.dashboard"
          :href="dashboardPath"
          target="_blank"
          rel="noopener noreferrer"
          class="ss-dbg-dashboard-link"
          title="Open dashboard"
        >
          <svg
            width="14"
            height="14"
            :viewBox="TAB_ICONS['external-link'].viewBox"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            v-html="TAB_ICONS['external-link'].elements.join('')"
          ></svg>
        </a>

        <ThemeToggle />

        <button type="button" class="ss-dbg-close" @click="close" title="Close panel">
          &times;
        </button>
      </div>
    </div>

    <!-- Tab content -->
    <div class="ss-dbg-content">
      <!-- Loading state (skip for custom tabs - they handle their own state) -->
      <div v-if="loading && !data && !isSelfManagedTab" class="ss-dbg-empty">Loading...</div>

      <!-- Error state (skip for custom tabs - they handle their own state) -->
      <div
        v-else-if="error && !isSelfManagedTab"
        class="ss-dbg-empty"
        style="color: var(--ss-red-fg)"
      >
        Error: {{ error.message }}
      </div>

      <!-- Tab content -->
      <template v-else>
        <QueriesTab
          v-if="activeTab === 'queries'"
          :data="data as any"
          :dashboard-path="dashboardPath"
        />
        <EventsTab
          v-else-if="activeTab === 'events'"
          :data="data as any"
          :dashboard-path="dashboardPath"
        />
        <EmailsTab
          v-else-if="activeTab === 'emails'"
          :data="data as any"
          :dashboard-path="dashboardPath"
          :debug-endpoint="debugEndpoint"
          :auth-token="authToken"
        />
        <RoutesTab v-else-if="activeTab === 'routes'" :data="data as any" />
        <LogsTab
          v-else-if="activeTab === 'logs'"
          :data="data as any"
          :dashboard-path="dashboardPath"
        />
        <TimelineTab
          v-else-if="activeTab === 'timeline'"
          :data="data as any"
          :dashboard-path="dashboardPath"
          :base-url="baseUrl"
          :debug-endpoint="debugEndpoint"
          :auth-token="authToken"
        />
        <CacheTab v-else-if="activeTab === 'cache'" :data="data as any" />
        <JobsTab v-else-if="activeTab === 'jobs'" :data="data as any" />
        <ConfigTab v-else-if="activeTab === 'config'" :data="data as any" />
        <InternalsTab
          v-else-if="activeTab === 'internals'"
          :data="data as any"
          :base-url="baseUrl"
          :debug-endpoint="debugEndpoint"
          :auth-token="authToken"
        />
        <CustomPaneTab
          v-else-if="activeTab.startsWith('custom-')"
          :pane="getCustomPane(activeTab)!"
          :base-url="baseUrl"
          :auth-token="authToken"
        />
      </template>
    </div>
  </div>
</template>
