// src/vue/components/StatsBar/StatsBar.vue
<script setup lang="ts">
/**
 * Main stats bar component.
 *
 * Fixed bar at the bottom of the viewport showing live server metrics.
 * Uses SSE/polling for real-time updates, with sparkline tooltips.
 * Auto-hides on 403, persists visibility to localStorage.
 */
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { useServerStats } from '../../composables/useServerStats.js'
import { useFeatures } from '../../composables/useFeatures.js'
import { useTheme } from '../../composables/useTheme.js'
import {
  getMetricsByGroup,
  getVisibleMetricGroups,
  detectMetricGroupsFromStats,
  formatBytes,
} from '../../../core/index.js'
import type { StatsBarConfig } from '../../../core/index.js'
import { TAB_ICONS } from '../../../core/index.js'
import MetricCard from './MetricCard.vue'

const props = withDefaults(defineProps<StatsBarConfig & { debugPanelOpen?: boolean }>(), {
  baseUrl: '',
  endpoint: '/admin/api/server-stats',
  channelName: 'admin/server-stats',
  pollInterval: 3000,
  debugEndpoint: '/admin/api/debug',
  debugPanelOpen: false,
})

const emit = defineEmits<{
  openDebugPanel: []
  connectionChange: [isConnected: boolean]
}>()

const { stats, history, isStale, isUnauthorized, isConnected, connectionMode } = useServerStats({
  baseUrl: props.baseUrl,
  endpoint: props.endpoint,
  channelName: props.channelName,
  authToken: props.authToken,
  pollInterval: props.pollInterval,
})

watch(isConnected, (value) => {
  emit('connectionChange', value)
})

const { features } = useFeatures({
  baseUrl: props.baseUrl,
  debugEndpoint: props.debugEndpoint,
  authToken: props.authToken,
})

const { theme } = useTheme()

const STORAGE_KEY = 'admin:stats-bar'
const visible = ref(true)
const scrollRef = ref<HTMLDivElement | null>(null)

onMounted(() => {
  visible.value = localStorage.getItem(STORAGE_KEY) !== 'hidden'

  // Horizontal wheel scroll
  const el = scrollRef.value
  if (el) {
    const handler = (e: WheelEvent) => {
      if (Math.abs(e.deltaX) > Math.abs(e.deltaY)) return
      e.preventDefault()
      el.scrollLeft += e.deltaY
    }
    el.addEventListener('wheel', handler, { passive: false })
    onUnmounted(() => el.removeEventListener('wheel', handler))
  }
})

function toggleVisibility() {
  visible.value = !visible.value
  localStorage.setItem(STORAGE_KEY, visible.value ? 'visible' : 'hidden')
}

// Auto-hide on unauthorized
watch(isUnauthorized, (unauthorized) => {
  if (unauthorized) visible.value = false
})

// Group metrics for rendering with separators, filtered by available data.
// Primary: detect groups from actual stats data (mirrors old vanilla JS behavior).
// Fallback: use feature flags from the debug endpoint before stats arrive.
const visibleGroups = computed(() => {
  if (stats.value) {
    return detectMetricGroupsFromStats(stats.value as unknown as Record<string, unknown>)
  }
  return getVisibleMetricGroups(features.value)
})

const metricGroups = computed(() => {
  const groups = getMetricsByGroup()
  return Array.from(groups.entries())
    .filter(([name]) => visibleGroups.value.has(name))
    .map(([name, metrics]) => ({
      name,
      metrics,
    }))
})

function getMetricHistory(historyKey?: string): number[] {
  if (!historyKey) return []
  return (history as Record<string, number[]>)[historyKey] || []
}

// Toggle summary values for collapsed state
const cpuSummary = computed(() => {
  if (!stats.value) return '...'
  return `${stats.value.cpuPercent.toFixed(0)}%`
})

const memSummary = computed(() => {
  if (!stats.value) return '...'
  return stats.value.memHeapUsed !== undefined
    ? Math.round(stats.value.memHeapUsed / (1024 * 1024)) + 'M'
    : '-'
})

const redisSummary = computed(() => {
  if (!stats.value) return '...'
  return stats.value.redisOk ? '\u2713' : '\u2717'
})

const themeAttr = computed(() => theme.value)
</script>

<template>
  <!-- Stats Bar -->
  <div
    v-if="!isUnauthorized"
    id="ss-bar"
    :class="['ss-bar', { 'ss-hidden': !visible }]"
    :data-ss-theme="themeAttr"
  >
    <div class="ss-bar-left">
      <button
        v-if="features.tracing || visibleGroups.has('redis') || visibleGroups.has('queue')"
        type="button"
        :class="['ss-dbg-btn', { 'ss-dbg-active': debugPanelOpen }]"
        title="Toggle debug panel"
        id="ss-dbg-wrench"
        @click="emit('openDebugPanel')"
      >
        <svg
          width="14"
          height="14"
          :viewBox="TAB_ICONS.wrench.viewBox"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          v-html="TAB_ICONS.wrench.elements.join('')"
        ></svg>
      </button>
      <div :class="['ss-dot', { 'ss-stale': isStale }]"></div>
    </div>

    <div ref="scrollRef" id="ss-bar-scroll" class="ss-bar-scroll">
      <template v-for="(group, gi) in metricGroups" :key="group.name">
        <div class="ss-group">
          <MetricCard
            v-for="metric in group.metrics"
            :key="metric.id"
            :metric="metric"
            :stats="stats"
            :history="getMetricHistory(metric.historyKey)"
          />
        </div>
        <div v-if="gi < metricGroups.length - 1" class="ss-group-sep"></div>
      </template>
    </div>
  </div>

  <!-- Toggle Button -->
  <button
    v-if="!isUnauthorized"
    type="button"
    :class="['ss-toggle', visible ? 'ss-visible' : 'ss-collapsed']"
    :data-ss-theme="themeAttr"
    :title="visible ? 'Hide stats bar' : 'Show stats bar'"
    @click="toggleVisibility"
  >
    <span v-if="!visible && stats" class="ss-toggle-summary" style="display: flex">
      <span
        v-if="visibleGroups.has('process')"
        :class="['ss-value', stats.cpuPercent > 80 ? 'ss-red' : stats.cpuPercent > 50 ? 'ss-amber' : 'ss-green']"
      >{{ cpuSummary }}</span>
      <span v-if="visibleGroups.has('process')" class="ss-value ss-green">{{ memSummary }}</span>
      <span
        v-if="visibleGroups.has('redis') && stats?.redisOk !== undefined"
        :class="['ss-value', stats?.redisOk ? 'ss-green' : 'ss-red']"
        >{{ redisSummary }}</span
      >
    </span>
    <span v-if="visible" class="ss-toggle-label" style="color: #737373">hide stats</span>
    <span class="ss-toggle-arrow">{{ visible ? '\u25BC' : '\u25B2' }}</span>
  </button>
</template>

// src/react/components/StatsBar/StatsBar.tsx
import React, { useState, useCallback, useEffect, useRef, useMemo } from 'react'

import {
  getVisibleMetricGroups,
  detectMetricGroupsFromStats,
} from '../../../core/feature-detect.js'
import { METRIC_DEFINITIONS } from '../../../core/metrics.js'
import { useFeatures } from '../../hooks/useFeatures.js'
import { useServerStats } from '../../hooks/useServerStats.js'
import { useTheme } from '../../hooks/useTheme.js'
import { MetricCard } from './MetricCard.js'

import type { StatsBarProps as StatsBarPropsBase, DebugPanelProps } from '../../../core/types.js'
import { TAB_ICONS } from '../../../core/icons.js'

interface StatsBarProps extends StatsBarPropsBase {
  /** Options for feature detection. */
  featureOptions?: DebugPanelProps
  /** Whether to auto-hide on 403. */
  autoHideOnUnauthorized?: boolean
  /** Callback to toggle the debug panel (renders wrench button in bar-left). */
  onOpenDebugPanel?: () => void
  /** Whether the debug panel is currently open (controls active styling on wrench). */
  debugPanelOpen?: boolean
  /** Callback invoked when the live (SSE/Transmit) connection state changes. */
  onConnectionChange?: (isConnected: boolean) => void
}

/**
 * Fixed stats bar at the bottom of the viewport.
 *
 * Displays real-time server metrics with sparklines, tooltips,
 * and a show/hide toggle persisted to localStorage.
 */
export function StatsBar(props: StatsBarProps) {
  const {
    featureOptions,
    autoHideOnUnauthorized = true,
    onOpenDebugPanel,
    debugPanelOpen = false,
    onConnectionChange,
    ...statsOptions
  } = props

  const { stats, getHistory, isConnected, isStale, unauthorized } = useServerStats(statsOptions)

  // Report connection state changes to parent
  useEffect(() => {
    onConnectionChange?.(isConnected)
  }, [isConnected, onConnectionChange])
  const { features } = useFeatures(featureOptions)
  const { theme } = useTheme()

  const [visible, setVisible] = useState(() => {
    if (typeof window === 'undefined') return true
    return localStorage.getItem('admin:stats-bar') !== 'hidden'
  })

  const barRef = useRef<HTMLDivElement>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  // Auto-hide on unauthorized
  useEffect(() => {
    if (autoHideOnUnauthorized && unauthorized) {
      setVisible(false)
    }
  }, [autoHideOnUnauthorized, unauthorized])

  const toggleVisible = useCallback(() => {
    setVisible((prev) => {
      const next = !prev
      localStorage.setItem('admin:stats-bar', next ? 'visible' : 'hidden')
      return next
    })
  }, [])

  // Horizontal wheel scroll
  useEffect(() => {
    const el = scrollRef.current
    if (!el) return

    const handler = (e: WheelEvent) => {
      if (Math.abs(e.deltaX) > Math.abs(e.deltaY)) return
      e.preventDefault()
      el.scrollLeft += e.deltaY
    }

    el.addEventListener('wheel', handler, { passive: false })
    return () => el.removeEventListener('wheel', handler)
  }, [])

  // Visible metric groups: derive from actual stats data when available,
  // fall back to feature flags from the debug endpoint.
  // This mirrors the old vanilla JS behavior where groups were shown
  // based on what data the server actually sends, not what the debug
  // endpoint reports.
  const visibleGroups = useMemo(() => {
    if (stats) {
      return detectMetricGroupsFromStats(stats as unknown as Record<string, unknown>)
    }
    // Before stats arrive, use feature flags (if available) for initial render
    return getVisibleMetricGroups(features)
  }, [stats, features])

  // Filter metrics by visible groups
  const visibleMetrics = useMemo(
    () => METRIC_DEFINITIONS.filter((m) => visibleGroups.has(m.group || 'core')),
    [visibleGroups]
  )

  // Group metrics for separator display
  const groupedMetrics = useMemo(() => {
    const groups: { group: string; metrics: typeof METRIC_DEFINITIONS }[] = []
    let currentGroup = ''
    for (const metric of visibleMetrics) {
      const metricGroup = metric.group || 'core'
      if (metricGroup !== currentGroup) {
        currentGroup = metricGroup
        groups.push({ group: currentGroup, metrics: [] })
      }
      groups[groups.length - 1].metrics.push(metric)
    }
    return groups
  }, [visibleMetrics])

  if (autoHideOnUnauthorized && unauthorized) {
    return null
  }

  return (
    <>
      {/* Toggle button */}
      <button
        type="button"
        className={`ss-toggle ${visible ? 'ss-visible' : 'ss-collapsed'}`}
        onClick={toggleVisible}
        title={visible ? 'Hide stats bar' : 'Show stats bar'}
        data-ss-theme={theme}
      >
        {!visible && stats && (
          <span className="ss-toggle-summary" style={{ display: 'flex' }}>
            {visibleGroups.has('process') && (
              <>
                <span
                  className={`ss-value ${stats.cpuPercent > 80 ? 'ss-red' : stats.cpuPercent > 50 ? 'ss-amber' : 'ss-green'}`}
                >
                  {stats.cpuPercent.toFixed(0)}%
                </span>
                <span className="ss-value ss-green">
                  {stats.memHeapUsed !== undefined
                    ? Math.round(stats.memHeapUsed / (1024 * 1024)) + 'M'
                    : '-'}
                </span>
              </>
            )}
            {visibleGroups.has('redis') && stats.redisOk !== undefined && (
              <span className={`ss-value ${stats.redisOk ? 'ss-green' : 'ss-red'}`}>
                {stats.redisOk ? '\u2713' : '\u2717'}
              </span>
            )}
          </span>
        )}
        {visible && <span className="ss-toggle-label" style={{ color: '#737373' }}>hide stats</span>}
        <span className="ss-toggle-arrow">{visible ? '\u25BC' : '\u25B2'}</span>
      </button>

      {/* Stats bar */}
      <div ref={barRef} className={visible ? 'ss-bar' : 'ss-bar ss-hidden'} data-ss-theme={theme}>
        <div className="ss-bar-left">
          {onOpenDebugPanel && (
            <button
              type="button"
              className={`ss-dbg-btn ${debugPanelOpen ? 'ss-dbg-active' : ''}`}
              onClick={onOpenDebugPanel}
              title="Toggle debug panel"
              id="ss-dbg-wrench"
            >
              <svg
                width="14"
                height="14"
                viewBox={TAB_ICONS.wrench.viewBox}
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                dangerouslySetInnerHTML={{ __html: TAB_ICONS.wrench.elements.join('') }}
              />
            </button>
          )}
          <div className={isStale ? 'ss-dot ss-stale' : 'ss-dot'} />
        </div>

        <div ref={scrollRef} className="ss-bar-scroll" id="ss-bar-scroll">
          {stats &&
            groupedMetrics.map((group, gi) => (
              <React.Fragment key={group.group}>
                {gi > 0 && <div className="ss-group-sep" />}
                <div className="ss-group">
                  {group.metrics.map((metric) => (
                    <MetricCard
                      key={metric.id}
                      metric={metric}
                      stats={stats}
                      history={getHistory(metric.historyKey || '')}
                    />
                  ))}
                </div>
              </React.Fragment>
            ))}
        </div>
      </div>
    </>
  )
}
