// src/vue/components/DebugPanel/tabs/EmailsTab.vue
<script setup lang="ts">
/**
 * Emails table with preview tab for the debug panel.
 */
import { computed, ref } from 'vue'
import { timeAgo, formatTime } from '../../../../core/index.js'
import { useResizableTable } from '../../../composables/useResizableTable.js'
import type { EmailRecord } from '../../../../core/index.js'

const props = defineProps<{
  data: { emails?: EmailRecord[] } | EmailRecord[] | null
  dashboardPath?: string
  debugEndpoint?: string
  authToken?: string
}>()

const search = ref('')
const previewEmail = ref<EmailRecord | null>(null)
const previewHtml = ref<string | null>(null)
const loadingPreview = ref(false)

const emails = computed<EmailRecord[]>(() => {
  const d = props.data
  const arr = d ? (Array.isArray(d) ? d : d.emails) || [] : []
  if (!search.value.trim()) return arr
  const term = search.value.toLowerCase()
  return arr.filter(
    (e: EmailRecord) =>
      e.subject.toLowerCase().includes(term) ||
      e.from.toLowerCase().includes(term) ||
      e.to.toLowerCase().includes(term) ||
      (e.mailer && e.mailer.toLowerCase().includes(term))
  )
})

const summary = computed(() => {
  const d = props.data
  const arr = d ? (Array.isArray(d) ? d : d.emails) || [] : []
  return `${arr.length} emails`
})

function statusClass(status: string): string {
  const map: Record<string, string> = {
    sent: 'ss-dbg-email-status-sent',
    sending: 'ss-dbg-email-status-sending',
    queueing: 'ss-dbg-email-status-queued',
    queued: 'ss-dbg-email-status-queued',
    failed: 'ss-dbg-email-status-failed',
  }
  return map[status] || ''
}

async function openPreview(email: EmailRecord) {
  previewEmail.value = email
  previewHtml.value = email.html || null

  // If no HTML in row data (SQLite path strips bodies), fetch from preview endpoint
  if (!previewHtml.value && email.id) {
    loadingPreview.value = true
    try {
      const endpoint = props.debugEndpoint || '/admin/api/debug'
      const headers: Record<string, string> = {}
      if (props.authToken) headers['Authorization'] = `Bearer ${props.authToken}`
      const res = await fetch(`${endpoint}/emails/${email.id}/preview`, {
        headers,
        credentials: props.authToken ? 'omit' : 'include',
      })
      if (res.ok) {
        previewHtml.value = await res.text()
      }
    } catch {
      // Preview fetch failed — show fallback
    } finally {
      loadingPreview.value = false
    }
  }
}

function closePreview() {
  previewEmail.value = null
  previewHtml.value = null
  loadingPreview.value = false
}

const { tableRef } = useResizableTable(() => emails.value)
</script>

<template>
  <div style="position: relative; height: 100%">
    <!-- Email preview overlay -->
    <div v-if="previewEmail" class="ss-dbg-email-preview">
      <div class="ss-dbg-email-preview-header">
        <div class="ss-dbg-email-preview-meta">
          <div><strong>From:</strong> {{ previewEmail.from }}</div>
          <div><strong>To:</strong> {{ previewEmail.to }}</div>
          <div v-if="previewEmail.cc"><strong>CC:</strong> {{ previewEmail.cc }}</div>
          <div><strong>Subject:</strong> {{ previewEmail.subject }}</div>
          <div>
            <strong>Status:</strong>
            <span :class="['ss-dbg-email-status', statusClass(previewEmail.status)]">
              {{ previewEmail.status }}
            </span>
          </div>
        </div>
        <button type="button" class="ss-dbg-btn-clear" @click="closePreview">&times;</button>
      </div>
      <div v-if="loadingPreview" class="ss-dbg-empty">Loading preview...</div>
      <iframe
        v-else-if="previewHtml"
        class="ss-dbg-email-iframe"
        :srcdoc="previewHtml"
      ></iframe>
      <div v-else class="ss-dbg-empty">No HTML content</div>
    </div>

    <!-- Email list -->
    <template v-if="!previewEmail">
      <div class="ss-dbg-search-bar">
        <input v-model="search" class="ss-dbg-search" placeholder="Filter emails..." type="text" />
        <span class="ss-dbg-summary">{{ summary }}</span>
      </div>

      <div v-if="emails.length === 0" class="ss-dbg-empty">No emails captured</div>

      <table v-else ref="tableRef" class="ss-dbg-table">
        <thead>
          <tr>
            <th>#</th>
            <th>From</th>
            <th>To</th>
            <th>Subject</th>
            <th>Status</th>
            <th>Mailer</th>
            <th title="Attachments">&#x1F4CE;</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="e in emails" :key="e.id" class="ss-dbg-email-row" @click="openPreview(e)">
            <td class="ss-dbg-c-dim" style="white-space: nowrap">{{ e.id }}</td>
            <td class="ss-dbg-c-secondary" :title="e.from">{{ e.from }}</td>
            <td class="ss-dbg-c-secondary" :title="e.to">{{ e.to }}</td>
            <td class="ss-dbg-c-sql">{{ e.subject }}</td>
            <td>
              <span :class="['ss-dbg-email-status', statusClass(e.status)]">
                {{ e.status }}
              </span>
            </td>
            <td class="ss-dbg-c-muted">{{ e.mailer }}</td>
            <td class="ss-dbg-c-dim" style="text-align: center">
              {{ e.attachmentCount > 0 ? e.attachmentCount : '-' }}
            </td>
            <td class="ss-dbg-event-time" :title="formatTime(e.timestamp)">
              {{ timeAgo(e.timestamp) }}
            </td>
          </tr>
        </tbody>
      </table>
    </template>
  </div>
</template>

// src/react/components/DebugPanel/tabs/EmailsTab.tsx
import React, { useState, useMemo, useCallback } from 'react'

import { timeAgo, formatTime } from '../../../../core/formatters.js'
import { useDebugData } from '../../../hooks/useDebugData.js'
import { useResizableTable } from '../../../hooks/useResizableTable.js'

import type { EmailRecord, DebugPanelProps } from '../../../../core/types.js'

interface EmailsTabProps {
  options?: DebugPanelProps
}

export function EmailsTab({ options }: EmailsTabProps) {
  const { data, isLoading, error } = useDebugData<{ emails: EmailRecord[] }>('emails', options)
  const [search, setSearch] = useState('')
  const [previewId, setPreviewId] = useState<number | null>(null)
  const [previewHtml, setPreviewHtml] = useState<string | null>(null)
  const [loadingPreview, setLoadingPreview] = useState(false)

  const emails = useMemo(() => {
    const items = data?.emails || []
    if (!search) return items
    const lower = search.toLowerCase()
    return items.filter(
      (e) =>
        (e.subject || '').toLowerCase().includes(lower) ||
        (e.to || '').toLowerCase().includes(lower) ||
        (e.from || '').toLowerCase().includes(lower) ||
        (e.mailer || '').toLowerCase().includes(lower)
    )
  }, [data, search])

  const previewEmail = useMemo(() => emails.find((e) => e.id === previewId), [emails, previewId])

  const openPreview = useCallback(
    async (email: EmailRecord) => {
      setPreviewId(email.id)
      setPreviewHtml(email.html || null)

      if (!email.html && email.id) {
        setLoadingPreview(true)
        try {
          const endpoint = options?.debugEndpoint || '/admin/api/debug'
          const headers: Record<string, string> = {}
          if (options?.authToken) headers['Authorization'] = `Bearer ${options.authToken}`
          const res = await fetch(`${endpoint}/emails/${email.id}/preview`, {
            headers,
            credentials: options?.authToken ? 'omit' : 'include',
          })
          if (res.ok) {
            setPreviewHtml(await res.text())
          }
        } catch {
          // Preview fetch failed
        } finally {
          setLoadingPreview(false)
        }
      }
    },
    [options]
  )

  const closePreview = useCallback(() => {
    setPreviewId(null)
    setPreviewHtml(null)
    setLoadingPreview(false)
  }, [])

  const statusColorMap: Record<string, string> = {
    sent: 'ss-dbg-email-status-sent',
    sending: 'ss-dbg-email-status-sending',
    queueing: 'ss-dbg-email-status-queued',
    queued: 'ss-dbg-email-status-queued',
    failed: 'ss-dbg-email-status-failed',
  }

  const tableRef = useResizableTable([emails])

  if (isLoading && !data) {
    return <div className="ss-dbg-empty">Loading emails...</div>
  }

  if (error) {
    return <div className="ss-dbg-empty">Error: {error.message}</div>
  }

  // Email preview overlay
  if (previewEmail) {
    return (
      <div className="ss-dbg-email-preview">
        <div className="ss-dbg-email-preview-header">
          <div className="ss-dbg-email-preview-meta">
            <div>
              <strong>Subject:</strong> {previewEmail.subject}
            </div>
            <div>
              <strong>From:</strong> {previewEmail.from}
            </div>
            <div>
              <strong>To:</strong> {previewEmail.to}
            </div>
            {previewEmail.cc && (
              <div>
                <strong>CC:</strong> {previewEmail.cc}
              </div>
            )}
          </div>
          <button className="ss-dbg-btn-clear" onClick={closePreview} type="button">
            {'\u00D7'}
          </button>
        </div>
        {loadingPreview ? (
          <div className="ss-dbg-empty">Loading preview...</div>
        ) : previewHtml ? (
          <iframe
            className="ss-dbg-email-iframe"
            srcDoc={previewHtml}
            title="Email preview"
            sandbox=""
          />
        ) : (
          <div style={{ padding: '12px', whiteSpace: 'pre-wrap' }}>
            {previewEmail.text || 'No content'}
          </div>
        )}
      </div>
    )
  }

  return (
    <div>
      <div className="ss-dbg-search-bar">
        <input
          type="text"
          className="ss-dbg-search"
          placeholder="Filter emails..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <span className="ss-dbg-summary">{emails.length} emails</span>
      </div>

      {emails.length === 0 ? (
        <div className="ss-dbg-empty">No emails captured</div>
      ) : (
        <table ref={tableRef} className="ss-dbg-table">
          <colgroup>
            <col style={{ width: '50px' }} />
            <col style={{ width: '140px' }} />
            <col style={{ width: '140px' }} />
            <col />
            <col style={{ width: '70px' }} />
            <col style={{ width: '80px' }} />
            <col style={{ width: '40px' }} />
            <col style={{ width: '80px' }} />
          </colgroup>
          <thead>
            <tr>
              <th>#</th>
              <th>From</th>
              <th>To</th>
              <th>Subject</th>
              <th>Status</th>
              <th>Mailer</th>
              <th title="Attachments">{'\u{1F4CE}'}</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            {emails.map((email) => (
              <tr
                key={email.id}
                className="ss-dbg-email-row"
                onClick={() => openPreview(email)}
              >
                <td className="ss-dbg-c-dim" style={{ whiteSpace: 'nowrap' }}>
                  {email.id}
                </td>
                <td className="ss-dbg-c-secondary" title={email.from}>
                  {email.from}
                </td>
                <td className="ss-dbg-c-secondary" title={email.to}>
                  {email.to}
                </td>
                <td className="ss-dbg-c-sql">{email.subject}</td>
                <td>
                  <span className={`ss-dbg-email-status ${statusColorMap[email.status] || ''}`}>
                    {email.status}
                  </span>
                </td>
                <td className="ss-dbg-c-muted">{email.mailer}</td>
                <td className="ss-dbg-c-dim" style={{ textAlign: 'center' }}>
                  {email.attachmentCount > 0 ? email.attachmentCount : '-'}
                </td>
                <td
                  className="ss-dbg-event-time"
                  title={formatTime(
                    email.timestamp ||
                      (email as unknown as Record<string, number>).created_at ||
                      (email as unknown as Record<string, number>).createdAt
                  )}
                >
                  {timeAgo(
                    email.timestamp ||
                      (email as unknown as Record<string, number>).created_at ||
                      (email as unknown as Record<string, number>).createdAt
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}

export default EmailsTab
