// src/vue/components/Dashboard/sections/CacheSection.vue
<script setup lang="ts">
/**
 * Cache inspector section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React CacheSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import { ApiClient, DashboardApi } from '../../../../core/index.js'
import JsonViewer from '../../shared/JsonViewer.vue'
import FilterBar from '../shared/FilterBar.vue'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

interface CacheStats {
  connected?: boolean
  hits?: number
  misses?: number
  hitRate?: number
  memoryUsedBytes?: number
  memoryUsedHuman?: string
  connectedClients?: number
  totalKeys?: number
  keyCount?: number
}

interface CacheKeyEntry {
  key: string
  type: string
  ttl: number
  size?: number | null
}

interface CacheResponse {
  available?: boolean
  stats?: CacheStats | null
  keys?: CacheKeyEntry[]
  data?: CacheKeyEntry[]
  cursor?: string
}

const {
  data,
  loading,
  setSearch,
  mutate,
} = useDashboardData(() => 'cache', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const cacheClient = new ApiClient({ baseUrl: baseUrl || '', authToken })
const cacheApi = new DashboardApi(cacheClient, dashboardEndpoint || '/__stats/api')

const search = ref('')
const selectedKey = ref<string | null>(null)
const keyValue = ref<unknown>(null)
const keyValueLoading = ref(false)
const keyValueError = ref<string | null>(null)

const cacheData = computed<CacheResponse | null>(() => {
  return data.value as CacheResponse | null
})

const keys = computed<CacheKeyEntry[]>(() => {
  return cacheData.value?.keys || cacheData.value?.data || []
})

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}

async function handleDelete(key: string) {
  if (!confirm(`Delete cache key "${key}"?`)) return
  try {
    await mutate(`cache/${encodeURIComponent(key)}`, 'delete')
    if (selectedKey.value === key) {
      selectedKey.value = null
      keyValue.value = null
      keyValueError.value = null
    }
  } catch {
    // silently fail
  }
}

async function handleKeyClick(key: string) {
  if (selectedKey.value === key) {
    selectedKey.value = null
    keyValue.value = null
    keyValueError.value = null
    return
  }
  selectedKey.value = key
  keyValue.value = null
  keyValueError.value = null
  keyValueLoading.value = true
  try {
    const result = await cacheApi.fetchCacheKey(key)
    keyValue.value =
      result.value !== undefined ? result.value :
      result.data !== undefined ? result.data : result
    keyValueError.value = null
  } catch {
    keyValue.value = null
    keyValueError.value = 'Failed to fetch key value'
  } finally {
    keyValueLoading.value = false
  }
}
</script>

<template>
  <div>
    <!-- Stats -->
    <div v-if="cacheData?.available && cacheData?.stats" class="ss-dash-cache-stats">
      <div class="ss-dash-cache-stat">
        <span class="ss-dash-cache-stat-label">Hit Rate:</span>
        <span class="ss-dash-cache-stat-value">{{ (cacheData.stats.hitRate ?? 0).toFixed(1) }}%</span>
      </div>
      <div class="ss-dash-cache-stat">
        <span class="ss-dash-cache-stat-label">Hits:</span>
        <span class="ss-dash-cache-stat-value">{{ cacheData.stats.hits ?? 0 }}</span>
      </div>
      <div class="ss-dash-cache-stat">
        <span class="ss-dash-cache-stat-label">Misses:</span>
        <span class="ss-dash-cache-stat-value">{{ cacheData.stats.misses ?? 0 }}</span>
      </div>
      <div class="ss-dash-cache-stat">
        <span class="ss-dash-cache-stat-label">Keys:</span>
        <span class="ss-dash-cache-stat-value">
          {{ cacheData.stats.totalKeys || cacheData.stats.keyCount || keys.length || 0 }}
        </span>
      </div>
    </div>

    <FilterBar
      :model-value="search"
      placeholder="Filter cache keys..."
      :summary="`${keys.length} keys`"
      @update:model-value="handleSearch"
    />

    <div v-if="loading && !data" class="ss-dash-empty">Loading cache...</div>

    <div v-else-if="!cacheData || !cacheData.available" class="ss-dash-empty">
      Cache inspector not available
    </div>

    <template v-else>
      <div class="ss-dash-table-wrap">
        <table v-if="keys.length > 0" class="ss-dash-table">
          <thead>
            <tr>
              <th>Key</th>
              <th>Type</th>
              <th>Size</th>
              <th>TTL</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="k in keys"
              :key="k.key"
              class="ss-dash-clickable"
              @click="handleKeyClick(k.key)"
            >
              <td>
                <span
                  :title="k.key"
                  style="color: var(--ss-sql-color); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                >
                  {{ k.key }}
                </span>
              </td>
              <td><span style="color: var(--ss-muted)">{{ k.type }}</span></td>
              <td>{{ k.size !== null && k.size !== undefined ? k.size + 'B' : '-' }}</td>
              <td>{{ k.ttl > 0 ? `${k.ttl}s` : '-' }}</td>
              <td>
                <button
                  type="button"
                  class="ss-dash-retry-btn"
                  @click.stop="handleDelete(k.key)"
                >
                  Delete
                </button>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-else class="ss-dash-empty">No cache keys found</div>
      </div>
    </template>

    <!-- Key value detail -->
    <div v-if="selectedKey" class="ss-dash-cache-detail">
      <h4>Key: {{ selectedKey }}</h4>
      <div v-if="keyValueLoading" class="ss-dash-empty">Loading value...</div>
      <div v-else-if="keyValueError" class="ss-dash-empty" style="color: var(--ss-red-fg)">
        {{ keyValueError }}
      </div>
      <JsonViewer v-else :value="keyValue" />
    </div>
  </div>
</template>

// src/react/components/Dashboard/sections/CacheSection.tsx
import React, { useState, useCallback } from 'react'

import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { JsonViewer } from '../../shared/JsonViewer.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../shared/FilterBar.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface CacheStats {
  connected: boolean
  hits: number
  misses: number
  hitRate: number
  memoryUsedBytes: number
  memoryUsedHuman: string
  connectedClients: number
  totalKeys: number
  keyCount?: number
}

interface CacheKeyEntry {
  key: string
  type: string
  ttl: number
  size?: number | null
}

interface CacheResponse {
  available: boolean
  stats: CacheStats | null
  keys?: CacheKeyEntry[]
  data?: CacheKeyEntry[]
  cursor: string
}

interface CacheSectionProps {
  options?: DashboardHookOptions
}

export function CacheSection({ options = {} }: CacheSectionProps) {
  const [search, setSearch] = useState('')
  const [selectedKey, setSelectedKey] = useState<string | null>(null)
  const [keyValue, setKeyValue] = useState<unknown>(null)
  const [keyValueLoading, setKeyValueLoading] = useState(false)
  const [keyValueError, setKeyValueError] = useState<string | null>(null)

  const { data, isLoading, mutate, getApi } = useDashboardData<CacheResponse>('cache', {
    ...options,
    search,
  })
  const cacheData = data

  const handleDelete = useCallback(
    async (key: string) => {
      if (!confirm(`Delete cache key "${key}"?`)) return
      try {
        await mutate(`cache/${encodeURIComponent(key)}`, 'delete')
        // Clear selection if the deleted key was selected
        if (selectedKey === key) {
          setSelectedKey(null)
          setKeyValue(null)
          setKeyValueError(null)
        }
      } catch {
        // Silently fail
      }
    },
    [mutate, selectedKey]
  )

  const handleKeyClick = useCallback(
    async (key: string) => {
      if (selectedKey === key) {
        setSelectedKey(null)
        setKeyValue(null)
        setKeyValueError(null)
        return
      }
      setSelectedKey(key)
      setKeyValue(null)
      setKeyValueError(null)
      setKeyValueLoading(true)
      try {
        const api = getApi()
        const result = await api.fetchCacheKey(key)
        setKeyValue(
          result.value !== undefined
            ? result.value
            : result.data !== undefined
              ? result.data
              : result
        )
        setKeyValueError(null)
      } catch {
        setKeyValue(null)
        setKeyValueError('Failed to fetch key value')
      } finally {
        setKeyValueLoading(false)
      }
    },
    [selectedKey, getApi]
  )

  return (
    <div>
      {/* Stats */}
      {cacheData?.available && cacheData?.stats && (
        <div className="ss-dash-cache-stats">
          <div className="ss-dash-cache-stat">
            <span className="ss-dash-cache-stat-label">Hit Rate:</span>
            <span className="ss-dash-cache-stat-value">
              {(cacheData.stats.hitRate ?? 0).toFixed(1)}%
            </span>
          </div>
          <div className="ss-dash-cache-stat">
            <span className="ss-dash-cache-stat-label">Hits:</span>
            <span className="ss-dash-cache-stat-value">{cacheData.stats.hits ?? 0}</span>
          </div>
          <div className="ss-dash-cache-stat">
            <span className="ss-dash-cache-stat-label">Misses:</span>
            <span className="ss-dash-cache-stat-value">{cacheData.stats.misses ?? 0}</span>
          </div>
          <div className="ss-dash-cache-stat">
            <span className="ss-dash-cache-stat-label">Keys:</span>
            <span className="ss-dash-cache-stat-value">
              {cacheData.stats.totalKeys || cacheData.stats.keyCount || cacheData.keys?.length || 0}
            </span>
          </div>
        </div>
      )}

      <FilterBar search={search} onSearchChange={setSearch} placeholder="Filter cache keys..." summary={`${(cacheData?.keys || cacheData?.data || []).length} keys`} />

      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading cache...</div>
      ) : !cacheData || !cacheData.available ? (
        <div className="ss-dash-empty">Cache inspector not available</div>
      ) : (
        <div className="ss-dash-table-wrap">
          <DataTable
            columns={[
              {
                key: 'key',
                label: 'Key',
                render: (v: string) => (
                  <span
                    title={v}
                    style={{
                      color: 'var(--ss-sql-color)',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      whiteSpace: 'nowrap',
                      display: 'block',
                    }}
                  >
                    {v}
                  </span>
                ),
              },
              {
                key: 'type',
                label: 'Type',
                width: '70px',
                render: (v: string) => (
                  <span style={{ color: 'var(--ss-muted)' }}>{v}</span>
                ),
              },
              {
                key: 'size',
                label: 'Size',
                width: '60px',
                render: (v: number | null | undefined) =>
                  v !== null && v !== undefined ? v + 'B' : '-',
              },
              {
                key: 'ttl',
                label: 'TTL',
                width: '70px',
                render: (v: number) => (v > 0 ? `${v}s` : '-'),
              },
              {
                key: '_actions',
                label: '',
                width: '60px',
                render: (_: unknown, row: Record<string, unknown>) => (
                  <button
                    type="button"
                    className="ss-dash-retry-btn"
                    onClick={(e) => {
                      e.stopPropagation()
                      handleDelete(row.key as string)
                    }}
                  >
                    Delete
                  </button>
                ),
              },
            ]}
            data={cacheData.keys || cacheData.data || []}
            keyField="key"
            onRowClick={(row: Record<string, unknown>) =>
              handleKeyClick(row.key as string)
            }
            emptyMessage="No cache keys found"
          />
        </div>
      )}

      {selectedKey && (
        <div className="ss-dash-cache-detail">
          <h4>Key: {selectedKey}</h4>
          {keyValueLoading ? (
            <div className="ss-dash-empty">Loading value...</div>
          ) : keyValueError ? (
            <div className="ss-dash-empty" style={{ color: 'var(--ss-red-fg)' }}>
              {keyValueError}
            </div>
          ) : (
            <JsonViewer data={keyValue} />
          )}
        </div>
      )}
    </div>
  )
}

export default CacheSection
