// src/vue/components/Dashboard/sections/EventsSection.vue
<script setup lang="ts">
/**
 * Events section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React EventsSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { timeAgo, formatTime } from '../../../../core/index.js'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import FilterBar from '../shared/FilterBar.vue'
import PaginationControls from '../shared/PaginationControls.vue'
import JsonViewer from '../../shared/JsonViewer.vue'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

const {
  data,
  loading,
  pagination,
  goToPage,
  setSearch,
} = useDashboardData(() => 'events', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const search = ref('')

const events = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const d = data.value as Record<string, unknown>
  return (d.data || d.events || data.value || []) as Record<string, unknown>[]
})

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}
</script>

<template>
  <div>
    <FilterBar
      :model-value="search"
      placeholder="Filter events..."
      :summary="`${pagination.total ?? 0} events`"
      @update:model-value="handleSearch"
    />

    <div v-if="loading && !data" class="ss-dash-empty">Loading events...</div>

    <template v-else>
      <div class="ss-dash-table-wrap">
        <table v-if="events.length > 0" class="ss-dash-table">
          <colgroup>
            <col style="width: 40px" />
            <col />
            <col />
            <col style="width: 80px" />
          </colgroup>
          <thead>
            <tr>
              <th>#</th>
              <th>Event</th>
              <th>Data</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="e in events" :key="(e.id as string)">
              <td><span style="color: var(--ss-dim)">{{ e.id }}</span></td>
              <td>
                <span
                  class="ss-dash-event-name"
                  :title="((e.event_name as string) || (e.eventName as string) || (e.event as string) || '') as string"
                  style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                >
                  {{ (e.event_name as string) || (e.eventName as string) || (e.event as string) || '' }}
                </span>
              </td>
              <td>
                <JsonViewer :value="e.data" class="ss-dash-event-data" />
              </td>
              <td>
                <span
                  class="ss-dash-event-time"
                  :title="formatTime(((e.createdAt as string) || (e.created_at as string) || (e.timestamp as string)) as string)"
                >
                  {{ timeAgo(((e.createdAt as string) || (e.created_at as string) || (e.timestamp as string)) as string) }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-else class="ss-dash-empty">No events recorded yet</div>
      </div>
      <PaginationControls
        v-if="pagination.totalPages > 1"
        :page="pagination.page"
        :last-page="pagination.totalPages"
        :total="pagination.total"
        @page-change="goToPage"
      />
    </template>
  </div>
</template>

// src/react/components/Dashboard/sections/EventsSection.tsx
import React, { useState, useEffect } from 'react'

import { timeAgo, formatTime } from '../../../../core/formatters.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { JsonViewer } from '../../shared/JsonViewer.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../shared/FilterBar.js'
import { Pagination } from '../shared/Pagination.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface EventsSectionProps {
  options?: DashboardHookOptions
}

export function EventsSection({ options = {} }: EventsSectionProps) {
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')

  const { data, meta, isLoading } = useDashboardData('events', { ...options, page, search })
  const events = (data as Record<string, unknown>[]) || []

  useEffect(() => setPage(1), [search])

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Filter events..."
        summary={`${meta?.total ?? 0} events`}
      />
      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading events...</div>
      ) : (
        <>
          <div className="ss-dash-table-wrap">
            <DataTable
              columns={[
                {
                  key: 'id',
                  label: '#',
                  width: '40px',
                  render: (v: unknown) => (
                    <span style={{ color: 'var(--ss-dim)' }}>{v as string}</span>
                  ),
                },
                {
                  key: 'eventName',
                  label: 'Event',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const name = (row.event_name || row.eventName || row.event || '') as string
                    return (
                      <span
                        className="ss-dash-event-name"
                        title={name}
                        style={{
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          display: 'block',
                        }}
                      >
                        {name}
                      </span>
                    )
                  },
                },
                {
                  key: 'data',
                  label: 'Data',
                  render: (v: unknown) => (
                    <JsonViewer data={v} maxPreviewLength={80} className="ss-dash-event-data" />
                  ),
                },
                {
                  key: 'createdAt',
                  label: 'Time',
                  width: '80px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const ts = (row.createdAt || row.created_at || row.timestamp) as string
                    return <span className="ss-dash-event-time" title={formatTime(ts)}>{timeAgo(ts)}</span>
                  },
                },
              ]}
              data={events}
              emptyMessage="No events recorded yet"
            />
          </div>
          {meta && (
            <Pagination
              page={meta.page}
              lastPage={meta.lastPage}
              total={meta.total}
              onPageChange={setPage}
            />
          )}
        </>
      )}
    </div>
  )
}

export default EventsSection
