// src/vue/components/Dashboard/sections/LogsSection.vue
<script setup lang="ts">
/**
 * Logs section with structured filtering.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React LogsSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { timeAgo, formatTime } from '../../../../core/index.js'
import {
  LOG_LEVELS,
  resolveLogLevel,
  resolveLogMessage,
  resolveLogTimestamp,
  resolveLogRequestId,
  getLogLevelCssClass,
} from '../../../../core/log-utils.js'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import FilterBar from '../shared/FilterBar.vue'
import PaginationControls from '../shared/PaginationControls.vue'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

const {
  data,
  loading,
  error,
  pagination,
  filter: filterState,
  goToPage,
  setSearch,
  setFilter,
  refresh,
} = useDashboardData(() => 'logs', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const search = ref('')
const levelFilter = ref('all')
const reqIdFilter = ref('')
const reqIdInput = ref('')

interface StructuredFilter {
  field: string
  operator: string
  value: string
}

const structuredFilters = ref<StructuredFilter[]>([])
const structuredField = ref('level')
const structuredOp = ref('equals')
const structuredValue = ref('')

const logs = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const d = data.value as Record<string, unknown>
  return (d.data || d.logs || data.value || []) as Record<string, unknown>[]
})

const hasActiveFilters = computed(
  () =>
    levelFilter.value !== 'all' || reqIdFilter.value !== '' || structuredFilters.value.length > 0
)

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}

function handleLevelFilter(level: string) {
  levelFilter.value = level
  if (level === 'all') {
    setFilter('level', '')
  } else {
    setFilter('level', level)
  }
}

function handleReqIdClick(reqId: string) {
  reqIdFilter.value = reqId
  reqIdInput.value = reqId
  setFilter('request_id', reqId)
}

function handleReqIdInputSubmit() {
  const trimmed = reqIdInput.value.trim()
  reqIdFilter.value = trimmed
  setFilter('request_id', trimmed)
}

function clearReqIdFilter() {
  reqIdFilter.value = ''
  reqIdInput.value = ''
  setFilter('request_id', '')
}

function clearLevelFilter() {
  levelFilter.value = 'all'
  setFilter('level', '')
}

/**
 * Sync the structuredFilters array into the composable's filter state
 * using the same numbered key format as React:
 *   filter_field_0, filter_op_0, filter_value_0, ...
 */
function syncStructuredFilters() {
  const f = filterState as Record<string, string | number | boolean>
  // Remove all existing structured filter keys
  for (const key of Object.keys(f)) {
    if (
      key.startsWith('filter_field_') ||
      key.startsWith('filter_op_') ||
      key.startsWith('filter_value_')
    ) {
      delete f[key]
    }
  }
  // Re-add from current array
  structuredFilters.value.forEach((sf, idx) => {
    f[`filter_field_${idx}`] = sf.field
    f[`filter_op_${idx}`] = sf.operator
    f[`filter_value_${idx}`] = sf.value
  })
  pagination.page = 1
  refresh()
}

function addStructuredFilter() {
  const trimmed = structuredValue.value.trim()
  if (!trimmed) return
  structuredFilters.value.push({
    field: structuredField.value,
    operator: structuredOp.value,
    value: trimmed,
  })
  structuredValue.value = ''
  syncStructuredFilters()
}

function removeStructuredFilter(index: number) {
  structuredFilters.value.splice(index, 1)
  syncStructuredFilters()
}
</script>

<template>
  <div>
    <FilterBar
      :model-value="search"
      placeholder="Search logs..."
      :summary="`${pagination.total ?? 0} logs`"
      @update:model-value="handleSearch"
    >
      <div class="ss-dash-log-filters">
        <button
          v-for="level in LOG_LEVELS"
          :key="level"
          type="button"
          :class="`ss-dash-log-filter ${levelFilter === level ? 'ss-dash-active' : ''}`"
          @click="handleLevelFilter(level)"
        >
          {{ level }}
        </button>
        <input
          type="text"
          class="ss-dash-filter-input ss-dash-reqid-input"
          placeholder="Filter by request ID..."
          :value="reqIdInput"
          @input="reqIdInput = ($event.target as HTMLInputElement).value"
          @keydown.enter="handleReqIdInputSubmit"
        />
        <button
          v-if="reqIdInput || reqIdFilter"
          type="button"
          class="ss-dash-btn ss-dash-reqid-clear"
          @click="clearReqIdFilter"
        >
          Clear
        </button>
      </div>
    </FilterBar>

    <!-- Structured search panel -->
    <div class="ss-dash-structured-search">
      <select
        class="ss-dash-filter-select"
        :value="structuredField"
        @change="structuredField = ($event.target as HTMLSelectElement).value"
      >
        <option value="level">level</option>
        <option value="message">message</option>
        <option value="request_id">request_id</option>
        <option value="userId">userId</option>
        <option value="email">email</option>
        <option value="path">path</option>
      </select>
      <select
        class="ss-dash-filter-select"
        :value="structuredOp"
        @change="structuredOp = ($event.target as HTMLSelectElement).value"
      >
        <option value="equals">equals</option>
        <option value="contains">contains</option>
        <option value="starts_with">starts with</option>
      </select>
      <input
        class="ss-dash-filter-input"
        placeholder="Value..."
        :value="structuredValue"
        @input="structuredValue = ($event.target as HTMLInputElement).value"
        @keydown.enter="addStructuredFilter"
      />
      <button type="button" class="ss-dash-btn" @click="addStructuredFilter">Add</button>
    </div>

    <!-- Active filter chips -->
    <div v-if="hasActiveFilters" class="ss-dash-filter-chips">
      <span v-if="levelFilter !== 'all'" class="ss-dash-filter-chip">
        level: {{ levelFilter }}
        <button type="button" class="ss-dash-filter-chip-remove" @click="clearLevelFilter">
          &times;
        </button>
      </span>
      <span v-if="reqIdFilter" class="ss-dash-filter-chip">
        requestId: {{ reqIdFilter.slice(0, 8) }}...
        <button type="button" class="ss-dash-filter-chip-remove" @click="clearReqIdFilter">
          &times;
        </button>
      </span>
      <span v-for="(sf, idx) in structuredFilters" :key="idx" class="ss-dash-filter-chip">
        {{ sf.field }} {{ sf.operator }} "{{ sf.value }}"
        <button
          type="button"
          class="ss-dash-filter-chip-remove"
          @click="removeStructuredFilter(idx)"
        >
          &times;
        </button>
      </span>
    </div>

    <div v-if="error" class="ss-dash-empty">Failed to load logs</div>

    <div v-else-if="loading && !data" class="ss-dash-empty">Loading logs...</div>

    <template v-else-if="logs.length === 0">
      <div class="ss-dash-empty">
        No log entries{{
          reqIdFilter
            ? ` matching request ${reqIdFilter}`
            : levelFilter !== 'all'
              ? ` for ${levelFilter}`
              : ''
        }}
      </div>
    </template>

    <template v-else>
      <div class="ss-dash-log-entries">
        <div v-for="(log, i) in logs" :key="(log.id as string) || i" class="ss-dash-log-entry">
          <span
            :class="`ss-dash-log-level ${getLogLevelCssClass(resolveLogLevel(log), 'ss-dash-log-level')}`"
          >
            {{ resolveLogLevel(log).toUpperCase() }}
          </span>
          <span
            class="ss-dash-log-time"
            :title="resolveLogTimestamp(log) ? formatTime(resolveLogTimestamp(log)) : ''"
          >
            {{ resolveLogTimestamp(log) ? timeAgo(resolveLogTimestamp(log)) : '-' }}
          </span>
          <span
            v-if="resolveLogRequestId(log)"
            class="ss-dash-log-reqid"
            :title="resolveLogRequestId(log)"
            role="button"
            tabindex="0"
            @click="handleReqIdClick(resolveLogRequestId(log))"
            @keydown.enter="handleReqIdClick(resolveLogRequestId(log))"
          >
            {{ resolveLogRequestId(log).slice(0, 8) }}
          </span>
          <span v-else class="ss-dash-log-reqid-empty">--</span>
          <span class="ss-dash-log-msg">{{ resolveLogMessage(log) }}</span>
        </div>
      </div>
    </template>

    <PaginationControls
      v-if="pagination.totalPages > 1"
      :page="pagination.page"
      :last-page="pagination.totalPages"
      :total="pagination.total"
      @page-change="goToPage"
    />
  </div>
</template>

// src/react/components/Dashboard/sections/LogsSection.tsx
import React, { useState, useCallback } from 'react'

import { formatTime, timeAgo } from '../../../../core/formatters.js'
import {
  LOG_LEVELS,
  resolveLogLevel,
  resolveLogMessage,
  resolveLogTimestamp,
  resolveLogRequestId,
  getLogLevelCssClass,
} from '../../../../core/log-utils.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { FilterBar } from '../shared/FilterBar.js'
import { Pagination } from '../shared/Pagination.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface LogsSectionProps {
  options?: DashboardHookOptions
}

interface StructuredFilter {
  field: string
  operator: string
  value: string
}

export function LogsSection({ options = {} }: LogsSectionProps) {
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [levelFilter, setLevelFilter] = useState<string>('all')
  const [reqIdFilter, setReqIdFilter] = useState('')
  const [reqIdInput, setReqIdInput] = useState('')
  const [structuredFilters, setStructuredFilters] = useState<StructuredFilter[]>([])
  const [structuredField, setStructuredField] = useState('level')
  const [structuredOp, setStructuredOp] = useState('equals')
  const [structuredValue, setStructuredValue] = useState('')

  const filters: Record<string, string> = {}
  if (levelFilter !== 'all') filters.level = levelFilter
  if (reqIdFilter) filters.request_id = reqIdFilter
  structuredFilters.forEach((sf, idx) => {
    filters[`filter_field_${idx}`] = sf.field
    filters[`filter_op_${idx}`] = sf.operator
    filters[`filter_value_${idx}`] = sf.value
  })

  const { data, meta, isLoading } = useDashboardData('logs', {
    ...options,
    page,
    search,
    filters,
  })

  const logs = (data as Record<string, unknown>[]) || []

  const handleReqIdClick = useCallback((reqId: string) => {
    setReqIdFilter(reqId)
    setReqIdInput(reqId)
    setPage(1)
  }, [])

  const handleReqIdInputSubmit = useCallback(() => {
    const trimmed = reqIdInput.trim()
    setReqIdFilter(trimmed)
    setPage(1)
  }, [reqIdInput])

  const clearReqIdFilter = useCallback(() => {
    setReqIdFilter('')
    setReqIdInput('')
    setPage(1)
  }, [])

  const clearLevelFilter = useCallback(() => {
    setLevelFilter('all')
    setPage(1)
  }, [])

  const addStructuredFilter = useCallback(() => {
    const trimmed = structuredValue.trim()
    if (!trimmed) return
    setStructuredFilters((prev) => [
      ...prev,
      { field: structuredField, operator: structuredOp, value: trimmed },
    ])
    setStructuredValue('')
  }, [structuredField, structuredOp, structuredValue])

  const removeStructuredFilter = useCallback((index: number) => {
    setStructuredFilters((prev) => prev.filter((_, i) => i !== index))
  }, [])

  const hasActiveFilters =
    levelFilter !== 'all' || reqIdFilter !== '' || structuredFilters.length > 0

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Search logs..."
        summary={`${meta?.total ?? 0} logs`}
      >
        <div className="ss-dash-log-filters">
          {LOG_LEVELS.map((level) => (
            <button
              key={level}
              type="button"
              className={`ss-dash-log-filter ${levelFilter === level ? 'ss-dash-active' : ''}`}
              onClick={() => {
                setLevelFilter(level)
                setPage(1)
              }}
            >
              {level}
            </button>
          ))}
          <input
            type="text"
            className="ss-dash-filter-input ss-dash-reqid-input"
            placeholder="Filter by request ID..."
            value={reqIdInput}
            onChange={(e) => setReqIdInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleReqIdInputSubmit()}
          />
          {(reqIdInput || reqIdFilter) && (
            <button
              type="button"
              className="ss-dash-btn ss-dash-reqid-clear"
              onClick={() => {
                clearReqIdFilter()
              }}
            >
              Clear
            </button>
          )}
        </div>
      </FilterBar>

      {/* Structured search panel */}
      <div className="ss-dash-structured-search">
        <select
          className="ss-dash-filter-select"
          value={structuredField}
          onChange={(e) => setStructuredField(e.target.value)}
        >
          <option value="level">level</option>
          <option value="message">message</option>
          <option value="request_id">request_id</option>
          <option value="userId">userId</option>
          <option value="email">email</option>
          <option value="path">path</option>
        </select>
        <select
          className="ss-dash-filter-select"
          value={structuredOp}
          onChange={(e) => setStructuredOp(e.target.value)}
        >
          <option value="equals">equals</option>
          <option value="contains">contains</option>
          <option value="starts_with">starts with</option>
        </select>
        <input
          className="ss-dash-filter-input"
          placeholder="Value..."
          value={structuredValue}
          onChange={(e) => setStructuredValue(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && addStructuredFilter()}
        />
        <button type="button" className="ss-dash-btn" onClick={addStructuredFilter}>
          Add
        </button>
      </div>

      {/* Active filter chips */}
      {hasActiveFilters && (
        <div className="ss-dash-filter-chips">
          {levelFilter !== 'all' && (
            <span className="ss-dash-filter-chip">
              level: {levelFilter}
              <button
                type="button"
                className="ss-dash-filter-chip-remove"
                onClick={clearLevelFilter}
              >
                &times;
              </button>
            </span>
          )}
          {reqIdFilter && (
            <span className="ss-dash-filter-chip">
              requestId: {reqIdFilter.slice(0, 8)}...
              <button
                type="button"
                className="ss-dash-filter-chip-remove"
                onClick={clearReqIdFilter}
              >
                &times;
              </button>
            </span>
          )}
          {structuredFilters.map((sf, idx) => (
            <span key={idx} className="ss-dash-filter-chip">
              {sf.field} {sf.operator} &quot;{sf.value}&quot;
              <button
                type="button"
                className="ss-dash-filter-chip-remove"
                onClick={() => removeStructuredFilter(idx)}
              >
                &times;
              </button>
            </span>
          ))}
        </div>
      )}

      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading logs...</div>
      ) : logs.length === 0 ? (
        <div className="ss-dash-empty">
          No log entries
          {reqIdFilter
            ? ` matching request ${reqIdFilter}`
            : levelFilter !== 'all'
              ? ` for ${levelFilter}`
              : ''}
        </div>
      ) : (
        <div className="ss-dash-log-entries">
          {logs.map((log, i) => {
            const level = resolveLogLevel(log)
            const message = resolveLogMessage(log)
            const reqId = resolveLogRequestId(log)
            const ts = resolveLogTimestamp(log)

            return (
              <div key={(log.id as string) || i} className="ss-dash-log-entry">
                <span
                  className={`ss-dash-log-level ${getLogLevelCssClass(level, 'ss-dash-log-level')}`}
                >
                  {level.toUpperCase()}
                </span>
                <span className="ss-dash-log-time" title={ts ? formatTime(ts) : ''}>
                  {ts ? timeAgo(ts) : '-'}
                </span>
                {reqId ? (
                  <span
                    className="ss-dash-log-reqid"
                    title={reqId}
                    onClick={() => handleReqIdClick(reqId)}
                    role="button"
                    tabIndex={0}
                    onKeyDown={(e) => e.key === 'Enter' && handleReqIdClick(reqId)}
                  >
                    {reqId.slice(0, 8)}
                  </span>
                ) : (
                  <span className="ss-dash-log-reqid-empty">--</span>
                )}
                <span className="ss-dash-log-msg">{message}</span>
              </div>
            )
          })}
        </div>
      )}

      {meta && (
        <Pagination
          page={meta.page}
          lastPage={meta.lastPage}
          total={meta.total}
          onPageChange={setPage}
        />
      )}
    </div>
  )
}

export default LogsSection
