// src/vue/components/Dashboard/sections/RoutesSection.vue
<script setup lang="ts">
/**
 * Routes section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React RoutesSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import FilterBar from '../shared/FilterBar.vue'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

const {
  data,
  loading,
  error,
  setSearch,
} = useDashboardData(() => 'routes', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const search = ref('')

const routes = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const raw = data.value as Record<string, unknown> | Record<string, unknown>[]
  if (Array.isArray(raw)) return raw
  if (Array.isArray(raw.routes)) return raw.routes as Record<string, unknown>[]
  if (Array.isArray(raw.data)) return raw.data as Record<string, unknown>[]
  return []
})

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}
</script>

<template>
  <div>
    <FilterBar
      :model-value="search"
      placeholder="Filter routes..."
      :summary="`${routes.length} routes`"
      @update:model-value="handleSearch"
    />

    <div v-if="error" class="ss-dash-empty">Failed to load routes</div>

    <div v-else-if="loading && !data" class="ss-dash-empty">Loading routes...</div>

    <template v-else>
      <div class="ss-dash-table-wrap">
        <table v-if="routes.length > 0" class="ss-dash-table">
          <colgroup>
            <col style="width: 70px" />
            <col />
            <col style="width: 120px" />
            <col />
            <col />
          </colgroup>
          <thead>
            <tr>
              <th>Method</th>
              <th>Pattern</th>
              <th>Name</th>
              <th>Handler</th>
              <th>Middleware</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(r, i) in routes" :key="(r.pattern as string) || i">
              <td>
                <span :class="`ss-dash-method ss-dash-method-${((r.method as string) || '').toLowerCase()}`">
                  {{ r.method }}
                </span>
              </td>
              <td>
                <span
                  style="color: var(--ss-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap"
                  :title="(r.pattern as string)"
                >
                  {{ r.pattern }}
                </span>
              </td>
              <td>
                <span
                  style="color: var(--ss-muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap"
                  :title="(r.name as string) || '-'"
                >
                  {{ (r.name as string) || '-' }}
                </span>
              </td>
              <td>
                <span
                  style="color: var(--ss-sql-color); overflow: hidden; text-overflow: ellipsis; white-space: nowrap"
                  :title="(r.handler as string)"
                >
                  {{ r.handler }}
                </span>
              </td>
              <td>
                <span
                  style="color: var(--ss-dim); font-size: 10px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap"
                  :title="(r.middleware as string[])?.length ? (r.middleware as string[]).join(', ') : '-'"
                >
                  {{ (r.middleware as string[])?.length ? (r.middleware as string[]).join(', ') : '-' }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-else class="ss-dash-empty">No routes available</div>
      </div>
    </template>
  </div>
</template>

// src/react/components/Dashboard/sections/RoutesSection.tsx
import React, { useState } from 'react'

import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { MethodBadge } from '../../shared/Badge.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../shared/FilterBar.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface RoutesSectionProps {
  options?: DashboardHookOptions
}

export function RoutesSection({ options = {} }: RoutesSectionProps) {
  const [search, setSearch] = useState('')
  const { data, isLoading, error } = useDashboardData('routes', { ...options, search })
  const raw = data as Record<string, unknown> | Record<string, unknown>[] | null
  const routes: Record<string, unknown>[] = Array.isArray(raw)
    ? raw
    : raw && Array.isArray((raw as Record<string, unknown>).routes)
      ? ((raw as Record<string, unknown>).routes as Record<string, unknown>[])
      : raw && Array.isArray((raw as Record<string, unknown>).data)
        ? ((raw as Record<string, unknown>).data as Record<string, unknown>[])
        : []

  const truncStyle: React.CSSProperties = {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Filter routes..."
        summary={`${routes.length} routes`}
      />
      {error ? (
        <div className="ss-dash-empty">Failed to load routes</div>
      ) : isLoading && !data ? (
        <div className="ss-dash-empty">Loading routes...</div>
      ) : (
        <>
          <div className="ss-dash-table-wrap">
            <DataTable
              columns={[
                {
                  key: 'method',
                  label: 'Method',
                  width: '70px',
                  render: (v: string) => <MethodBadge method={v} />,
                },
                {
                  key: 'pattern',
                  label: 'Pattern',
                  render: (v: string) => (
                    <span style={{ color: 'var(--ss-text)', ...truncStyle }} title={v}>
                      {v}
                    </span>
                  ),
                },
                {
                  key: 'name',
                  label: 'Name',
                  width: '120px',
                  render: (v: string) => (
                    <span style={{ color: 'var(--ss-muted)', ...truncStyle }} title={v || '-'}>
                      {v || '-'}
                    </span>
                  ),
                },
                {
                  key: 'handler',
                  label: 'Handler',
                  render: (v: string) => (
                    <span style={{ color: 'var(--ss-sql-color)', ...truncStyle }} title={v}>
                      {v}
                    </span>
                  ),
                },
                {
                  key: 'middleware',
                  label: 'Middleware',
                  render: (v: string[]) => {
                    const text = v?.length ? v.join(', ') : '-'
                    return (
                      <span
                        style={{ color: 'var(--ss-dim)', fontSize: '10px', ...truncStyle }}
                        title={text}
                      >
                        {text}
                      </span>
                    )
                  },
                },
              ]}
              data={routes}
              keyField="pattern"
              emptyMessage="No routes available"
            />
          </div>
        </>
      )}
    </div>
  )
}

export default RoutesSection
