// src/vue/components/Dashboard/sections/TimelineSection.vue
<script setup lang="ts">
/**
 * Timeline/traces section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React TimelineSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { ApiClient, timeAgo, formatTime } from '../../../../core/index.js'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import FilterBar from '../shared/FilterBar.vue'
import PaginationControls from '../shared/PaginationControls.vue'
import WaterfallChart from '../shared/WaterfallChart.vue'

const props = withDefaults(defineProps<{
  /** When false, show a "tracing disabled" message instead of fetching. Defaults to true. */
  tracingEnabled?: boolean
}>(), {
  tracingEnabled: true,
})

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

interface TraceDetail {
  method?: string
  url?: string
  status_code?: number
  statusCode?: number
  total_duration?: number
  totalDuration?: number
  spanCount?: number
  spans?: unknown[] | string
  warnings?: string[] | string
}

const {
  data,
  loading,
  error,
  pagination,
  goToPage,
  setSearch,
} = useDashboardData(() => 'traces', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const search = ref('')
const selectedId = ref<number | null>(null)
const traceDetail = ref<TraceDetail | null>(null)
const detailLoading = ref(false)

const traces = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const d = data.value as Record<string, unknown>
  return (d.data || d.traces || data.value || []) as Record<string, unknown>[]
})

let apiClient: ApiClient | null = null
function getClient(): ApiClient {
  if (!apiClient) {
    apiClient = new ApiClient({ baseUrl, authToken })
  }
  return apiClient
}

async function selectTrace(id: number) {
  selectedId.value = id
  detailLoading.value = true
  traceDetail.value = null
  try {
    const endpoint = dashboardEndpoint || '/__stats/api'
    const result = await getClient().fetch<TraceDetail>(`${endpoint}/traces/${id}`)
    traceDetail.value = result
  } catch {
    // silently fail
  } finally {
    detailLoading.value = false
  }
}

function handleBack() {
  selectedId.value = null
  traceDetail.value = null
}

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}

function parseSpans(raw: unknown[] | string | undefined): unknown[] {
  if (!raw) return []
  if (typeof raw === 'string') {
    try { return JSON.parse(raw) } catch { return [] }
  }
  return Array.isArray(raw) ? raw : []
}

function parseWarnings(raw: string[] | string | undefined): string[] {
  if (!raw) return []
  if (typeof raw === 'string') {
    try { return JSON.parse(raw) } catch { return [] }
  }
  return Array.isArray(raw) ? raw : []
}
</script>

<template>
  <div>
    <!-- Tracing disabled message -->
    <div v-if="!props.tracingEnabled" class="ss-dash-empty">
      Tracing is not enabled. Enable tracing in your server-stats config to use the timeline.
    </div>

    <!-- Trace detail view -->
    <template v-else-if="selectedId && traceDetail">
      <div class="ss-dash-tl-detail-header">
        <button type="button" class="ss-dash-btn" @click="handleBack">
          &larr; Back
        </button>
        <span :class="`ss-dash-method ss-dash-method-${(traceDetail.method || '').toLowerCase()}`">
          {{ traceDetail.method }}
        </span>
        <span style="color: var(--ss-text)">{{ traceDetail.url }}</span>
        <span :class="`ss-dash-status ss-dash-status-${Math.floor((traceDetail.status_code || traceDetail.statusCode || 0) / 100)}xx`">
          {{ traceDetail.status_code || traceDetail.statusCode || 0 }}
        </span>
        <span class="ss-dash-tl-meta">
          {{ (traceDetail.total_duration || traceDetail.totalDuration || 0).toFixed(1) }}ms
          &middot;
          {{ traceDetail.spanCount ?? parseSpans(traceDetail.spans).length }} spans
        </span>
      </div>
      <WaterfallChart
        :spans="parseSpans(traceDetail.spans) as any"
        :total-duration="traceDetail.total_duration || traceDetail.totalDuration || 0"
        :warnings="parseWarnings(traceDetail.warnings)"
      />
    </template>

    <!-- Loading detail -->
    <template v-else-if="selectedId && detailLoading">
      <div class="ss-dash-tl-detail-header">
        <button type="button" class="ss-dash-btn" @click="handleBack">
          &larr; Back
        </button>
      </div>
      <div class="ss-dash-empty">Loading trace detail...</div>
    </template>

    <!-- List view -->
    <template v-else>
      <FilterBar
        :model-value="search"
        placeholder="Filter traces..."
        :summary="`${pagination.total ?? 0} traces`"
        @update:model-value="handleSearch"
      />

      <div v-if="error" class="ss-dash-empty">Failed to load traces</div>

      <div v-if="loading && !data" class="ss-dash-empty">Loading traces...</div>

      <template v-else>
        <div class="ss-dash-table-wrap">
          <table v-if="traces.length > 0" class="ss-dash-table">
            <colgroup>
              <col style="width: 40px" />
              <col style="width: 70px" />
              <col />
              <col style="width: 60px" />
              <col style="width: 80px" />
              <col style="width: 50px" />
              <col style="width: 80px" />
            </colgroup>
            <thead>
              <tr>
                <th>#</th>
                <th>Method</th>
                <th>URL</th>
                <th>Status</th>
                <th>Duration</th>
                <th>Spans</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="t in traces"
                :key="(t.id as number)"
                class="ss-dash-clickable"
                @click="selectTrace(t.id as number)"
              >
                <td><span style="color: var(--ss-dim)">{{ t.id }}</span></td>
                <td>
                  <span :class="`ss-dash-method ss-dash-method-${((t.method as string) || '').toLowerCase()}`">
                    {{ t.method }}
                  </span>
                </td>
                <td>
                  <span
                    style="color: var(--ss-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap"
                    :title="(t.url as string)"
                  >
                    {{ t.url }}
                  </span>
                </td>
                <td>
                  <span :class="`ss-dash-status ss-dash-status-${Math.floor(((t.statusCode as number) || (t.status_code as number) || 0) / 100)}xx`">
                    {{ (t.statusCode as number) || (t.status_code as number) || 0 }}
                  </span>
                </td>
                <td>
                  <span
                    :class="`ss-dash-duration ${((t.totalDuration as number) || (t.total_duration as number) || 0) > 500 ? 'ss-dash-very-slow' : ((t.totalDuration as number) || (t.total_duration as number) || 0) > 100 ? 'ss-dash-slow' : ''}`"
                  >
                    {{ ((t.totalDuration as number) || (t.total_duration as number) || 0).toFixed(1) }}ms
                  </span>
                </td>
                <td>
                  <span style="color: var(--ss-muted); text-align: center">
                    {{ (t.spanCount as number) || (t.span_count as number) || 0 }}
                  </span>
                </td>
                <td>
                  <span
                    class="ss-dash-event-time"
                    :title="formatTime(((t.createdAt as string) || (t.created_at as string) || (t.timestamp as string)) as string)"
                  >
                    {{ timeAgo(((t.createdAt as string) || (t.created_at as string) || (t.timestamp as string)) as string) }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
          <div v-else class="ss-dash-empty">No traces recorded</div>
        </div>
        <PaginationControls
          v-if="pagination.totalPages > 1"
          :page="pagination.page"
          :last-page="pagination.totalPages"
          :total="pagination.total"
          @page-change="goToPage"
        />
      </template>
    </template>
  </div>
</template>

// src/react/components/Dashboard/sections/TimelineSection.tsx
import React, { useState, useCallback, useEffect, useRef } from 'react'

import { ApiClient } from '../../../../core/api-client.js'
import { timeAgo, formatTime } from '../../../../core/formatters.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { MethodBadge, StatusBadge } from '../../shared/Badge.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../shared/FilterBar.js'
import { Pagination } from '../shared/Pagination.js'
import { WaterfallChart } from '../shared/WaterfallChart.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface TimelineSectionProps {
  options?: DashboardHookOptions
  /** When false, show a "tracing disabled" message instead of fetching. Defaults to true. */
  tracingEnabled?: boolean
}

interface TraceDetail {
  method?: string
  url?: string
  status_code?: number
  statusCode?: number
  total_duration?: number
  totalDuration?: number
  spanCount?: number
  spans?: Array<{
    id: string
    label: string
    startOffset: number
    duration: number
    category: string
    parentId?: string
    metadata?: Record<string, unknown>
  }> | string
  warnings?: string[] | string
}

export function TimelineSection({ options = {}, tracingEnabled = true }: TimelineSectionProps) {
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [selectedId, setSelectedId] = useState<number | null>(null)
  const [traceDetail, setTraceDetail] = useState<TraceDetail | null>(null)
  const [detailLoading, setDetailLoading] = useState(false)

  const { data, meta, isLoading, error } = useDashboardData('traces', { ...options, page, search })
  const traces = (data as Record<string, unknown>[]) || []

  const clientRef = useRef<ApiClient | null>(null)
  const getClient = useCallback(() => {
    if (!clientRef.current) {
      clientRef.current = new ApiClient({
        baseUrl: options.baseUrl || '',
        authToken: options.authToken,
      })
    }
    return clientRef.current
  }, [options.baseUrl, options.authToken])

  // Fetch individual trace detail when selectedId changes
  useEffect(() => {
    if (!selectedId) {
      setTraceDetail(null)
      return
    }

    let cancelled = false
    setDetailLoading(true)

    const endpoint = options.dashboardEndpoint || '/__stats/api'
    getClient()
      .fetch<TraceDetail>(`${endpoint}/traces/${selectedId}`)
      .then((result) => {
        if (!cancelled) {
          setTraceDetail(result)
          setDetailLoading(false)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setDetailLoading(false)
        }
      })

    return () => {
      cancelled = true
    }
  }, [selectedId, getClient, options.dashboardEndpoint])

  const handleBack = useCallback(() => setSelectedId(null), [])

  if (!tracingEnabled) {
    return (
      <div className="ss-dash-empty">
        Tracing is not enabled. Enable tracing in your server-stats config to use the timeline.
      </div>
    )
  }

  if (selectedId && traceDetail) {
    // Parse spans from string if they come as JSON strings
    let spans: TraceDetail['spans'] = traceDetail.spans
    if (typeof spans === 'string') {
      try {
        spans = JSON.parse(spans)
      } catch {
        spans = []
      }
    }
    const parsedSpans = (Array.isArray(spans) ? spans : []) as Array<{
      id: string
      label: string
      startOffset: number
      duration: number
      category: string
      parentId?: string
      metadata?: Record<string, unknown>
    }>

    // Parse warnings from string if they come as JSON strings
    let warnings: TraceDetail['warnings'] = traceDetail.warnings
    if (typeof warnings === 'string') {
      try {
        warnings = JSON.parse(warnings)
      } catch {
        warnings = []
      }
    }
    const parsedWarnings = (Array.isArray(warnings) ? warnings : []) as string[]

    const duration = traceDetail.total_duration || traceDetail.totalDuration || 0
    const spanCount = traceDetail.spanCount ?? parsedSpans.length

    return (
      <div>
        <div className="ss-dash-tl-detail-header">
          <button type="button" className="ss-dash-btn" onClick={handleBack}>
            ← Back
          </button>
          <MethodBadge method={traceDetail.method || ''} />
          <span style={{ color: 'var(--ss-text)' }}>{traceDetail.url}</span>
          <StatusBadge code={traceDetail.status_code || traceDetail.statusCode || 0} />
          <span className="ss-dash-tl-meta">
            {duration.toFixed(1)}ms &middot; {spanCount} spans
          </span>
        </div>
        <WaterfallChart
          spans={parsedSpans}
          totalDuration={duration}
          warnings={parsedWarnings}
        />
      </div>
    )
  }

  if (selectedId && detailLoading) {
    return (
      <div>
        <div className="ss-dash-tl-detail-header">
          <button type="button" className="ss-dash-btn" onClick={handleBack}>
            ← Back
          </button>
        </div>
        <div className="ss-dash-empty">Loading trace detail...</div>
      </div>
    )
  }

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Filter traces..."
        summary={`${meta?.total ?? 0} traces`}
      />

      {error && <div className="ss-dash-empty">Failed to load traces</div>}

      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading traces...</div>
      ) : (
        <>
          <div className="ss-dash-table-wrap">
            <DataTable
              columns={[
                {
                  key: 'id',
                  label: '#',
                  width: '40px',
                  render: (v: number) => <span style={{ color: 'var(--ss-dim)' }}>{v}</span>,
                },
                {
                  key: 'method',
                  label: 'Method',
                  width: '70px',
                  render: (v: string) => <MethodBadge method={v} />,
                },
                {
                  key: 'url',
                  label: 'URL',
                  render: (v: string) => (
                    <span
                      style={{
                        color: 'var(--ss-text)',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}
                      title={v}
                    >
                      {v}
                    </span>
                  ),
                },
                {
                  key: 'statusCode',
                  label: 'Status',
                  width: '60px',
                  render: (v: number) => <StatusBadge code={v} />,
                },
                {
                  key: 'totalDuration',
                  label: 'Duration',
                  width: '80px',
                  render: (v: number) => (
                    <span
                      className={`ss-dash-duration ${v > 500 ? 'ss-dash-very-slow' : v > 100 ? 'ss-dash-slow' : ''}`}
                    >
                      {v.toFixed(1)}ms
                    </span>
                  ),
                },
                {
                  key: 'spanCount',
                  label: 'Spans',
                  width: '50px',
                  render: (v: number) => (
                    <span style={{ color: 'var(--ss-muted)', textAlign: 'center' }}>{v}</span>
                  ),
                },
                {
                  key: 'createdAt',
                  label: 'Time',
                  width: '80px',
                  render: (v: string) => <span className="ss-dash-event-time" title={formatTime(v)}>{timeAgo(v)}</span>,
                },
              ]}
              data={traces}
              onRowClick={(row: Record<string, unknown>) => setSelectedId(row.id as number)}
              emptyMessage="No traces recorded"
            />
          </div>
          {meta && (
            <Pagination
              page={meta.page}
              lastPage={meta.lastPage}
              total={meta.total}
              onPageChange={setPage}
            />
          )}
        </>
      )}
    </div>
  )
}

export default TimelineSection
