// src/react/components/Dashboard/sections/EmailsSection.tsx
import React, { useState, useCallback, useEffect } from 'react'

import { timeAgo, formatTime } from '../../../../core/formatters.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../../shared/FilterBar.js'
import { Pagination } from '../shared/Pagination.js'

import type { DashboardHookOptions } from '../../../../core/types.js'

interface EmailsSectionProps {
  options?: DashboardHookOptions
}

export function EmailsSection({ options = {} }: EmailsSectionProps) {
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [previewId, setPreviewId] = useState<number | null>(null)
  const [previewHtml, setPreviewHtml] = useState<string | null>(null)

  const { data, meta, isLoading } = useDashboardData('emails', { ...options, page, search })
  const emails = (data as Record<string, unknown>[]) || []

  useEffect(() => setPage(1), [search])

  const handlePreview = useCallback(
    async (email: Record<string, unknown>) => {
      if (email.html) {
        setPreviewId(email.id as number)
        setPreviewHtml(email.html as string)
        return
      }
      // Fetch preview from API
      try {
        const { baseUrl = '', dashboardEndpoint = '/__stats/api', authToken } = options
        const url = `${baseUrl}${dashboardEndpoint}/emails/${email.id}/preview`
        const headers: Record<string, string> = { Accept: 'text/html' }
        if (authToken) headers['Authorization'] = `Bearer ${authToken}`
        const resp = await fetch(url, { headers, credentials: 'same-origin' })
        const html = await resp.text()
        setPreviewId(email.id as number)
        setPreviewHtml(html)
      } catch {
        // Silently fail
      }
    },
    [options]
  )

  if (previewId && previewHtml) {
    const email = emails.find((e) => e.id === previewId)
    return (
      <div className="ss-dash-email-preview" id="ss-dash-email-preview">
        <div className="ss-dash-email-preview-header">
          <div className="ss-dash-email-preview-meta" id="ss-dash-email-preview-meta">
            {email && (
              <>
                <strong>Subject:</strong> {email.subject as string}
                &nbsp;&nbsp;|&nbsp;&nbsp;<strong>From:</strong>{' '}
                {(email.from_addr || email.from) as string}
                &nbsp;&nbsp;|&nbsp;&nbsp;<strong>To:</strong>{' '}
                {(email.to_addr || email.to) as string}
                {(email.cc || email.cc_addr) && (
                  <>
                    &nbsp;&nbsp;|&nbsp;&nbsp;<strong>CC:</strong>{' '}
                    {(email.cc || email.cc_addr) as string}
                  </>
                )}
                &nbsp;&nbsp;|&nbsp;&nbsp;<strong>Status:</strong>{' '}
                <span className={`ss-dash-badge ss-dash-email-status-${email.status as string}`}>
                  {email.status as string}
                </span>
                {(email.mailer as string) && (
                  <>
                    &nbsp;&nbsp;|&nbsp;&nbsp;<strong>Mailer:</strong> {email.mailer as string}
                  </>
                )}
              </>
            )}
          </div>
          <button
            type="button"
            className="ss-dash-btn"
            id="ss-dash-email-preview-close"
            onClick={() => {
              setPreviewId(null)
              setPreviewHtml(null)
            }}
          >
            Close
          </button>
        </div>
        <iframe
          className="ss-dash-email-iframe"
          id="ss-dash-email-iframe"
          srcDoc={previewHtml}
          title="Email preview"
          sandbox=""
        />
      </div>
    )
  }

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Filter emails..."
        summary={`${meta?.total ?? 0} emails`}
      />
      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading emails...</div>
      ) : (
        <>
          <div className="ss-dash-table-wrap">
            <DataTable
              columns={[
                {
                  key: 'id',
                  label: '#',
                  width: '40px',
                  render: (v: unknown) => (
                    <span style={{ color: 'var(--ss-dim)' }}>{v as string}</span>
                  ),
                },
                {
                  key: 'from',
                  label: 'From',
                  width: '150px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const from = (row.from_addr || row.from || '') as string
                    return (
                      <span
                        title={from}
                        style={{
                          color: 'var(--ss-text-secondary)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          display: 'block',
                        }}
                      >
                        {from}
                      </span>
                    )
                  },
                },
                {
                  key: 'to',
                  label: 'To',
                  width: '150px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const to = (row.to_addr || row.to || '') as string
                    return (
                      <span
                        title={to}
                        style={{
                          color: 'var(--ss-text-secondary)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          display: 'block',
                        }}
                      >
                        {to}
                      </span>
                    )
                  },
                },
                {
                  key: 'subject',
                  label: 'Subject',
                  render: (v: unknown) => {
                    const subject = (v || '') as string
                    return (
                      <span
                        title={subject}
                        style={{
                          color: 'var(--ss-sql-color)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          display: 'block',
                        }}
                      >
                        {subject}
                      </span>
                    )
                  },
                },
                {
                  key: 'status',
                  label: 'Status',
                  width: '80px',
                  render: (v: unknown) => {
                    const status = (v || '') as string
                    return (
                      <span className={`ss-dash-badge ss-dash-email-status-${status}`}>
                        {status}
                      </span>
                    )
                  },
                },
                {
                  key: 'attachmentCount',
                  label: 'ATT',
                  width: '40px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const count = (row.attachment_count || row.attachmentCount || 0) as number
                    return count > 0 ? (
                      <span
                        style={{ color: 'var(--ss-dim)', textAlign: 'center', display: 'block' }}
                      >
                        {count}
                      </span>
                    ) : (
                      <span
                        style={{ color: 'var(--ss-dim)', textAlign: 'center', display: 'block' }}
                      >
                        -
                      </span>
                    )
                  },
                },
                {
                  key: 'mailer',
                  label: 'Mailer',
                  width: '70px',
                  render: (v: unknown) => {
                    const mailer = (v || '') as string
                    return (
                      <span
                        title={mailer}
                        style={{
                          color: 'var(--ss-muted)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          display: 'block',
                        }}
                      >
                        {mailer}
                      </span>
                    )
                  },
                },
                {
                  key: 'createdAt',
                  label: 'Time',
                  width: '80px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const ts = (row.createdAt || row.created_at || row.timestamp) as string
                    return (
                      <span
                        className="ss-dash-event-time"
                        style={{ whiteSpace: 'nowrap' }}
                        title={formatTime(ts)}
                      >
                        {timeAgo(ts)}
                      </span>
                    )
                  },
                },
              ]}
              data={emails}
              onRowClick={handlePreview}
              rowClassName="ss-dash-email-row"
              emptyMessage="No emails captured yet"
            />
          </div>
          {meta && (
            <Pagination
              page={meta.page}
              lastPage={meta.lastPage}
              total={meta.total}
              onPageChange={setPage}
            />
          )}
        </>
      )}
    </div>
  )
}

export default EmailsSection

// src/vue/components/Dashboard/sections/EmailsSection.vue
<script setup lang="ts">
/**
 * Emails section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data.
 * CSS classes match the React EmailsSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { timeAgo, formatTime } from '../../../../core/index.js'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import FilterBar from '../shared/FilterBar.vue'
import PaginationControls from '../shared/PaginationControls.vue'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

const {
  data,
  loading,
  pagination,
  goToPage,
  setSearch,
  fetchEmailPreview,
} = useDashboardData(() => 'emails', {
  baseUrl,
  dashboardEndpoint,
  authToken,
  refreshKey,
})

const search = ref('')
const previewId = ref<number | null>(null)
const previewHtml = ref<string | null>(null)

const emails = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const d = data.value as Record<string, unknown>
  return (d.data || d.emails || data.value || []) as Record<string, unknown>[]
})

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}

async function handlePreview(email: Record<string, unknown>) {
  if (email.html) {
    previewId.value = email.id as number
    previewHtml.value = email.html as string
    return
  }
  const html = await fetchEmailPreview(email.id as number)
  previewId.value = email.id as number
  previewHtml.value = html
}

function closePreview() {
  previewId.value = null
  previewHtml.value = null
}
</script>

<template>
  <div>
    <!-- Email preview -->
    <template v-if="previewId && previewHtml">
      <div class="ss-dash-email-preview" id="ss-dash-email-preview">
        <div class="ss-dash-email-preview-header">
          <div class="ss-dash-email-preview-meta" id="ss-dash-email-preview-meta">
            <template v-if="emails.find(e => e.id === previewId)">
              <strong>Subject:</strong> {{ emails.find(e => e.id === previewId)?.subject }}
              &nbsp;&nbsp;|&nbsp;&nbsp;<strong>From:</strong>
              {{ emails.find(e => e.id === previewId)?.from_addr || emails.find(e => e.id === previewId)?.from }}
              &nbsp;&nbsp;|&nbsp;&nbsp;<strong>To:</strong>
              {{ emails.find(e => e.id === previewId)?.to_addr || emails.find(e => e.id === previewId)?.to }}
              <template v-if="emails.find(e => e.id === previewId)?.cc || emails.find(e => e.id === previewId)?.cc_addr">
                &nbsp;&nbsp;|&nbsp;&nbsp;<strong>CC:</strong>
                {{ emails.find(e => e.id === previewId)?.cc || emails.find(e => e.id === previewId)?.cc_addr }}
              </template>
              &nbsp;&nbsp;|&nbsp;&nbsp;<strong>Status:</strong>
              <span :class="`ss-dash-badge ss-dash-email-status-${emails.find(e => e.id === previewId)?.status}`">
                {{ emails.find(e => e.id === previewId)?.status }}
              </span>
              <template v-if="emails.find(e => e.id === previewId)?.mailer">
                &nbsp;&nbsp;|&nbsp;&nbsp;<strong>Mailer:</strong>
                {{ emails.find(e => e.id === previewId)?.mailer }}
              </template>
            </template>
          </div>
          <button
            type="button"
            class="ss-dash-btn"
            id="ss-dash-email-preview-close"
            @click="closePreview"
          >
            Close
          </button>
        </div>
        <iframe
          class="ss-dash-email-iframe"
          id="ss-dash-email-iframe"
          :srcdoc="previewHtml"
          title="Email preview"
          sandbox=""
        />
      </div>
    </template>

    <!-- Email list -->
    <template v-else>
      <FilterBar
        :model-value="search"
        placeholder="Filter emails..."
        :summary="`${pagination.total ?? 0} emails`"
        @update:model-value="handleSearch"
      />

      <div v-if="loading && !data" class="ss-dash-empty">Loading emails...</div>

      <template v-else>
        <div class="ss-dash-table-wrap">
          <table v-if="emails.length > 0" class="ss-dash-table">
            <colgroup>
              <col style="width: 40px" />
              <col style="width: 150px" />
              <col style="width: 150px" />
              <col />
              <col style="width: 80px" />
              <col style="width: 40px" />
              <col style="width: 70px" />
              <col style="width: 80px" />
            </colgroup>
            <thead>
              <tr>
                <th>#</th>
                <th>From</th>
                <th>To</th>
                <th>Subject</th>
                <th>Status</th>
                <th>ATT</th>
                <th>Mailer</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="e in emails"
                :key="(e.id as number)"
                class="ss-dash-clickable ss-dash-email-row"
                @click="handlePreview(e)"
              >
                <td><span style="color: var(--ss-dim)">{{ e.id }}</span></td>
                <td>
                  <span
                    :title="((e.from_addr as string) || (e.from as string) || '')"
                    style="color: var(--ss-text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                  >
                    {{ (e.from_addr as string) || (e.from as string) || '' }}
                  </span>
                </td>
                <td>
                  <span
                    :title="((e.to_addr as string) || (e.to as string) || '')"
                    style="color: var(--ss-text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                  >
                    {{ (e.to_addr as string) || (e.to as string) || '' }}
                  </span>
                </td>
                <td>
                  <span
                    :title="((e.subject as string) || '')"
                    style="color: var(--ss-sql-color); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                  >
                    {{ (e.subject as string) || '' }}
                  </span>
                </td>
                <td>
                  <span :class="`ss-dash-badge ss-dash-email-status-${(e.status as string) || ''}`">
                    {{ e.status }}
                  </span>
                </td>
                <td>
                  <span
                    v-if="((e.attachment_count as number) || (e.attachmentCount as number) || 0) > 0"
                    style="color: var(--ss-dim); text-align: center; display: block"
                  >
                    {{ (e.attachment_count as number) || (e.attachmentCount as number) || 0 }}
                  </span>
                  <span v-else style="color: var(--ss-dim); text-align: center; display: block">-</span>
                </td>
                <td>
                  <span
                    :title="((e.mailer as string) || '')"
                    style="color: var(--ss-muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block"
                  >
                    {{ (e.mailer as string) || '' }}
                  </span>
                </td>
                <td>
                  <span
                    class="ss-dash-event-time"
                    style="white-space: nowrap"
                    :title="formatTime(((e.createdAt as string) || (e.created_at as string) || (e.timestamp as string)) as string)"
                  >
                    {{ timeAgo(((e.createdAt as string) || (e.created_at as string) || (e.timestamp as string)) as string) }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
          <div v-else class="ss-dash-empty">No emails captured yet</div>
        </div>
        <PaginationControls
          v-if="pagination.totalPages > 1"
          :page="pagination.page"
          :last-page="pagination.totalPages"
          :total="pagination.total"
          @page-change="goToPage"
        />
      </template>
    </template>
  </div>
</template>
