// src/react/components/Dashboard/sections/OverviewSection.tsx
import React, { useState } from 'react'

import { formatDuration } from '../../../../core/formatters.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { Sparkline } from '../../StatsBar/Sparkline.js'
import { TimeRangeSelector } from '../shared/TimeRangeSelector.js'

import type {
  OverviewMetrics,
  ChartDataPoint,
  DashboardHookOptions,
  TimeRange,
} from '../../../../core/types.js'

interface OverviewSectionProps {
  options?: DashboardHookOptions
}

export function OverviewSection({ options = {} }: OverviewSectionProps) {
  const [timeRange, setTimeRange] = useState<TimeRange>('1h')
  const { data: overview, isLoading } = useDashboardData<OverviewMetrics>('overview', options)
  const { data: chartData } = useDashboardData<ChartDataPoint[]>('overview/chart', {
    ...options,
    timeRange,
  })

  if (isLoading && !overview) {
    return <div className="ss-dash-empty">Loading overview...</div>
  }

  const metrics = overview || {
    avgResponseTime: 0,
    p95ResponseTime: 0,
    requestsPerMinute: 0,
    errorRate: 0,
    slowestEndpoints: [],
    queryStats: { total: 0, avgDuration: 0, perRequest: 0 },
    recentErrors: [],
  }

  // Extract sparkline data from chart points
  const chartPoints = chartData || []
  const avgResponseTimes = chartPoints.map((p) => p.avgDuration ?? 0)
  const p95ResponseTimes = chartPoints.map((p) => p.p95Duration ?? 0)
  const requestCounts = chartPoints.map((p) => p.requestCount ?? 0)
  const errorCounts = chartPoints.map((p) => p.errorCount ?? 0)

  return (
    <div className="ss-dash-overview">
      {/* Top metric cards */}
      <div className="ss-dash-metric-cards">
        <div className="ss-dash-metric-card">
          <div className="ss-dash-metric-label">Avg Response Time</div>
          <div className="ss-dash-metric-value">{formatDuration(metrics.avgResponseTime)}</div>
          <Sparkline data={avgResponseTimes} color="#34d399" width={160} height={40} />
        </div>
        <div className="ss-dash-metric-card">
          <div className="ss-dash-metric-label">P95 Response Time</div>
          <div className="ss-dash-metric-value">{formatDuration(metrics.p95ResponseTime)}</div>
          <Sparkline data={p95ResponseTimes} color="#60a5fa" width={160} height={40} />
        </div>
        <div className="ss-dash-metric-card">
          <div className="ss-dash-metric-label">Requests/min</div>
          <div className="ss-dash-metric-value">{metrics.requestsPerMinute.toFixed(1)}</div>
          <Sparkline data={requestCounts} color="#34d399" width={160} height={40} />
        </div>
        <div className="ss-dash-metric-card">
          <div className="ss-dash-metric-label">Error Rate</div>
          <div
            className={`ss-dash-metric-value ${metrics.errorRate > 5 ? 'ss-dash-text-red' : metrics.errorRate > 1 ? 'ss-dash-text-amber' : ''}`}
          >
            {metrics.errorRate.toFixed(1)}%
          </div>
          <Sparkline data={errorCounts} color="#f87171" width={160} height={40} />
        </div>
      </div>

      {/* Request volume chart */}
      <div className="ss-dash-chart-section">
        <div className="ss-dash-section-header">
          <h3>Request Volume</h3>
          <TimeRangeSelector value={timeRange} onChange={setTimeRange} />
        </div>
        <div className="ss-dash-bar-chart">
          {chartPoints.length === 0 ? (
            <div className="ss-dash-empty" style={{ minHeight: '120px' }}>
              No data for this range
            </div>
          ) : (
            <svg
              width="100%"
              height="160"
              viewBox={`0 0 ${chartPoints.length * 12} 160`}
              preserveAspectRatio="none"
            >
              {(() => {
                const maxCount = Math.max(...chartPoints.map((p) => p.requestCount ?? 0), 1)
                return chartPoints.map((point, i) => {
                  const reqCount = point.requestCount ?? 0
                  const errCount = point.errorCount ?? 0
                  const barHeight = (reqCount / maxCount) * 140
                  const errorHeight = (errCount / maxCount) * 140
                  return (
                    <g key={i}>
                      <rect
                        x={i * 12 + 1}
                        y={150 - barHeight}
                        width="10"
                        height={barHeight}
                        rx="1"
                        fill="var(--ss-accent, #34d399)"
                        opacity="0.6"
                      >
                        <title>{`${point.bucket}: ${reqCount} requests`}</title>
                      </rect>
                      {errCount > 0 && (
                        <rect
                          x={i * 12 + 1}
                          y={150 - errorHeight}
                          width="10"
                          height={errorHeight}
                          rx="1"
                          fill="var(--ss-red-fg, #f87171)"
                          opacity="0.8"
                        />
                      )}
                    </g>
                  )
                })
              })()}
            </svg>
          )}
        </div>
      </div>

      {/* Bottom row */}
      <div className="ss-dash-overview-bottom">
        {/* Slowest Endpoints */}
        <div className="ss-dash-card">
          <h4>Slowest Endpoints</h4>
          <div className="ss-dash-card-content">
            {metrics.slowestEndpoints.length === 0 ? (
              <span className="ss-dash-muted">No data</span>
            ) : (
              <table className="ss-dash-mini-table">
                <tbody>
                  {metrics.slowestEndpoints.map((ep, i) => (
                    <tr key={i}>
                      <td style={{ color: 'var(--ss-text)' }}>{ep.url}</td>
                      <td style={{ textAlign: 'right' }}>{formatDuration(ep.avgDuration)}</td>
                      <td style={{ textAlign: 'right', color: 'var(--ss-dim)' }}>{ep.count}x</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {/* Query Stats */}
        <div className="ss-dash-card">
          <h4>Query Stats</h4>
          <div className="ss-dash-card-content">
            <div className="ss-dash-stat-row">
              <span>Total Queries</span>
              <span>{metrics.queryStats.total}</span>
            </div>
            <div className="ss-dash-stat-row">
              <span>Avg Duration</span>
              <span>{formatDuration(metrics.queryStats.avgDuration)}</span>
            </div>
            <div className="ss-dash-stat-row">
              <span>Per Request</span>
              <span>{metrics.queryStats.perRequest.toFixed(1)}</span>
            </div>
          </div>
        </div>

        {/* Recent Errors */}
        <div className="ss-dash-card">
          <h4>Recent Errors</h4>
          <div className="ss-dash-card-content">
            {metrics.recentErrors.length === 0 ? (
              <span className="ss-dash-muted">No errors</span>
            ) : (
              metrics.recentErrors.map((err, i) => (
                <div key={i} className="ss-dash-error-entry">
                  <span className="ss-dash-error-level">{err.level}</span>
                  <span className="ss-dash-error-msg">{err.message}</span>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

export default OverviewSection

// src/vue/components/Dashboard/sections/OverviewSection.vue
<script setup lang="ts">
/**
 * Overview section with performance cards and charts.
 */
import { ref, computed, onMounted } from 'vue'
import { formatDuration, formatStatNum, timeAgo } from '../../../../core/index.js'
import type { OverviewData, ChartDataPoint, TimeRange } from '../../../../core/index.js'
import Sparkline from '../../StatsBar/Sparkline.vue'
import TimeRangeSelector from '../shared/TimeRangeSelector.vue'

const props = defineProps<{
  data: any
  timeRange: TimeRange
  onFetchChart?: (range: TimeRange) => Promise<any>
}>()

const emit = defineEmits<{
  changeTimeRange: [range: TimeRange]
  navigateTo: [section: string]
}>()

const chartData = ref<ChartDataPoint[]>([])

const overview = computed<OverviewData | null>(() => props.data)

const metricCards = computed(() => {
  if (!overview.value) return []
  return [
    {
      label: 'Avg Response Time',
      value: formatStatNum(overview.value.avgResponseTime, 'ms'),
      series: overview.value.avgResponseTimeSeries || [],
      color: overview.value.avgResponseTime > 500 ? '#f87171' : overview.value.avgResponseTime > 200 ? '#fbbf24' : '#34d399',
    },
    {
      label: 'P95 Response Time',
      value: formatStatNum(overview.value.p95ResponseTime, 'ms'),
      series: overview.value.p95ResponseTimeSeries || [],
      color: overview.value.p95ResponseTime > 1000 ? '#f87171' : overview.value.p95ResponseTime > 500 ? '#fbbf24' : '#34d399',
    },
    {
      label: 'Requests/min',
      value: overview.value.requestsPerMinute.toFixed(1),
      series: overview.value.requestsPerMinuteSeries || [],
      color: '#34d399',
    },
    {
      label: 'Error Rate',
      value: `${overview.value.errorRate.toFixed(1)}%`,
      series: overview.value.errorRateSeries || [],
      color: overview.value.errorRate > 5 ? '#f87171' : overview.value.errorRate > 1 ? '#fbbf24' : '#34d399',
    },
  ]
})

async function handleRangeChange(range: TimeRange) {
  emit('changeTimeRange', range)
  if (props.onFetchChart) {
    const result = await props.onFetchChart(range)
    if (result?.data) chartData.value = result.data
  }
}

// SVG chart rendering
const chartMaxCount = computed(() => {
  if (chartData.value.length === 0) return 1
  return Math.max(...chartData.value.map((d) => d.total), 1)
})

function barHeight(count: number): number {
  return (count / chartMaxCount.value) * 100
}

onMounted(async () => {
  if (props.onFetchChart) {
    const result = await props.onFetchChart(props.timeRange)
    if (result?.data) chartData.value = result.data
  }
})
</script>

<template>
  <div class="ss-dash-overview">
    <!-- Metric cards -->
    <div v-if="overview" class="ss-dash-metric-cards">
      <div
        v-for="card in metricCards"
        :key="card.label"
        class="ss-dash-metric-card"
      >
        <div class="ss-dash-metric-card-header">
          <span class="ss-dash-metric-card-label">{{ card.label }}</span>
          <span class="ss-dash-metric-card-value" :style="{ color: card.color }">
            {{ card.value }}
          </span>
        </div>
        <div class="ss-dash-metric-card-chart">
          <Sparkline
            :data="card.series"
            :color="card.color"
            :width="200"
            :height="40"
          />
        </div>
      </div>
    </div>

    <!-- Request volume chart -->
    <div class="ss-dash-chart-section">
      <div class="ss-dash-chart-header">
        <h3 class="ss-dash-section-title">Request Volume</h3>
        <TimeRangeSelector
          :model-value="timeRange"
          @update:model-value="handleRangeChange"
        />
      </div>

      <div v-if="chartData.length > 0" class="ss-dash-bar-chart">
        <svg
          :width="Math.max(chartData.length * 12, 400)"
          height="120"
          style="display: block; width: 100%;"
          preserveAspectRatio="none"
          :viewBox="`0 0 ${Math.max(chartData.length * 12, 400)} 120`"
        >
          <g v-for="(point, i) in chartData" :key="i">
            <!-- Stacked bar: 2xx, 3xx, 4xx, 5xx -->
            <rect
              :x="i * 12 + 1"
              :y="120 - barHeight(point.total)"
              :width="10"
              :height="barHeight(point.count2xx)"
              fill="var(--ss-green-fg, #34d399)"
              opacity="0.8"
            >
              <title>{{ point.bucket }}: {{ point.count2xx }} 2xx</title>
            </rect>
            <rect
              :x="i * 12 + 1"
              :y="120 - barHeight(point.total) + barHeight(point.count2xx)"
              :width="10"
              :height="barHeight(point.count3xx)"
              fill="var(--ss-blue-fg, #60a5fa)"
              opacity="0.8"
            >
              <title>{{ point.count3xx }} 3xx</title>
            </rect>
            <rect
              :x="i * 12 + 1"
              :y="120 - barHeight(point.total) + barHeight(point.count2xx) + barHeight(point.count3xx)"
              :width="10"
              :height="barHeight(point.count4xx)"
              fill="var(--ss-amber-fg, #fbbf24)"
              opacity="0.8"
            >
              <title>{{ point.count4xx }} 4xx</title>
            </rect>
            <rect
              :x="i * 12 + 1"
              :y="120 - barHeight(point.count5xx)"
              :width="10"
              :height="barHeight(point.count5xx)"
              fill="var(--ss-red-fg, #f87171)"
              opacity="0.8"
            >
              <title>{{ point.count5xx }} 5xx</title>
            </rect>
          </g>
        </svg>
      </div>
      <div v-else class="ss-dash-empty">No chart data available</div>
    </div>

    <!-- Bottom row: secondary cards -->
    <div v-if="overview" class="ss-dash-secondary-cards">
      <!-- Slowest Endpoints -->
      <div class="ss-dash-secondary-card">
        <h4 class="ss-dash-secondary-title">Slowest Endpoints</h4>
        <div v-if="overview.slowestEndpoints && overview.slowestEndpoints.length > 0">
          <div
            v-for="ep in overview.slowestEndpoints.slice(0, 5)"
            :key="ep.url"
            class="ss-dash-endpoint-row"
          >
            <span class="ss-dash-endpoint-url">{{ ep.url }}</span>
            <span class="ss-dash-endpoint-stats">
              {{ formatDuration(ep.avgDuration) }} avg &middot; {{ ep.count }}x
            </span>
          </div>
        </div>
        <div v-else class="ss-dash-empty-small">No data yet</div>
      </div>

      <!-- Query Stats -->
      <div class="ss-dash-secondary-card">
        <h4 class="ss-dash-secondary-title">Query Stats</h4>
        <div class="ss-dash-stat-row">
          <span>Total queries:</span>
          <strong>{{ overview.queryStats?.total || 0 }}</strong>
        </div>
        <div class="ss-dash-stat-row">
          <span>Avg duration:</span>
          <strong>{{ formatDuration(overview.queryStats?.avgDuration || 0) }}</strong>
        </div>
        <div class="ss-dash-stat-row">
          <span>Queries/request:</span>
          <strong>{{ (overview.queryStats?.perRequest || 0).toFixed(1) }}</strong>
        </div>
      </div>

      <!-- Recent Errors -->
      <div class="ss-dash-secondary-card">
        <h4 class="ss-dash-secondary-title">
          Recent Errors
          <button
            class="ss-dash-link-btn"
            @click="emit('navigateTo', 'logs')"
          >
            View all
          </button>
        </h4>
        <div v-if="overview.recentErrors && overview.recentErrors.length > 0">
          <div
            v-for="err in overview.recentErrors.slice(0, 5)"
            :key="err.id"
            class="ss-dash-error-row"
          >
            <span class="ss-dash-error-level">{{ err.level }}</span>
            <span class="ss-dash-error-msg">{{ err.message }}</span>
            <span class="ss-dash-error-time">{{ timeAgo(err.timestamp) }}</span>
          </div>
        </div>
        <div v-else class="ss-dash-empty-small">No errors</div>
      </div>
    </div>

    <div v-if="!overview" class="ss-dash-empty">Loading overview...</div>
  </div>
</template>
