// src/react/components/Dashboard/sections/RequestsSection.tsx
import React, { useState, useCallback, useEffect } from 'react'

import { timeAgo, formatTime, durationSeverity } from '../../../../core/formatters.js'
import { normalizeTraceFields } from '../../../../core/trace-utils.js'
import { useApiClient } from '../../../hooks/useApiClient.js'
import { useDashboardData } from '../../../hooks/useDashboardData.js'
import { MethodBadge, StatusBadge } from '../../shared/Badge.js'
import { DataTable } from '../shared/DataTable.js'
import { FilterBar } from '../shared/FilterBar.js'
import { Pagination } from '../shared/Pagination.js'
import { WaterfallChart } from '../shared/WaterfallChart.js'

import type { DashboardHookOptions } from '../../../../core/types.js'
import type { TraceDetail } from '../../../../core/trace-utils.js'

interface RequestsSectionProps {
  options?: DashboardHookOptions
}

export function RequestsSection({ options = {} }: RequestsSectionProps) {
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [sort, setSort] = useState('createdAt')
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc')
  const [selectedTrace, setSelectedTrace] = useState<TraceDetail | null>(null)
  const [detailLoading, setDetailLoading] = useState(false)

  useEffect(() => setPage(1), [search])

  const { data, meta, isLoading, error } = useDashboardData('requests', {
    ...options,
    page,
    search,
    sort,
    sortDir,
  })

  const getClient = useApiClient(options.baseUrl || '', options.authToken)

  const handleRowClick = useCallback(
    (row: Record<string, unknown>) => {
      const id = row.id as number
      setDetailLoading(true)

      const endpoint = options.dashboardEndpoint || '/__stats/api'
      getClient()
        .fetch<TraceDetail>(`${endpoint}/requests/${id}`)
        .then((result) => {
          setSelectedTrace(result)
          setDetailLoading(false)
        })
        .catch(() => {
          setDetailLoading(false)
        })
    },
    [getClient, options.dashboardEndpoint]
  )

  const handleSort = useCallback(
    (key: string) => {
      if (sort === key) {
        setSortDir((prev) => (prev === 'asc' ? 'desc' : 'asc'))
      } else {
        setSort(key)
        setSortDir('desc')
      }
    },
    [sort]
  )

  const requests = (data as Record<string, unknown>[]) || []

  if (selectedTrace) {
    const normalized = normalizeTraceFields(selectedTrace as unknown as Record<string, unknown>)

    return (
      <div>
        <div className="ss-dash-tl-detail-header">
          <button type="button" className="ss-dash-btn" onClick={() => setSelectedTrace(null)}>
            ← Back to Requests
          </button>
          <MethodBadge method={normalized.method} />
          <span style={{ color: 'var(--ss-text)' }}>{normalized.url}</span>
          <StatusBadge code={normalized.statusCode} />
          <span className="ss-dash-tl-meta">
            {normalized.totalDuration.toFixed(1)}ms &middot; {normalized.spanCount} spans
          </span>
        </div>
        <WaterfallChart
          spans={normalized.spans}
          totalDuration={normalized.totalDuration}
          warnings={normalized.warnings}
        />
      </div>
    )
  }

  if (detailLoading) {
    return (
      <div>
        <div className="ss-dash-tl-detail-header">
          <button type="button" className="ss-dash-btn" onClick={() => setDetailLoading(false)}>
            ← Back to Requests
          </button>
        </div>
        <div className="ss-dash-empty">Loading request detail...</div>
      </div>
    )
  }

  return (
    <div>
      <FilterBar
        search={search}
        onSearchChange={setSearch}
        placeholder="Filter requests..."
        summary={`${meta?.total ?? 0} requests`}
      />

      {error && <div className="ss-dash-empty">Failed to load requests</div>}

      {isLoading && !data ? (
        <div className="ss-dash-empty">Loading requests...</div>
      ) : (
        <>
          <div className="ss-dash-table-wrap">
            <DataTable
              columns={[
                {
                  key: 'id',
                  label: '#',
                  width: '40px',
                  render: (v: unknown) => <span style={{ color: 'var(--ss-dim)' }}>{v as number}</span>,
                },
                {
                  key: 'method',
                  label: 'Method',
                  width: '70px',
                  sortable: true,
                  render: (v: unknown) => <MethodBadge method={v as string} />,
                },
                {
                  key: 'url',
                  label: 'URL',
                  sortable: true,
                  render: (v: unknown) => (
                    <span
                      style={{
                        color: 'var(--ss-text)',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}
                      title={v as string}
                    >
                      {v as string}
                    </span>
                  ),
                },
                {
                  key: 'statusCode',
                  label: 'Status',
                  width: '60px',
                  sortable: true,
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const code = (row as Record<string, unknown>).status_code || (row as Record<string, unknown>).statusCode || row.statusCode
                    return <StatusBadge code={code as number} />
                  },
                },
                {
                  key: 'duration',
                  label: 'Duration',
                  width: '80px',
                  sortable: true,
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const dur = ((row as Record<string, unknown>).total_duration || (row as Record<string, unknown>).totalDuration || (row as Record<string, unknown>).duration || 0) as number
                    return (
                      <span
                        className={`ss-dash-duration ${durationSeverity(dur) === 'very-slow' ? 'ss-dash-very-slow' : durationSeverity(dur) === 'slow' ? 'ss-dash-slow' : ''}`}
                      >
                        {dur.toFixed(1)}ms
                      </span>
                    )
                  },
                },
                {
                  key: 'spanCount',
                  label: 'Spans',
                  width: '50px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const count = ((row as Record<string, unknown>).span_count || (row as Record<string, unknown>).spanCount || 0) as number
                    return (
                      <span style={{ color: 'var(--ss-muted)', textAlign: 'center' }}>{count}</span>
                    )
                  },
                },
                {
                  key: 'warningCount',
                  label: '\u26A0',
                  width: '40px',
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const count = ((row as Record<string, unknown>).warning_count || (row as Record<string, unknown>).warningCount || 0) as number
                    return count > 0 ? (
                      <span style={{ color: 'var(--ss-amber-fg)', textAlign: 'center', display: 'block' }}>{count}</span>
                    ) : (
                      <span style={{ color: 'var(--ss-dim)', textAlign: 'center', display: 'block' }}>-</span>
                    )
                  },
                },
                {
                  key: 'createdAt',
                  label: 'Time',
                  width: '80px',
                  sortable: true,
                  render: (_v: unknown, row: Record<string, unknown>) => {
                    const val = ((row as Record<string, unknown>).createdAt || (row as Record<string, unknown>).created_at || (row as Record<string, unknown>).timestamp || '') as string
                    return <span className="ss-dash-event-time" title={formatTime(val)}>{timeAgo(val)}</span>
                  },
                },
              ]}
              data={requests}
              sort={sort}
              sortDir={sortDir}
              onSort={handleSort}
              onRowClick={handleRowClick}
              emptyMessage="No requests recorded yet"
            />
          </div>
          {meta && (
            <Pagination
              page={meta.page}
              lastPage={meta.lastPage}
              total={meta.total}
              onPageChange={setPage}
            />
          )}
        </>
      )}
    </div>
  )
}

export default RequestsSection

// src/vue/components/Dashboard/sections/RequestsSection.vue
<script setup lang="ts">
/**
 * Request history section for the dashboard.
 *
 * Self-contained: injects dependencies and fetches its own data
 * via useDashboardData. CSS classes match the React RequestsSection.
 */
import { ref, computed, inject, type Ref } from 'vue'
import { timeAgo, formatTime, durationSeverity } from '../../../../core/index.js'
import { useApiClient } from '../../../composables/useApiClient.js'
import { normalizeTraceFields } from '../../../../core/trace-utils.js'
import { useDashboardData } from '../../../composables/useDashboardData.js'
import { useResizableTable } from '../../../composables/useResizableTable.js'
import FilterBar from '../shared/FilterBar.vue'
import PaginationControls from '../shared/PaginationControls.vue'
import WaterfallChart from '../shared/WaterfallChart.vue'

import type { NormalizedTrace, TraceDetail } from '../../../../core/trace-utils.js'

const refreshKey = inject<Ref<number>>('ss-refresh-key', ref(0))
const dashboardEndpoint = inject<string>('ss-dashboard-endpoint', '/__stats/api')
const authToken = inject<string | undefined>('ss-auth-token', undefined)
const baseUrl = inject<string>('ss-base-url', '')

const { data, loading, error, pagination, sort, goToPage, setSearch, setSort } = useDashboardData(
  () => 'requests',
  {
    baseUrl,
    dashboardEndpoint,
    authToken,
    refreshKey,
  }
)

const search = ref('')
const selectedTrace = ref<Record<string, unknown> | null>(null)
const detailLoading = ref(false)

const traceDetail = ref<NormalizedTrace | null>(null)

const requests = computed<Record<string, unknown>[]>(() => {
  if (!data.value) return []
  const d = data.value as Record<string, unknown>
  return (d.data || d.requests || data.value || []) as Record<string, unknown>[]
})

const getClient = useApiClient(baseUrl, authToken)

async function handleRowClick(row: Record<string, unknown>) {
  const id = row.id as number
  detailLoading.value = true
  try {
    const endpoint = dashboardEndpoint || '/__stats/api'
    const result = await getClient().fetch<TraceDetail>(`${endpoint}/requests/${id}`)
    traceDetail.value = normalizeTraceFields(result as unknown as Record<string, unknown>)
    selectedTrace.value = row
  } catch {
    // silently fail
  } finally {
    detailLoading.value = false
  }
}

function handleBack() {
  selectedTrace.value = null
  traceDetail.value = null
}

function handleSearch(term: string) {
  search.value = term
  setSearch(term)
}

function handleSort(key: string) {
  setSort(key)
}

function dashDurationClass(ms: number): string {
  const sev = durationSeverity(ms)
  if (sev === 'very-slow') return 'ss-dash-very-slow'
  if (sev === 'slow') return 'ss-dash-slow'
  return ''
}

const { tableRef } = useResizableTable(() => requests.value)
</script>

<template>
  <div>
    <!-- Trace detail view -->
    <template v-if="traceDetail && selectedTrace">
      <div class="ss-dash-tl-detail-header">
        <button type="button" class="ss-dash-btn" @click="handleBack">
          &larr; Back to Requests
        </button>
        <span :class="`ss-dash-method ss-dash-method-${(traceDetail.method || '').toLowerCase()}`">
          {{ traceDetail.method }}
        </span>
        <span style="color: var(--ss-text)">{{ traceDetail.url }}</span>
        <span
          :class="`ss-dash-status ss-dash-status-${Math.floor((traceDetail.statusCode || 200) / 100)}xx`"
        >
          {{ traceDetail.statusCode }}
        </span>
        <span class="ss-dash-tl-meta">
          {{ traceDetail.totalDuration.toFixed(1) }}ms &middot; {{ traceDetail.spanCount }} spans
        </span>
      </div>
      <WaterfallChart
        :spans="traceDetail.spans as any"
        :total-duration="traceDetail.totalDuration"
        :warnings="traceDetail.warnings"
      />
    </template>

    <!-- Loading detail -->
    <template v-else-if="detailLoading">
      <div class="ss-dash-tl-detail-header">
        <button type="button" class="ss-dash-btn" @click="detailLoading = false">
          &larr; Back to Requests
        </button>
      </div>
      <div class="ss-dash-empty">Loading request detail...</div>
    </template>

    <!-- List view -->
    <template v-else>
      <FilterBar
        :model-value="search"
        placeholder="Filter requests..."
        :summary="`${pagination.total ?? 0} requests`"
        @update:model-value="handleSearch"
      />

      <div v-if="error" class="ss-dash-empty">Failed to load requests</div>

      <div v-if="loading && !data" class="ss-dash-empty">Loading requests...</div>

      <template v-else>
        <div class="ss-dash-table-wrap">
          <table v-if="requests.length > 0" ref="tableRef" class="ss-dash-table">
            <colgroup>
              <col style="width: 40px" />
              <col style="width: 70px" />
              <col />
              <col style="width: 60px" />
              <col style="width: 80px" />
              <col style="width: 50px" />
              <col style="width: 40px" />
              <col style="width: 80px" />
            </colgroup>
            <thead>
              <tr>
                <th>#</th>
                <th class="ss-dash-sortable" @click="handleSort('method')">
                  Method
                  <span v-if="sort.column === 'method'" class="ss-dash-sort-arrow">{{
                    sort.direction === 'asc' ? ' \u25B2' : ' \u25BC'
                  }}</span>
                </th>
                <th class="ss-dash-sortable" @click="handleSort('url')">
                  URL
                  <span v-if="sort.column === 'url'" class="ss-dash-sort-arrow">{{
                    sort.direction === 'asc' ? ' \u25B2' : ' \u25BC'
                  }}</span>
                </th>
                <th class="ss-dash-sortable" @click="handleSort('statusCode')">
                  Status
                  <span v-if="sort.column === 'statusCode'" class="ss-dash-sort-arrow">{{
                    sort.direction === 'asc' ? ' \u25B2' : ' \u25BC'
                  }}</span>
                </th>
                <th class="ss-dash-sortable" @click="handleSort('duration')">
                  Duration
                  <span v-if="sort.column === 'duration'" class="ss-dash-sort-arrow">{{
                    sort.direction === 'asc' ? ' \u25B2' : ' \u25BC'
                  }}</span>
                </th>
                <th>Spans</th>
                <th>&#x26A0;</th>
                <th class="ss-dash-sortable" @click="handleSort('createdAt')">
                  Time
                  <span v-if="sort.column === 'createdAt'" class="ss-dash-sort-arrow">{{
                    sort.direction === 'asc' ? ' \u25B2' : ' \u25BC'
                  }}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="r in requests"
                :key="r.id as number"
                class="ss-dash-clickable"
                @click="handleRowClick(r)"
              >
                <td>
                  <span style="color: var(--ss-dim)">{{ r.id }}</span>
                </td>
                <td>
                  <span
                    :class="`ss-dash-method ss-dash-method-${((r.method as string) || '').toLowerCase()}`"
                  >
                    {{ r.method }}
                  </span>
                </td>
                <td>
                  <span
                    style="
                      color: var(--ss-text);
                      overflow: hidden;
                      text-overflow: ellipsis;
                      white-space: nowrap;
                    "
                    :title="r.url as string"
                  >
                    {{ r.url }}
                  </span>
                </td>
                <td>
                  <span
                    :class="`ss-dash-status ss-dash-status-${Math.floor(((r.status_code as number) || (r.statusCode as number) || 200) / 100)}xx`"
                  >
                    {{ r.status_code || r.statusCode }}
                  </span>
                </td>
                <td>
                  <span
                    :class="`ss-dash-duration ${dashDurationClass((r.total_duration as number) || (r.totalDuration as number) || (r.duration as number) || 0)}`"
                  >
                    {{
                      (
                        (r.total_duration as number) ||
                        (r.totalDuration as number) ||
                        (r.duration as number) ||
                        0
                      ).toFixed(1)
                    }}ms
                  </span>
                </td>
                <td>
                  <span style="color: var(--ss-muted); text-align: center">
                    {{ (r.span_count as number) || (r.spanCount as number) || 0 }}
                  </span>
                </td>
                <td>
                  <span
                    v-if="((r.warning_count as number) || (r.warningCount as number) || 0) > 0"
                    style="color: var(--ss-amber-fg); text-align: center; display: block"
                  >
                    {{ (r.warning_count as number) || (r.warningCount as number) || 0 }}
                  </span>
                  <span v-else style="color: var(--ss-dim); text-align: center; display: block"
                    >-</span
                  >
                </td>
                <td>
                  <span
                    class="ss-dash-event-time"
                    :title="
                      formatTime(
                        ((r.createdAt as string) ||
                          (r.created_at as string) ||
                          (r.timestamp as string) ||
                          '') as string
                      )
                    "
                  >
                    {{
                      timeAgo(
                        ((r.createdAt as string) ||
                          (r.created_at as string) ||
                          (r.timestamp as string) ||
                          '') as string
                      )
                    }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
          <div v-else class="ss-dash-empty">No requests recorded yet</div>
        </div>
        <PaginationControls
          v-if="pagination.totalPages > 1"
          :page="pagination.page"
          :last-page="pagination.totalPages"
          :total="pagination.total"
          @page-change="goToPage"
        />
      </template>
    </template>
  </div>
</template>
