// src/vue/components/Dashboard/shared/DataTable.vue
<script setup lang="ts">
/**
 * Reusable data table component for the dashboard.
 *
 * Supports sortable columns, row click handlers,
 * and slot-based cell rendering.
 */
import { useResizableTable } from '../../../composables/useResizableTable.js'

export interface Column {
  key: string
  label: string
  width?: string
  sortable?: boolean
  align?: 'left' | 'center' | 'right'
}

const props = defineProps<{
  columns: Column[]
  rows: Record<string, unknown>[]
  keyField?: string
  sortColumn?: string
  sortDirection?: 'asc' | 'desc'
  emptyMessage?: string
  clickable?: boolean
  rowClassName?: string
  className?: string
}>()

const emit = defineEmits<{
  sort: [column: string]
  rowClick: [row: Record<string, unknown>, index: number]
}>()

function handleSort(col: Column) {
  if (col.sortable) {
    emit('sort', col.key)
  }
}

const { tableRef } = useResizableTable(() => props.rows)
</script>

<template>
  <div v-if="rows.length === 0" class="ss-dash-empty">
    {{ emptyMessage || 'No data' }}
  </div>

  <table v-else ref="tableRef" :class="`ss-dash-table ${className || ''}`">
    <colgroup>
      <col
        v-for="col in columns"
        :key="col.key"
        :style="col.width ? { width: col.width } : undefined"
      />
    </colgroup>
    <thead>
      <tr>
        <th
          v-for="col in columns"
          :key="col.key"
          :class="col.sortable ? 'ss-dash-sortable' : ''"
          @click="handleSort(col)"
        >
          {{ col.label }}
          <span v-if="col.sortable && sortColumn === col.key" class="ss-dash-sort-arrow">
            {{ sortDirection === 'asc' ? ' \u25B2' : ' \u25BC' }}
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr
        v-for="(row, index) in rows"
        :key="(row[keyField || 'id'] as PropertyKey) ?? index"
        :class="
          [clickable ? 'ss-dash-clickable' : '', rowClassName || ''].filter(Boolean).join(' ')
        "
        @click="clickable ? emit('rowClick', row, index) : undefined"
      >
        <td v-for="col in columns" :key="col.key">
          <slot :name="`cell-${col.key}`" :value="row[col.key]" :row="row" :index="index">
            {{ row[col.key] ?? '-' }}
          </slot>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// src/react/components/Dashboard/shared/DataTable.tsx
import React, { useCallback } from 'react'

import { useResizableTable } from '../../../hooks/useResizableTable.js'

interface Column<T> {
  key: string
  label: string
  width?: string
  render?: (value: unknown, row: T) => React.ReactNode
  sortable?: boolean
}

interface DataTableProps<T> {
  columns: Column<T>[]
  data: T[]
  keyField?: string
  sort?: string
  sortDir?: 'asc' | 'desc'
  onSort?: (key: string) => void
  onRowClick?: (row: T) => void
  rowClassName?: string | ((row: T) => string)
  emptyMessage?: string
  className?: string
  renderAfterRow?: (row: T, index: number) => React.ReactNode
}

/**
 * Reusable data table component for dashboard sections.
 */
export function DataTable<T extends Record<string, unknown>>({
  columns,
  data,
  keyField = 'id',
  sort,
  sortDir,
  onSort,
  onRowClick,
  rowClassName,
  emptyMessage = 'No data',
  className = '',
  renderAfterRow,
}: DataTableProps<T>) {
  const handleSort = useCallback(
    (key: string) => {
      if (onSort) onSort(key)
    },
    [onSort]
  )

  const tableRef = useResizableTable([data, columns])

  if (data.length === 0) {
    return <div className="ss-dash-empty">{emptyMessage}</div>
  }

  return (
    <table ref={tableRef} className={`ss-dash-table ${className}`}>
      <colgroup>
        {columns.map((col) => (
          <col key={col.key} style={col.width ? { width: col.width } : undefined} />
        ))}
      </colgroup>
      <thead>
        <tr>
          {columns.map((col) => (
            <th
              key={col.key}
              onClick={col.sortable ? () => handleSort(col.key) : undefined}
              className={col.sortable ? 'ss-dash-sortable' : ''}
            >
              {col.label}
              {sort === col.key && (
                <span className="ss-dash-sort-arrow">
                  {sortDir === 'asc' ? ' \u25B2' : ' \u25BC'}
                </span>
              )}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {data.map((row, i) => {
          const extraClass = rowClassName
            ? typeof rowClassName === 'function'
              ? rowClassName(row)
              : rowClassName
            : ''
          const clickClass = onRowClick ? 'ss-dash-clickable' : ''
          return (
          <React.Fragment key={row[keyField] ?? i}>
          <tr
            onClick={onRowClick ? () => onRowClick(row) : undefined}
            className={`${clickClass} ${extraClass}`.trim()}
          >
            {columns.map((col) => (
              <td key={col.key}>
                {col.render ? col.render(row[col.key], row) : (row[col.key] ?? '-')}
              </td>
            ))}
          </tr>
          {renderAfterRow ? renderAfterRow(row, i) : null}
          </React.Fragment>
          )
        })}
      </tbody>
    </table>
  )
}
