// src/vue/components/Dashboard/shared/FilterBar.vue
<script setup lang="ts">
/**
 * Search/filter bar for dashboard sections.
 */
const props = defineProps<{
  modelValue: string
  placeholder?: string
  summary?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
  clear: []
}>()

function onInput(event: Event) {
  emit('update:modelValue', (event.target as HTMLInputElement).value)
}

function handleClear() {
  emit('update:modelValue', '')
  emit('clear')
}
</script>

<template>
  <div class="ss-dash-filter-bar">
    <span v-if="summary" class="ss-dash-summary">{{ summary }}</span>
    <div class="ss-dash-search-wrapper">
      <svg
        class="ss-dash-search-icon"
        viewBox="0 0 24 24"
        width="14"
        height="14"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="11" cy="11" r="8" />
        <line x1="21" y1="21" x2="16.65" y2="16.65" />
      </svg>
      <input
        class="ss-dash-search"
        type="text"
        :value="modelValue"
        :placeholder="placeholder || 'Search...'"
        @input="onInput"
      />
      <button v-if="modelValue" type="button" class="ss-dash-search-clear" @click="handleClear">&times;</button>
    </div>
    <div v-if="$slots.default" class="ss-dash-filter-controls">
      <slot />
    </div>
  </div>
</template>

// src/react/components/Dashboard/shared/FilterBar.tsx
import React, { useCallback } from 'react'

interface FilterBarProps {
  search: string
  onSearchChange: (value: string) => void
  placeholder?: string
  children?: React.ReactNode
  className?: string
}

/**
 * Search/filter bar with optional additional controls.
 */
export function FilterBar({
  search,
  onSearchChange,
  placeholder = 'Search...',
  children,
  className = '',
}: FilterBarProps) {
  const handleClear = useCallback(() => {
    onSearchChange('')
  }, [onSearchChange])

  return (
    <div className={`ss-dash-filter-bar ${className}`}>
      <div className="ss-dash-search-wrapper">
        <svg
          className="ss-dash-search-icon"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
        <input
          type="text"
          className="ss-dash-search"
          placeholder={placeholder}
          value={search}
          onChange={(e) => onSearchChange(e.target.value)}
        />
        {search && (
          <button type="button" className="ss-dash-search-clear" onClick={handleClear}>
            {'\u00D7'}
          </button>
        )}
      </div>
      {children && <div className="ss-dash-filter-controls">{children}</div>}
    </div>
  )
}
