// src/react/components/shared/JsonViewer.tsx
import React, { useState, useCallback, useMemo } from 'react'

import { compactPreview } from '../../../core/formatters.js'

interface JsonViewerProps {
  data: unknown
  maxPreviewLength?: number
  className?: string
  classPrefix?: 'ss-dash' | 'ss-dbg'
}

/**
 * Compact JSON preview with click-to-expand functionality.
 */
export function JsonViewer({ data, maxPreviewLength = 100, className = '', classPrefix = 'ss-dash' }: JsonViewerProps) {
  const [expanded, setExpanded] = useState(false)

  const parsed = useMemo(() => {
    if (typeof data === 'string') {
      try {
        return JSON.parse(data)
      } catch {
        return data
      }
    }
    return data
  }, [data])

  const preview = useMemo(() => {
    if (typeof parsed === 'object' && parsed !== null) {
      return compactPreview(parsed, maxPreviewLength)
    }
    return String(parsed ?? '-')
  }, [parsed, maxPreviewLength])

  const fullJson = useMemo(() => {
    if (typeof parsed === 'object' && parsed !== null) {
      return JSON.stringify(parsed, null, 2)
    }
    return String(parsed)
  }, [parsed])

  const handleToggle = useCallback(() => {
    setExpanded((prev) => !prev)
  }, [])

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(fullJson)
    } catch {
      // Fallback: select text
    }
  }, [fullJson])

  if (!data && data !== 0 && data !== false) {
    return <span className={`ss-dim ${classPrefix}-c-dim`}>-</span>
  }

  return (
    <div className={`${classPrefix}-data-cell ${className}`}>
      <span
        className={`${classPrefix}-data-preview`}
        onClick={handleToggle}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Enter' && handleToggle()}
      >
        {preview}
      </span>
      {expanded && (
        <div className={`${classPrefix}-data-full`} onClick={handleToggle}>
          <button
            className={`${classPrefix}-copy-btn`}
            onClick={(e) => {
              e.stopPropagation()
              handleCopy()
            }}
            title="Copy to clipboard"
            type="button"
          >
            Copy
          </button>
          <pre>{fullJson}</pre>
        </div>
      )}
    </div>
  )
}

// src/vue/components/shared/JsonViewer.vue
<script setup lang="ts">
/**
 * Compact JSON preview with click-to-expand.
 */
import { ref, computed } from 'vue'
import { compactPreview } from '../../../core/index.js'

const props = withDefaults(
  defineProps<{
    /** The value to display (object, array, or primitive). */
    value: unknown
    /** Maximum preview length. */
    maxLen?: number
    /** CSS class prefix: 'ss-dash' for dashboard, 'ss-dbg' for debug panel. */
    classPrefix?: 'ss-dash' | 'ss-dbg'
  }>(),
  {
    classPrefix: 'ss-dash',
  }
)

const expanded = ref(false)

const preview = computed(() => {
  if (props.value === null || props.value === undefined) return '-'
  if (typeof props.value === 'string') {
    try {
      return compactPreview(JSON.parse(props.value), props.maxLen || 100)
    } catch {
      return props.value.length > 100 ? props.value.slice(0, 100) + '...' : props.value
    }
  }
  return compactPreview(props.value, props.maxLen || 100)
})

const fullJson = computed(() => {
  if (props.value === null || props.value === undefined) return ''
  if (typeof props.value === 'string') {
    try {
      return JSON.stringify(JSON.parse(props.value), null, 2)
    } catch {
      return props.value
    }
  }
  return JSON.stringify(props.value, null, 2)
})

function toggle() {
  expanded.value = !expanded.value
}

function copyToClipboard() {
  navigator.clipboard?.writeText(fullJson.value)
}
</script>

<template>
  <span v-if="value === null || value === undefined" :class="`ss-dim ${props.classPrefix}-c-dim`">-</span>
  <div v-else :class="`${props.classPrefix}-data-cell`">
    <span
      :class="`${props.classPrefix}-data-preview`"
      role="button"
      :tabindex="0"
      @click="toggle"
      @keydown="(e: KeyboardEvent) => e.key === 'Enter' && toggle()"
    >
      {{ preview }}
    </span>
    <div v-if="expanded" :class="`${props.classPrefix}-data-full`" @click="toggle">
      <button
        :class="`${props.classPrefix}-copy-btn`"
        title="Copy to clipboard"
        @click.stop="copyToClipboard"
      >
        Copy
      </button>
      <pre>{{ fullJson }}</pre>
    </div>
  </div>
</template>
