// src/react/components/shared/ThemeToggle.tsx
import React from 'react'

import type { Theme } from '../../../core/types.js'
import { TAB_ICONS } from '../../../core/icons.js'

interface ThemeToggleProps {
  theme: Theme
  onToggle: () => void
  className?: string
  classPrefix?: 'ss-dash' | 'ss-dbg'
}

/**
 * Sun/moon toggle button for switching between light and dark themes.
 */
export function ThemeToggle({ theme, onToggle, className = '', classPrefix = 'ss-dash' }: ThemeToggleProps) {
  const isDark = theme === 'dark'
  const baseClass = classPrefix === 'ss-dbg' ? 'ss-dbg-theme-toggle' : 'ss-dash-theme-btn'

  return (
    <button
      type="button"
      className={`${baseClass} ${className}`}
      onClick={onToggle}
      title={isDark ? 'Switch to light theme' : 'Switch to dark theme'}
      aria-label={isDark ? 'Switch to light theme' : 'Switch to dark theme'}
    >
      {isDark ? (
        // Sun icon
        <svg
          width="16"
          height="16"
          viewBox={TAB_ICONS.sun.viewBox}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          dangerouslySetInnerHTML={{ __html: TAB_ICONS.sun.elements.join('') }}
        />
      ) : (
        // Moon icon
        <svg
          width="16"
          height="16"
          viewBox={TAB_ICONS.moon.viewBox}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          dangerouslySetInnerHTML={{ __html: TAB_ICONS.moon.elements.join('') }}
        />
      )}
    </button>
  )
}

// src/vue/components/shared/ThemeToggle.vue
<script setup lang="ts">
/**
 * Sun/moon toggle button for switching between light and dark themes.
 */
import { computed } from 'vue'
import { useTheme } from '../../composables/useTheme.js'
import { TAB_ICONS } from '../../../core/icons.js'

const props = withDefaults(
  defineProps<{
    classPrefix?: 'ss-dash' | 'ss-dbg'
  }>(),
  { classPrefix: 'ss-dbg' }
)

const { theme, toggleTheme } = useTheme()

const isDark = computed(() => theme.value === 'dark')
const title = computed(() =>
  isDark.value ? 'Switch to light theme' : 'Switch to dark theme'
)
const baseClass = computed(() =>
  props.classPrefix === 'ss-dbg' ? 'ss-dbg-theme-toggle' : 'ss-dash-theme-btn'
)
</script>

<template>
  <button type="button" :class="baseClass" :title="title" :aria-label="title" @click="toggleTheme">
    <!-- Sun icon -->
    <svg
      v-if="isDark"
      width="16"
      height="16"
      :viewBox="TAB_ICONS.sun.viewBox"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      v-html="TAB_ICONS.sun.elements.join('')"
    ></svg>
    <!-- Moon icon -->
    <svg
      v-else
      width="16"
      height="16"
      :viewBox="TAB_ICONS.moon.viewBox"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      v-html="TAB_ICONS.moon.elements.join('')"
    ></svg>
  </button>
</template>
