// src/react/components/DebugPanel/tabs/CustomPaneTab.tsx
import React, { useState, useMemo } from 'react'

import {
  formatTime,
  timeAgo,
  formatDuration,
  compactPreview,
  durationSeverity,
} from '../../../../core/formatters.js'
import { useDebugData } from '../../../hooks/useDebugData.js'
import { useResizableTable } from '../../../hooks/useResizableTable.js'

import type { DebugPane, DebugPanelProps, DebugTab } from '../../../../core/types.js'

interface CustomPaneTabProps {
  pane: DebugPane
  options?: DebugPanelProps
}

/**
 * Config-driven custom pane renderer.
 *
 * Renders any user-registered custom pane based on its column
 * definitions, data endpoint, and formatting configuration.
 */
export function CustomPaneTab({ pane, options }: CustomPaneTabProps) {
  // Build custom endpoint options
  const _paneOptions: DebugPanelProps = {
    ...options,
    debugEndpoint: '', // Direct endpoint
  }

  const { data, isLoading, error, clearData } = useDebugData<Record<string, unknown>>(
    pane.endpoint.replace(/^\//, '') as DebugTab,
    {
      ...options,
      debugEndpoint: '', // Use endpoint directly
    }
  )
  const [search, setSearch] = useState('')

  // Extract data array from response using dataKey
  const rows = useMemo(() => {
    if (!data) return []
    const key = pane.dataKey || pane.id
    // Support dot notation
    let result: unknown = data
    for (const part of key.split('.')) {
      result = (result as Record<string, unknown>)?.[part]
    }
    return Array.isArray(result) ? result : []
  }, [data, pane.dataKey, pane.id])

  // Filter by search
  const filteredRows = useMemo(() => {
    if (!search) return rows
    const lower = search.toLowerCase()
    const searchableKeys = pane.columns.filter((c) => c.searchable).map((c) => c.key)
    if (searchableKeys.length === 0) return rows
    return rows.filter((row: Record<string, unknown>) =>
      searchableKeys.some((key) => {
        const val = row[key]
        return val !== null && String(val).toLowerCase().includes(lower)
      })
    )
  }, [rows, search, pane.columns])

  const formatCell = (value: unknown, col: (typeof pane.columns)[0]): React.ReactNode => {
    if (value === null || value === undefined) {
      return <span className="ss-dbg-c-dim">-</span>
    }

    const fmt = col.format || 'text'
    switch (fmt) {
      case 'time':
        return (
          <span className="ss-dbg-event-time" title={formatTime(value as number)}>
            {typeof value === 'number' ? timeAgo(value) : String(value)}
          </span>
        )
      case 'timeAgo':
        return (
          <span className="ss-dbg-event-time" title={formatTime(value as string)}>
            {timeAgo(value as string)}
          </span>
        )
      case 'duration': {
        const ms = typeof value === 'number' ? value : parseFloat(String(value))
        if (isNaN(ms)) return String(value)
        return (
          <span
            className={`ss-dbg-duration ${durationSeverity(ms) === 'very-slow' ? 'ss-dbg-very-slow' : durationSeverity(ms) === 'slow' ? 'ss-dbg-slow' : ''}`}
          >
            {formatDuration(ms)}
          </span>
        )
      }
      case 'method':
        return (
          <span className={`ss-dbg-method ss-dbg-method-${String(value).toLowerCase()}`}>
            {String(value)}
          </span>
        )
      case 'json': {
        let parsed = value
        if (typeof value === 'string') {
          try {
            parsed = JSON.parse(value)
          } catch {
            /* use as-is */
          }
        }
        return compactPreview(parsed as Record<string, unknown>, 80)
      }
      case 'badge': {
        const sv = String(value).toLowerCase()
        const colorMap = col.badgeColorMap || {}
        const color = colorMap[sv] || 'muted'
        return <span className={`ss-dbg-badge ss-dbg-badge-${color}`}>{String(value)}</span>
      }
      default:
        return String(value)
    }
  }

  const tableRef = useResizableTable([filteredRows])

  if (isLoading && !data) {
    return <div className="ss-dbg-empty">Loading {pane.label}...</div>
  }

  if (error) {
    return <div className="ss-dbg-empty">Error: {error.message}</div>
  }

  return (
    <div>
      {/* Search bar */}
      {pane.search && (
        <div className="ss-dbg-search-bar">
          <input
            type="text"
            className="ss-dbg-search"
            placeholder={pane.search.placeholder}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <span className="ss-dbg-summary">{filteredRows.length} items</span>
          {pane.clearable && (
            <button type="button" className="ss-dbg-btn-clear" onClick={clearData}>
              Clear
            </button>
          )}
        </div>
      )}

      {/* Table */}
      {filteredRows.length === 0 ? (
        <div className="ss-dbg-empty">No data</div>
      ) : (
        <table ref={tableRef} className="ss-dbg-table">
          <thead>
            <tr>
              {pane.columns.map((col) => (
                <th key={col.key}>{col.label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filteredRows.map((row, i) => (
              <tr key={row.id ?? i}>
                {pane.columns.map((col) => (
                  <td key={col.key}>{formatCell(row[col.key], col)}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}

export default CustomPaneTab

// src/vue/components/DebugPanel/tabs/CustomPaneTab.vue
<script setup lang="ts">
/**
 * Config-driven custom pane tab for the debug panel.
 *
 * Renders a table based on DebugPane column definitions
 * with support for search, formatting, and badge colors.
 */
import { ref, computed, onMounted } from 'vue'
import {
  compactPreview,
  formatTime,
  timeAgo,
  formatDuration,
  durationSeverity,
} from '../../../../core/index.js'
import { useApiClient } from '../../../composables/useApiClient.js'
import { useResizableTable } from '../../../composables/useResizableTable.js'
import type { DebugPane, DebugPaneColumn } from '../../../../core/index.js'

const props = defineProps<{
  pane: DebugPane
  baseUrl?: string
  authToken?: string
}>()

const data = ref<Record<string, unknown>[]>([])
const loading = ref(false)
const search = ref('')

const getClient = useApiClient(props.baseUrl || '', props.authToken)
let fetched = false

async function fetchData() {
  if (props.pane.fetchOnce && fetched) return
  loading.value = true
  try {
    const result = await getClient().fetch(props.pane.endpoint)
    // Extract data using dataKey or pane id
    const dataKey = props.pane.dataKey || props.pane.id
    const parts = dataKey.split('.')
    let extracted: unknown = result
    for (const part of parts) {
      extracted = (extracted as Record<string, unknown>)?.[part]
    }
    data.value = Array.isArray(extracted) ? extracted : []
    fetched = true
  } catch {
    data.value = []
  } finally {
    loading.value = false
  }
}

const filteredData = computed(() => {
  if (!search.value.trim()) return data.value
  const term = search.value.toLowerCase()
  const searchableCols = props.pane.columns.filter((c) => c.searchable).map((c) => c.key)
  if (searchableCols.length === 0) return data.value
  return data.value.filter((row) =>
    searchableCols.some((key) => {
      const val = row[key]
      if (val === null || val === undefined) return false
      return String(val).toLowerCase().includes(term)
    })
  )
})

function formatCell(value: unknown, col: DebugPaneColumn): string {
  if (value === null || value === undefined) return '-'
  const fmt = col.format || 'text'
  switch (fmt) {
    case 'time':
      return typeof value === 'number' ? timeAgo(value) : String(value)
    case 'timeAgo':
      return timeAgo(value as number | string)
    case 'duration':
      return formatDuration(typeof value === 'number' ? value : parseFloat(String(value)))
    case 'method':
      return String(value)
    case 'json': {
      let parsed: unknown = value
      if (typeof value === 'string') {
        try {
          parsed = JSON.parse(value)
        } catch {}
      }
      return compactPreview(parsed, 80)
    }
    case 'badge':
      return String(value)
    default:
      return String(value)
  }
}

function cellTitle(value: unknown, col: DebugPaneColumn): string | undefined {
  if (col.format === 'time' || col.format === 'timeAgo') {
    return formatTime(value as number | string)
  }
  return undefined
}

function isNullish(value: unknown): boolean {
  return value === null || value === undefined
}

function durationClass(value: unknown): string {
  const ms = typeof value === 'number' ? value : parseFloat(String(value))
  if (isNaN(ms)) return 'ss-dbg-duration'
  const sev = durationSeverity(ms)
  if (sev === 'very-slow') return 'ss-dbg-duration ss-dbg-very-slow'
  if (sev === 'slow') return 'ss-dbg-duration ss-dbg-slow'
  return 'ss-dbg-duration'
}

function badgeColor(value: unknown, col: DebugPaneColumn): string {
  if (col.format === 'badge' && col.badgeColorMap) {
    const sv = String(value).toLowerCase()
    return col.badgeColorMap[sv] || 'muted'
  }
  return ''
}

function methodClass(value: unknown): string {
  return `ss-dbg-method ss-dbg-method-${String(value).toLowerCase()}`
}

function handleClear() {
  data.value = []
}

const { tableRef } = useResizableTable(() => filteredData.value)

onMounted(() => {
  fetchData()
})
</script>

<template>
  <div>
    <div v-if="pane.search" class="ss-dbg-search-bar">
      <input
        v-model="search"
        class="ss-dbg-search"
        :placeholder="pane.search.placeholder"
        type="text"
      />
      <span class="ss-dbg-summary">{{ filteredData.length }} items</span>
      <button v-if="pane.clearable" class="ss-dbg-btn-clear" @click="handleClear">Clear</button>
    </div>

    <div v-if="loading" class="ss-dbg-empty">Loading...</div>
    <div v-else-if="filteredData.length === 0" class="ss-dbg-empty">No data</div>

    <table v-else ref="tableRef" class="ss-dbg-table">
      <thead>
        <tr>
          <th v-for="col in pane.columns" :key="col.key">
            {{ col.label }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, i) in filteredData" :key="row.id ?? i">
          <td
            v-for="col in pane.columns"
            :key="col.key"
            :class="{ 'ss-dbg-filterable': col.filterable }"
            @click="col.filterable ? (search = String(row[col.key])) : undefined"
          >
            <!-- null / undefined -->
            <template v-if="isNullish(row[col.key])">
              <span class="ss-dbg-c-dim">-</span>
            </template>
            <!-- time / timeAgo -->
            <template v-else-if="col.format === 'time' || col.format === 'timeAgo'">
              <span class="ss-dbg-event-time" :title="cellTitle(row[col.key], col)">
                {{ formatCell(row[col.key], col) }}
              </span>
            </template>
            <!-- duration -->
            <template v-else-if="col.format === 'duration'">
              <span :class="durationClass(row[col.key])">
                {{ formatCell(row[col.key], col) }}
              </span>
            </template>
            <!-- method -->
            <template v-else-if="col.format === 'method'">
              <span :class="methodClass(row[col.key])">
                {{ formatCell(row[col.key], col) }}
              </span>
            </template>
            <!-- badge -->
            <template v-else-if="col.format === 'badge'">
              <span :class="`ss-dbg-badge ss-dbg-badge-${badgeColor(row[col.key], col)}`">
                {{ formatCell(row[col.key], col) }}
              </span>
            </template>
            <!-- json / text / default -->
            <template v-else>
              {{ formatCell(row[col.key], col) }}
            </template>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
