// src/react/components/DebugPanel/tabs/LogsTab.tsx
import React, { useState, useMemo, useCallback } from 'react'

import { formatTime, timeAgo } from '../../../../core/formatters.js'
import { useDebugData } from '../../../hooks/useDebugData.js'

import type { DebugPanelProps } from '../../../../core/types.js'

interface LogEntry {
  level: string
  msg: string
  time: number
  requestId?: string
  [key: string]: string | number | boolean | undefined
}

interface LogsTabProps {
  options?: DebugPanelProps
}

const LOG_LEVELS = ['all', 'error', 'warn', 'info', 'debug'] as const

export function LogsTab({ options }: LogsTabProps) {
  const { data, isLoading, error } = useDebugData<LogEntry[] | { logs?: LogEntry[]; entries?: LogEntry[] }>('logs', options)
  const [levelFilter, setLevelFilter] = useState<string>('all')
  const [search, setSearch] = useState('')
  const [reqIdFilter, setReqIdFilter] = useState('')

  /** Resolve the log level from whichever field the backend provides. */
  const resolveLevel = useCallback(
    (l: LogEntry) =>
      (
        (l.levelName as string) ||
        (l.level_name as string) ||
        (typeof l.level === 'string' ? l.level : '') ||
        'info'
      ).toLowerCase(),
    []
  )

  /** Resolve the message from whichever field the backend provides. */
  const resolveMsg = useCallback(
    (l: LogEntry) => (l.msg as string) || (l.message as string) || JSON.stringify(l),
    []
  )

  /** Resolve the timestamp from whichever field the backend provides. */
  const resolveTime = useCallback(
    (l: LogEntry) => (l.time as number) || (l.timestamp as number) || 0,
    []
  )

  /** Resolve the request ID from whichever field the backend provides. */
  const resolveReqId = useCallback(
    (l: LogEntry) =>
      (l.requestId as string) ||
      (l.request_id as string) ||
      (l['x-request-id'] as string) ||
      '',
    []
  )

  const logs = useMemo(() => {
    let items: LogEntry[] = Array.isArray(data)
      ? data
      : (data?.logs || data?.entries || [])
    if (levelFilter !== 'all') {
      items = items.filter((l) => {
        const level = resolveLevel(l)
        if (levelFilter === 'error') return level === 'error' || level === 'fatal'
        return level === levelFilter
      })
    }
    if (reqIdFilter) {
      const f = reqIdFilter.toLowerCase()
      items = items.filter((l) => {
        const rid = resolveReqId(l).toLowerCase()
        return rid.includes(f)
      })
    }
    if (search) {
      const s = search.toLowerCase()
      items = items.filter((l) => resolveMsg(l).toLowerCase().includes(s))
    }
    return items
  }, [data, levelFilter, search, reqIdFilter, resolveLevel, resolveMsg, resolveReqId])

  const levelClass = useCallback((level: string) => {
    switch (level) {
      case 'error':
      case 'fatal':
        return 'ss-dbg-log-level-error'
      case 'warn':
        return 'ss-dbg-log-level-warn'
      case 'info':
        return 'ss-dbg-log-level-info'
      case 'debug':
        return 'ss-dbg-log-level-debug'
      case 'trace':
        return 'ss-dbg-log-level-trace'
      default:
        return 'ss-dbg-log-level-info'
    }
  }, [])

  const handleReqIdClick = useCallback((reqId: string) => {
    setReqIdFilter((prev) => (prev === reqId ? '' : reqId))
  }, [])

  if (isLoading && !data) {
    return <div className="ss-dbg-empty">Loading logs...</div>
  }

  if (error) {
    return <div className="ss-dbg-empty">Error: {error.message}</div>
  }

  return (
    <div>
      {/* Level filter buttons */}
      <div className="ss-dbg-log-filters">
        {LOG_LEVELS.map((level) => (
          <button
            key={level}
            type="button"
            className={`ss-dbg-log-filter ${levelFilter === level ? 'ss-dbg-active' : ''}`}
            onClick={() => setLevelFilter(level)}
          >
            {level}
          </button>
        ))}
        {reqIdFilter && (
          <button
            type="button"
            className="ss-dbg-log-filter ss-dbg-active"
            onClick={() => setReqIdFilter('')}
          >
            req: {reqIdFilter.slice(0, 8)} x
          </button>
        )}
        <span className="ss-dbg-summary" style={{ marginLeft: 'auto' }}>
          {logs.length} entries
        </span>
      </div>

      {/* Search bar */}
      <div className="ss-dbg-search-bar">
        <input
          type="text"
          className="ss-dbg-search"
          placeholder="Filter log messages..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {/* Log entries */}
      <div style={{ overflow: 'auto', flex: 1 }}>
        {logs.length === 0 ? (
          <div className="ss-dbg-empty">No log entries</div>
        ) : (
          logs.slice(-200).reverse().map((log, i) => {
            const level = resolveLevel(log)
            const msg = resolveMsg(log)
            const ts = resolveTime(log)
            const reqId = resolveReqId(log)

            return (
              <div key={i} className="ss-dbg-log-entry">
                <span className={`ss-dbg-log-level ${levelClass(level)}`}>
                  {level.toUpperCase()}
                </span>
                <span className="ss-dbg-log-time" title={ts ? formatTime(ts) : ''}>{ts ? timeAgo(ts) : '-'}</span>
                {reqId ? (
                  <span
                    className="ss-dbg-log-reqid"
                    onClick={() => handleReqIdClick(reqId)}
                    role="button"
                    tabIndex={0}
                    title={reqId}
                    onKeyDown={(e) => e.key === 'Enter' && handleReqIdClick(reqId)}
                  >
                    {reqId.slice(0, 8)}
                  </span>
                ) : (
                  <span className="ss-dbg-log-reqid-empty">-</span>
                )}
                <span className="ss-dbg-log-msg">{msg}</span>
              </div>
            )
          })
        )}
      </div>
    </div>
  )
}

export default LogsTab

// src/vue/components/DebugPanel/tabs/LogsTab.vue
<script setup lang="ts">
/**
 * Logs with level filter tab for the debug panel.
 */
import { ref, computed } from 'vue'
import { formatTime, shortReqId } from '../../../../core/index.js'

interface LogEntry {
  id?: number
  level: string | number
  levelName?: string
  level_name?: string
  msg?: string
  message?: string
  requestId?: string
  request_id?: string
  'x-request-id'?: string
  time?: number
  timestamp?: number
  data?: Record<string, unknown>
  [key: string]: unknown
}

const props = defineProps<{
  data: { logs?: LogEntry[]; entries?: LogEntry[] } | LogEntry[] | null
  dashboardPath?: string
}>()

const emit = defineEmits<{
  filterByRequestId: [requestId: string]
}>()

const activeLevel = ref('all')
const search = ref('')
const requestIdFilter = ref('')

const LEVELS = ['all', 'error', 'warn', 'info', 'debug'] as const

/** Resolve the log level string from whichever field the backend provides. */
function resolveLevel(l: LogEntry): string {
  return (
    (l.levelName as string) ||
    (l.level_name as string) ||
    (typeof l.level === 'string' ? l.level : '') ||
    'info'
  ).toLowerCase()
}

/** Resolve the message from whichever field the backend provides. */
function resolveMsg(l: LogEntry): string {
  return (l.msg as string) || (l.message as string) || JSON.stringify(l)
}

/** Resolve the timestamp from whichever field the backend provides. */
function resolveTime(l: LogEntry): number {
  return (l.time as number) || (l.timestamp as number) || 0
}

/** Resolve the request ID from whichever field the backend provides. */
function resolveReqId(l: LogEntry): string {
  return (l.requestId as string) || (l.request_id as string) || (l['x-request-id'] as string) || ''
}

const logs = computed<LogEntry[]>(() => {
  const d = props.data
  let arr: LogEntry[] = d ? (Array.isArray(d) ? d : d.logs || d.entries) || [] : []

  if (activeLevel.value !== 'all') {
    const level = activeLevel.value
    arr = arr.filter((l) => {
      const resolved = resolveLevel(l)
      if (level === 'error') return resolved === 'error' || resolved === 'fatal'
      return resolved === level
    })
  }

  if (requestIdFilter.value.trim()) {
    const rid = requestIdFilter.value.trim().toLowerCase()
    arr = arr.filter((l) => {
      const reqId = resolveReqId(l)
      return reqId && reqId.toLowerCase().includes(rid)
    })
  }

  if (search.value.trim()) {
    const s = search.value.trim().toLowerCase()
    arr = arr.filter((l) => resolveMsg(l).toLowerCase().includes(s))
  }

  return arr
})

const summary = computed(() => {
  const d = props.data
  const all = d ? (Array.isArray(d) ? d : d.logs || d.entries) || [] : []
  return `${logs.value.length} of ${all.length} entries`
})

function levelClass(level: string): string {
  const map: Record<string, string> = {
    info: 'ss-dbg-log-level-info',
    warn: 'ss-dbg-log-level-warn',
    error: 'ss-dbg-log-level-error',
    fatal: 'ss-dbg-log-level-fatal',
    debug: 'ss-dbg-log-level-debug',
    trace: 'ss-dbg-log-level-trace',
  }
  return map[level] || 'ss-dbg-log-level-debug'
}

function filterByReqId(reqId: string) {
  requestIdFilter.value = reqId
  emit('filterByRequestId', reqId)
}
</script>

<template>
  <div>
    <div class="ss-dbg-log-filters">
      <button
        v-for="level in LEVELS"
        :key="level"
        :class="['ss-dbg-log-filter', { 'ss-dbg-active': activeLevel === level }]"
        @click="activeLevel = level"
      >
        {{ level }}
      </button>
    </div>

    <div class="ss-dbg-search-bar">
      <input
        v-model="search"
        class="ss-dbg-search"
        placeholder="Filter log messages..."
        type="text"
      />
      <input
        v-model="requestIdFilter"
        class="ss-dbg-search ss-dbg-reqid-input"
        placeholder="Filter by request ID..."
        type="text"
      />
      <span class="ss-dbg-summary">{{ summary }}</span>
    </div>

    <div v-if="logs.length === 0" class="ss-dbg-empty">No log entries</div>

    <div v-else>
      <div v-for="(log, i) in logs" :key="log.id || i" class="ss-dbg-log-entry">
        <span :class="['ss-dbg-log-level', levelClass(resolveLevel(log))]">
          {{ resolveLevel(log).toUpperCase() }}
        </span>
        <span class="ss-dbg-log-time">{{ formatTime(resolveTime(log)) }}</span>
        <span
          v-if="resolveReqId(log)"
          class="ss-dbg-log-reqid"
          @click="filterByReqId(resolveReqId(log))"
          :title="resolveReqId(log)"
        >
          {{ shortReqId(resolveReqId(log)) }}
        </span>
        <span v-else class="ss-dbg-log-reqid-empty">--</span>
        <span class="ss-dbg-log-msg">{{ resolveMsg(log) }}</span>
        <a
          v-if="dashboardPath && resolveReqId(log)"
          :href="`${dashboardPath}#logs?requestId=${resolveReqId(log)}`"
          target="_blank"
          class="ss-dbg-deeplink"
        >
          <svg
            viewBox="0 0 16 16"
            width="12"
            height="12"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path d="M6 3H3v10h10v-3M9 1h6v6M7 9L15 1" />
          </svg>
        </a>
      </div>
    </div>
  </div>
</template>
