// src/react/components/DebugPanel/tabs/RoutesTab.tsx
import React, { useState, useMemo } from 'react'

import { useDebugData } from '../../../hooks/useDebugData.js'

import type { RouteRecord, DebugPanelProps } from '../../../../core/types.js'

interface RoutesTabProps {
  options?: DebugPanelProps
  currentPath?: string
}

export function RoutesTab({ options, currentPath }: RoutesTabProps) {
  const { data, isLoading, error } = useDebugData<{ routes: RouteRecord[] }>('routes', options)
  const [search, setSearch] = useState('')

  const routes = useMemo(() => {
    const items = data?.routes || []
    if (!search) return items
    const lower = search.toLowerCase()
    return items.filter(
      (r) =>
        r.pattern.toLowerCase().includes(lower) ||
        r.handler.toLowerCase().includes(lower) ||
        r.method.toLowerCase().includes(lower) ||
        (r.name && r.name.toLowerCase().includes(lower))
    )
  }, [data, search])

  if (isLoading && !data) {
    return <div className="ss-dbg-empty">Loading routes...</div>
  }

  if (error) {
    return <div className="ss-dbg-empty">Error: {error.message}</div>
  }

  return (
    <div>
      <div className="ss-dbg-search-bar">
        <input
          type="text"
          className="ss-dbg-search"
          placeholder="Filter routes..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <span className="ss-dbg-summary">{routes.length} routes</span>
      </div>

      {routes.length === 0 ? (
        <div className="ss-dbg-empty">No routes found</div>
      ) : (
        <table className="ss-dbg-table">
          <thead>
            <tr>
              <th style={{ width: '70px' }}>Method</th>
              <th>Pattern</th>
              <th style={{ width: '90px' }}>Name</th>
              <th>Handler</th>
              <th>Middleware</th>
            </tr>
          </thead>
          <tbody>
            {routes.map((route, i) => {
              const isCurrentRoute = currentPath && route.pattern === currentPath
              return (
                <tr
                  key={`${route.method}-${route.pattern}-${i}`}
                  className={isCurrentRoute ? 'ss-dbg-current-route' : ''}
                >
                  <td>
                    <span className={`ss-dbg-method ss-dbg-method-${route.method.toLowerCase()}`}>
                      {route.method}
                    </span>
                  </td>
                  <td style={{ color: 'var(--ss-text)' }}>{route.pattern}</td>
                  <td style={{ color: 'var(--ss-dim)' }}>{route.name || '-'}</td>
                  <td style={{ color: 'var(--ss-text-secondary)' }}>{route.handler}</td>
                  <td style={{ color: 'var(--ss-dim)', fontSize: '10px' }}>
                    {route.middleware.length > 0 ? route.middleware.join(', ') : '-'}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      )}
    </div>
  )
}

export default RoutesTab

// src/vue/components/DebugPanel/tabs/RoutesTab.vue
<script setup lang="ts">
/**
 * Route table tab for the debug panel.
 */
import { ref, computed } from 'vue'
import type { RouteRecord } from '../../../../core/index.js'

const props = defineProps<{
  data: any
  currentUrl?: string
}>()

const search = ref('')

const routes = computed<RouteRecord[]>(() => {
  const arr = props.data?.routes || props.data || []
  if (!search.value.trim()) return arr
  const term = search.value.toLowerCase()
  return arr.filter(
    (r: RouteRecord) =>
      r.pattern.toLowerCase().includes(term) ||
      r.handler.toLowerCase().includes(term) ||
      r.method.toLowerCase().includes(term) ||
      (r.name && r.name.toLowerCase().includes(term))
  )
})

const summary = computed(() => {
  const arr = props.data?.routes || props.data || []
  return `${arr.length} routes`
})

function isCurrentRoute(route: RouteRecord): boolean {
  if (!props.currentUrl) return false
  return props.currentUrl.includes(route.pattern.replace(/:[^/]+/g, ''))
}
</script>

<template>
  <div>
    <div class="ss-dbg-search-bar">
      <input
        v-model="search"
        class="ss-dbg-search"
        placeholder="Filter routes..."
        type="text"
      />
      <span class="ss-dbg-summary">{{ summary }}</span>
    </div>

    <div v-if="routes.length === 0" class="ss-dbg-empty">
      No routes found
    </div>

    <table v-else class="ss-dbg-table">
      <thead>
        <tr>
          <th style="width: 70px;">Method</th>
          <th>Pattern</th>
          <th style="width: 100px;">Name</th>
          <th>Handler</th>
          <th>Middleware</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(r, i) in routes"
          :key="i"
          :class="{ 'ss-dbg-current-route': isCurrentRoute(r) }"
        >
          <td>
            <span :class="`ss-dbg-method ss-dbg-method-${r.method.toLowerCase()}`">
              {{ r.method }}
            </span>
          </td>
          <td style="color: var(--ss-text);">{{ r.pattern }}</td>
          <td style="color: var(--ss-muted);">{{ r.name || '-' }}</td>
          <td style="color: var(--ss-text-secondary);">{{ r.handler }}</td>
          <td style="color: var(--ss-dim); font-size: 10px;">
            {{ r.middleware.length > 0 ? r.middleware.join(', ') : '-' }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
