// src/react/components/DebugPanel/tabs/TimelineTab.tsx
import React, { useState, useMemo, useCallback, useEffect, useRef } from 'react'

import {
  timeAgo,
  formatDuration,
  formatTime,
  durationSeverity,
} from '../../../../core/formatters.js'
import { initSplitPane } from '../../../../core/split-pane.js'
import { useApiClient } from '../../../hooks/useApiClient.js'
import { useDebugData } from '../../../hooks/useDebugData.js'
import { useResizableTable } from '../../../hooks/useResizableTable.js'
import { RelatedLogs } from '../../shared/RelatedLogs.js'

import type { TraceRecord, TraceSpan, DebugPanelProps } from '../../../../core/types.js'

function SplitPaneWrapper({
  children,
  classPrefix = 'ss-dbg',
  storageKey,
}: {
  children: [React.ReactNode, React.ReactNode]
  classPrefix?: string
  storageKey?: string
}) {
  const containerRef = useRef<HTMLDivElement>(null)
  const handleRef = useRef<HTMLDivElement>(null)
  const topRef = useRef<HTMLDivElement>(null)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (containerRef.current && handleRef.current && topRef.current && bottomRef.current) {
      return initSplitPane({
        container: containerRef.current,
        handle: handleRef.current,
        topPane: topRef.current,
        bottomPane: bottomRef.current,
        storageKey,
      })
    }
  }, [storageKey])

  return (
    <div ref={containerRef} className={`${classPrefix}-split-container`}>
      <div ref={topRef} className={`${classPrefix}-split-top`}>
        {children[0]}
      </div>
      <div ref={handleRef} className={`${classPrefix}-split-handle`} />
      <div ref={bottomRef} className={`${classPrefix}-split-bottom`}>
        {children[1]}
      </div>
    </div>
  )
}

interface TimelineTabProps {
  options?: DebugPanelProps
}

const BAR_COLORS: Record<string, string> = {
  request: '#1e3a5f',
  middleware: 'rgba(30, 58, 95, 0.7)',
  db: '#6d28d9',
  view: '#0e7490',
  mail: '#059669',
  event: '#b45309',
  custom: '#525252',
}

const LEGEND_ITEMS = [
  { label: 'Request', color: '#1e3a5f' },
  { label: 'Middleware', color: 'rgba(30, 58, 95, 0.7)' },
  { label: 'Database', color: '#6d28d9' },
  { label: 'View', color: '#0e7490' },
  { label: 'Mail', color: '#059669' },
  { label: 'Event', color: '#b45309' },
]

export function TimelineTab({ options }: TimelineTabProps) {
  const { baseUrl = '', debugEndpoint = '/admin/api/debug', authToken } = options || {}
  const { data, isLoading, error } = useDebugData<{ traces: TraceRecord[] }>('timeline', options)
  const [search, setSearch] = useState('')
  const [selectedTraceId, setSelectedTraceId] = useState<number | null>(null)
  const [traceDetail, setTraceDetail] = useState<TraceRecord | null>(null)
  const [detailLoading, setDetailLoading] = useState(false)
  const [detailError, setDetailError] = useState<string | null>(null)

  const traces = useMemo(() => {
    const items = data?.traces || []
    if (!search) return items
    const lower = search.toLowerCase()
    return items.filter(
      (t) =>
        t.url.toLowerCase().includes(lower) ||
        t.method.toLowerCase().includes(lower) ||
        String(t.statusCode).includes(lower)
    )
  }, [data, search])

  const getClient = useApiClient(baseUrl, authToken)

  // Fetch trace detail (with spans) when a trace is selected
  useEffect(() => {
    if (selectedTraceId === null) {
      setTraceDetail(null)
      setDetailError(null)
      return
    }

    let cancelled = false
    setDetailLoading(true)
    setDetailError(null)

    const client = getClient()
    client
      .get<TraceRecord>(`${debugEndpoint}/traces/${selectedTraceId}`)
      .then((detail) => {
        if (!cancelled) {
          setTraceDetail(detail)
          setDetailLoading(false)
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setDetailError(err instanceof Error ? err.message : 'Failed to load trace')
          setDetailLoading(false)
        }
      })

    return () => {
      cancelled = true
    }
  }, [selectedTraceId, debugEndpoint, getClient])

  const handleSelectTrace = useCallback((id: number) => {
    setSelectedTraceId((prev) => (prev === id ? null : id))
  }, [])

  const statusClass = useCallback((code: number) => {
    if (code >= 500) return 'ss-dbg-status-5xx'
    if (code >= 400) return 'ss-dbg-status-4xx'
    if (code >= 300) return 'ss-dbg-status-3xx'
    return 'ss-dbg-status-2xx'
  }, [])

  const tableRef = useResizableTable([traces])

  if (isLoading && !data) {
    return <div className="ss-dbg-empty">Loading traces...</div>
  }

  if (error) {
    return <div className="ss-dbg-empty">Error: {error.message}</div>
  }

  // Waterfall detail view
  if (selectedTraceId !== null) {
    if (detailLoading) {
      return <div className="ss-dbg-empty">Loading trace detail...</div>
    }

    if (detailError) {
      return (
        <div>
          <div className="ss-dbg-tl-detail-header">
            <button
              type="button"
              className="ss-dbg-btn-clear"
              onClick={() => setSelectedTraceId(null)}
            >
              &larr; Back
            </button>
          </div>
          <div className="ss-dbg-empty">Error: {detailError}</div>
        </div>
      )
    }

    if (!traceDetail) {
      return <div className="ss-dbg-empty">Loading trace detail...</div>
    }

    const spans = traceDetail.spans || []
    const warnings = traceDetail.warnings || []
    const detailLogs = traceDetail.logs || []
    const hasLogs = detailLogs.length > 0

    const waterfallContent = (
      <div>
        {/* Legend */}
        <div className="ss-dbg-tl-legend">
          {LEGEND_ITEMS.map((item) => (
            <div key={item.label} className="ss-dbg-tl-legend-item">
              <div className="ss-dbg-tl-legend-dot" style={{ background: item.color }} />
              <span>{item.label}</span>
            </div>
          ))}
        </div>

        {/* Waterfall rows */}
        <div style={{ padding: '8px 12px', overflow: 'auto' }}>
          {spans.length === 0 ? (
            <div className="ss-dbg-empty">No spans captured for this request</div>
          ) : (
            spans.map((span: TraceSpan) => {
              const totalDuration = traceDetail.totalDuration || 1
              const left = (span.startOffset / totalDuration) * 100
              const width = Math.max((span.duration / totalDuration) * 100, 0.5)

              return (
                <div key={span.id} className="ss-dbg-tl-row">
                  <div className="ss-dbg-tl-label" title={span.label}>
                    {span.label}
                  </div>
                  <div className="ss-dbg-tl-track">
                    <div
                      className={`ss-dbg-tl-bar ss-dbg-tl-bar-${span.category}`}
                      style={{
                        left: `${left}%`,
                        width: `${width}%`,
                        background: BAR_COLORS[span.category] || BAR_COLORS.custom,
                      }}
                      title={`${span.label}: ${formatDuration(span.duration)}`}
                    />
                  </div>
                  <span className="ss-dbg-tl-dur">{formatDuration(span.duration)}</span>
                </div>
              )
            })
          )}
        </div>

        {/* Warnings */}
        {warnings.length > 0 && (
          <div className="ss-dbg-tl-warnings">
            <div className="ss-dbg-tl-warnings-title">Warnings</div>
            {warnings.map((w, i) => (
              <div key={i} className="ss-dbg-tl-warning">
                {w}
              </div>
            ))}
          </div>
        )}
      </div>
    )

    return (
      <div>
        <div className="ss-dbg-tl-detail-header">
          <button
            type="button"
            className="ss-dbg-btn-clear"
            onClick={() => setSelectedTraceId(null)}
          >
            &larr; Back
          </button>
          <span className={`ss-dbg-method ss-dbg-method-${traceDetail.method.toLowerCase()}`}>
            {traceDetail.method}
          </span>
          <span className="ss-dbg-tl-detail-url">{traceDetail.url}</span>
          <span className={`ss-dbg-status ${statusClass(traceDetail.statusCode)}`}>
            {traceDetail.statusCode}
          </span>
          <span className="ss-dbg-tl-meta">
            {formatDuration(traceDetail.totalDuration)} &middot; {traceDetail.spanCount} spans
          </span>
        </div>

        {hasLogs ? (
          <SplitPaneWrapper classPrefix="ss-dbg" storageKey="ss-dbg-timeline-split">
            {waterfallContent}
            <RelatedLogs logs={detailLogs} classPrefix="ss-dbg" />
          </SplitPaneWrapper>
        ) : (
          waterfallContent
        )}
      </div>
    )
  }

  // Trace list view
  return (
    <div>
      <div className="ss-dbg-search-bar">
        <input
          type="text"
          className="ss-dbg-search"
          placeholder="Filter traces..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <span className="ss-dbg-summary">{traces.length} traces</span>
      </div>

      {traces.length === 0 ? (
        <div className="ss-dbg-empty">No traces captured. Enable tracing in config.</div>
      ) : (
        <table ref={tableRef} className="ss-dbg-table">
          <colgroup>
            <col style={{ width: '50px' }} />
            <col style={{ width: '70px' }} />
            <col />
            <col style={{ width: '60px' }} />
            <col style={{ width: '80px' }} />
            <col style={{ width: '50px' }} />
            <col style={{ width: '80px' }} />
          </colgroup>
          <thead>
            <tr>
              <th>#</th>
              <th>Method</th>
              <th>URL</th>
              <th>Status</th>
              <th>Duration</th>
              <th>Spans</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            {traces.map((trace) => (
              <tr
                key={trace.id}
                className="ss-dbg-email-row"
                onClick={() => handleSelectTrace(trace.id)}
              >
                <td className="ss-dbg-c-dim" style={{ whiteSpace: 'nowrap' }}>
                  {trace.id}
                </td>
                <td>
                  <span className={`ss-dbg-method ss-dbg-method-${trace.method.toLowerCase()}`}>
                    {trace.method}
                  </span>
                </td>
                <td title={trace.url}>{trace.url}</td>
                <td>
                  <span className={`ss-dbg-status ${statusClass(trace.statusCode)}`}>
                    {trace.statusCode}
                  </span>
                </td>
                <td
                  className={`ss-dbg-duration ${durationSeverity(trace.totalDuration) === 'very-slow' ? 'ss-dbg-very-slow' : durationSeverity(trace.totalDuration) === 'slow' ? 'ss-dbg-slow' : ''}`}
                >
                  {formatDuration(trace.totalDuration)}
                </td>
                <td className="ss-dbg-c-muted" style={{ textAlign: 'center' }}>
                  {trace.spanCount}
                </td>
                <td className="ss-dbg-event-time" title={formatTime(trace.timestamp)}>
                  {timeAgo(trace.timestamp)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}

export default TimelineTab

// src/vue/components/DebugPanel/tabs/TimelineTab.vue
<script setup lang="ts">
/**
 * Request waterfall / timeline tab for the debug panel.
 */
import { ref, computed, watch, nextTick, onBeforeUnmount } from 'vue'
import {
  formatDuration,
  formatTime,
  statusColor,
  timeAgo,
  durationSeverity,
} from '../../../../core/index.js'
import { useApiClient } from '../../../composables/useApiClient.js'
import { useResizableTable } from '../../../composables/useResizableTable.js'
import { TAB_ICONS } from '../../../../core/icons.js'
import { initSplitPane } from '../../../../core/split-pane.js'
import RelatedLogs from '../../shared/RelatedLogs.vue'
import type { TraceRecord, TraceSpan } from '../../../../core/index.js'

const props = defineProps<{
  data: { traces?: TraceRecord[] } | TraceRecord[] | null
  dashboardPath?: string
  baseUrl?: string
  debugEndpoint?: string
  authToken?: string
}>()

const search = ref('')
const selectedTraceId = ref<number | null>(null)
const traceDetail = ref<TraceRecord | null>(null)
const detailLoading = ref(false)
const detailError = ref<string | null>(null)

const getClient = useApiClient(props.baseUrl || '', props.authToken)

const traces = computed<TraceRecord[]>(() => {
  const d = props.data
  if (!d) return []
  const items = Array.isArray(d) ? d : d.traces || []
  if (!search.value.trim()) return items
  const term = search.value.toLowerCase()
  return items.filter(
    (t: TraceRecord) =>
      t.url.toLowerCase().includes(term) ||
      t.method.toLowerCase().includes(term) ||
      String(t.statusCode).includes(term)
  )
})

const CATEGORY_COLORS: Record<string, string> = {
  request: '#1e3a5f',
  middleware: 'rgba(30, 58, 95, 0.7)',
  db: '#6d28d9',
  view: '#0e7490',
  mail: '#059669',
  event: '#b45309',
  custom: '#525252',
}

const CATEGORY_LABELS: Record<string, string> = {
  request: 'Request',
  middleware: 'Middleware',
  db: 'Database',
  view: 'View',
  mail: 'Mail',
  event: 'Event',
  custom: 'Custom',
}

function selectTrace(trace: TraceRecord) {
  if (selectedTraceId.value === trace.id) {
    selectedTraceId.value = null
    traceDetail.value = null
    detailError.value = null
  } else {
    selectedTraceId.value = trace.id
    fetchTraceDetail(trace.id)
  }
}

function goBack() {
  selectedTraceId.value = null
  traceDetail.value = null
  detailError.value = null
}

let fetchAbortController: AbortController | null = null

async function fetchTraceDetail(id: number) {
  // Cancel any in-flight request
  if (fetchAbortController) {
    fetchAbortController.abort()
  }
  fetchAbortController = new AbortController()

  detailLoading.value = true
  detailError.value = null
  traceDetail.value = null

  const endpoint = props.debugEndpoint || '/admin/api/debug'
  try {
    const client = getClient()
    const detail = await client.get<TraceRecord>(`${endpoint}/traces/${id}`)
    traceDetail.value = detail
  } catch (err) {
    if (err instanceof Error && err.name === 'AbortError') return
    detailError.value = err instanceof Error ? err.message : 'Failed to load trace'
  } finally {
    detailLoading.value = false
  }
}

const detailSpans = computed<TraceSpan[]>(() => traceDetail.value?.spans || [])
const detailWarnings = computed<string[]>(() => traceDetail.value?.warnings || [])

function getBarStyle(span: TraceSpan, totalDuration: number): Record<string, string> {
  const total = totalDuration || 1
  const left = total > 0 ? (span.startOffset / total) * 100 : 0
  const width = total > 0 ? Math.max((span.duration / total) * 100, 0.5) : 0.5
  return {
    left: `${left}%`,
    width: `${width}%`,
    background: CATEGORY_COLORS[span.category] || CATEGORY_COLORS.custom,
  }
}

const { tableRef } = useResizableTable(() => traces.value)

const splitContainerRef = ref<HTMLElement | null>(null)
const splitHandleRef = ref<HTMLElement | null>(null)
const splitTopRef = ref<HTMLElement | null>(null)
const splitBottomRef = ref<HTMLElement | null>(null)
let splitCleanup: (() => void) | null = null

const detailLogs = computed(() => {
  if (!traceDetail.value) return []
  return traceDetail.value.logs || []
})

watch([selectedTraceId, traceDetail], async () => {
  splitCleanup?.()
  splitCleanup = null
  if (traceDetail.value && detailLogs.value.length > 0) {
    await nextTick()
    if (
      splitContainerRef.value &&
      splitHandleRef.value &&
      splitTopRef.value &&
      splitBottomRef.value
    ) {
      splitCleanup = initSplitPane({
        container: splitContainerRef.value,
        handle: splitHandleRef.value,
        topPane: splitTopRef.value,
        bottomPane: splitBottomRef.value,
        storageKey: 'ss-dbg-timeline-split',
      })
    }
  }
})

onBeforeUnmount(() => {
  if (fetchAbortController) fetchAbortController.abort()
  splitCleanup?.()
})

function dbgDurationClass(ms: number): string {
  const sev = durationSeverity(ms)
  if (sev === 'very-slow') return 'ss-dbg-very-slow'
  if (sev === 'slow') return 'ss-dbg-slow'
  return ''
}
</script>

<template>
  <div>
    <!-- Trace detail view -->
    <template v-if="selectedTraceId !== null">
      <!-- Loading state -->
      <div v-if="detailLoading" class="ss-dbg-empty">Loading trace detail...</div>

      <!-- Error state -->
      <template v-else-if="detailError">
        <div class="ss-dbg-tl-detail-header">
          <button type="button" class="ss-dbg-btn-clear" @click="goBack">&larr; Back</button>
        </div>
        <div class="ss-dbg-empty">Error: {{ detailError }}</div>
      </template>

      <!-- Detail content -->
      <div v-else-if="traceDetail" class="ss-dbg-tl-detail-wrapper">
        <div class="ss-dbg-tl-detail-header">
          <button type="button" class="ss-dbg-btn-clear" @click="goBack">&larr; Back</button>
          <span :class="`ss-dbg-method ss-dbg-method-${traceDetail.method.toLowerCase()}`">
            {{ traceDetail.method }}
          </span>
          <span class="ss-dbg-tl-detail-url">{{ traceDetail.url }}</span>
          <span
            :class="`ss-dbg-status ss-dbg-status-${Math.floor(traceDetail.statusCode / 100)}xx`"
          >
            {{ traceDetail.statusCode }}
          </span>
          <span class="ss-dbg-tl-meta">
            {{ formatDuration(traceDetail.totalDuration) }} &middot;
            {{ traceDetail.spanCount }} spans
          </span>
        </div>

        <!-- With logs: split pane -->
        <template v-if="detailLogs.length > 0">
          <div ref="splitContainerRef" class="ss-dbg-split-container">
            <div ref="splitTopRef" class="ss-dbg-split-top">
              <div class="ss-dbg-tl-legend">
                <span
                  v-for="(color, cat) in CATEGORY_COLORS"
                  :key="cat"
                  class="ss-dbg-tl-legend-item"
                >
                  <span class="ss-dbg-tl-legend-dot" :style="{ background: color }"></span>
                  {{ CATEGORY_LABELS[cat] || cat }}
                </span>
              </div>

              <div id="ss-dbg-tl-waterfall">
                <div v-if="detailSpans.length === 0" class="ss-dbg-empty">
                  No spans captured for this request
                </div>
                <div v-for="span in detailSpans" :key="span.id" class="ss-dbg-tl-row">
                  <span class="ss-dbg-tl-label" :title="span.label">
                    {{ span.label }}
                  </span>
                  <span class="ss-dbg-tl-track">
                    <span
                      :class="`ss-dbg-tl-bar ss-dbg-tl-bar-${span.category}`"
                      :style="getBarStyle(span, traceDetail.totalDuration)"
                      :title="`${span.label}: ${formatDuration(span.duration)}`"
                    ></span>
                  </span>
                  <span class="ss-dbg-tl-dur">{{ formatDuration(span.duration) }}</span>
                </div>
              </div>

              <div v-if="detailWarnings.length > 0" class="ss-dbg-tl-warnings">
                <div class="ss-dbg-tl-warnings-title">Warnings</div>
                <div v-for="(w, i) in detailWarnings" :key="i" class="ss-dbg-tl-warning">
                  {{ w }}
                </div>
              </div>
            </div>
            <div ref="splitHandleRef" class="ss-dbg-split-handle" />
            <div ref="splitBottomRef" class="ss-dbg-split-bottom">
              <RelatedLogs :logs="detailLogs" />
            </div>
          </div>
        </template>

        <!-- Without logs: original layout -->
        <template v-else>
          <div class="ss-dbg-tl-legend">
            <span v-for="(color, cat) in CATEGORY_COLORS" :key="cat" class="ss-dbg-tl-legend-item">
              <span class="ss-dbg-tl-legend-dot" :style="{ background: color }"></span>
              {{ CATEGORY_LABELS[cat] || cat }}
            </span>
          </div>

          <div id="ss-dbg-tl-waterfall">
            <div v-if="detailSpans.length === 0" class="ss-dbg-empty">
              No spans captured for this request
            </div>
            <div v-for="span in detailSpans" :key="span.id" class="ss-dbg-tl-row">
              <span class="ss-dbg-tl-label" :title="span.label">
                {{ span.label }}
              </span>
              <span class="ss-dbg-tl-track">
                <span
                  :class="`ss-dbg-tl-bar ss-dbg-tl-bar-${span.category}`"
                  :style="getBarStyle(span, traceDetail.totalDuration)"
                  :title="`${span.label}: ${formatDuration(span.duration)}`"
                ></span>
              </span>
              <span class="ss-dbg-tl-dur">{{ formatDuration(span.duration) }}</span>
            </div>
          </div>

          <div v-if="detailWarnings.length > 0" class="ss-dbg-tl-warnings">
            <div class="ss-dbg-tl-warnings-title">Warnings</div>
            <div v-for="(w, i) in detailWarnings" :key="i" class="ss-dbg-tl-warning">
              {{ w }}
            </div>
          </div>
        </template>
      </div>

      <!-- Fallback loading -->
      <div v-else class="ss-dbg-empty">Loading trace detail...</div>
    </template>

    <!-- Trace list view -->
    <template v-else>
      <div class="ss-dbg-search-bar">
        <input v-model="search" class="ss-dbg-search" placeholder="Filter traces..." type="text" />
        <span class="ss-dbg-summary">{{ traces.length }} traces</span>
      </div>

      <div v-if="traces.length === 0" class="ss-dbg-empty">No traces captured</div>

      <table v-else ref="tableRef" class="ss-dbg-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Method</th>
            <th>URL</th>
            <th>Status</th>
            <th>Duration</th>
            <th>Spans</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="t in traces" :key="t.id" class="ss-dbg-email-row" @click="selectTrace(t)">
            <td class="ss-dbg-c-dim" style="white-space: nowrap">{{ t.id }}</td>
            <td>
              <span :class="`ss-dbg-method ss-dbg-method-${t.method.toLowerCase()}`">
                {{ t.method }}
              </span>
            </td>
            <td class="ss-dbg-c-text">
              {{ t.url }}
              <a
                v-if="dashboardPath"
                :href="`${dashboardPath}#requests?id=${t.id}`"
                target="_blank"
                class="ss-dbg-deeplink"
                @click.stop
              >
                <svg
                  :viewBox="TAB_ICONS['open-external'].viewBox"
                  width="12"
                  height="12"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  v-html="TAB_ICONS['open-external'].elements.join('')"
                ></svg>
              </a>
            </td>
            <td>
              <span :class="`ss-dbg-status ss-dbg-status-${Math.floor(t.statusCode / 100)}xx`">
                {{ t.statusCode }}
              </span>
            </td>
            <td :class="['ss-dbg-duration', dbgDurationClass(t.totalDuration)]">
              {{ formatDuration(t.totalDuration) }}
            </td>
            <td class="ss-dbg-c-muted" style="text-align: center">
              {{ t.spanCount }}
            </td>
            <td class="ss-dbg-event-time" :title="formatTime(t.timestamp)">
              {{ timeAgo(t.timestamp) }}
            </td>
          </tr>
        </tbody>
      </table>
    </template>
  </div>
</template>
