// src/react/components/shared/FilterBar.tsx
import React, { useCallback } from 'react'

import { TAB_ICONS } from '../../../core/icons.js'

interface FilterBarProps {
  search: string
  onSearchChange: (value: string) => void
  placeholder?: string
  summary?: React.ReactNode
  children?: React.ReactNode
  className?: string
}

/**
 * Shared search/filter bar used by both Dashboard sections and DebugPanel tabs.
 * Uses the `ss-dbg-` CSS class namespace for consistent styling across both UIs.
 *
 * Layout: [summary] [search input with icon + clear] [extra controls via children]
 */
export function FilterBar({
  search,
  onSearchChange,
  placeholder = 'Search...',
  summary,
  children,
  className = '',
}: FilterBarProps) {
  const handleClear = useCallback(() => {
    onSearchChange('')
  }, [onSearchChange])

  return (
    <div className={`ss-dbg-filter-bar ${className}`}>
      {summary !== null && summary !== undefined && (
        <span className="ss-dbg-summary">{summary}</span>
      )}
      <div className="ss-dbg-search-wrapper">
        <svg
          className="ss-dbg-search-icon"
          width="14"
          height="14"
          viewBox={TAB_ICONS.search.viewBox}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          dangerouslySetInnerHTML={{ __html: TAB_ICONS.search.elements.join('') }}
        />
        <input
          type="text"
          className="ss-dbg-search"
          placeholder={placeholder}
          value={search}
          onChange={(e) => onSearchChange(e.target.value)}
        />
        {search && (
          <button type="button" className="ss-dbg-search-clear" onClick={handleClear}>
            {'\u00D7'}
          </button>
        )}
      </div>
      {children && <div className="ss-dbg-filter-controls">{children}</div>}
    </div>
  )
}

// src/vue/components/Dashboard/shared/FilterBar.vue
<script setup lang="ts">
/**
 * Search/filter bar for dashboard sections.
 */
import { TAB_ICONS } from '../../../../core/icons.js'

const props = defineProps<{
  modelValue: string
  placeholder?: string
  summary?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
  clear: []
}>()

function onInput(event: Event) {
  emit('update:modelValue', (event.target as HTMLInputElement).value)
}

function handleClear() {
  emit('update:modelValue', '')
  emit('clear')
}
</script>

<template>
  <div class="ss-dash-filter-bar">
    <span v-if="summary" class="ss-dash-summary">{{ summary }}</span>
    <div class="ss-dash-search-wrapper">
      <svg
        class="ss-dash-search-icon"
        :viewBox="TAB_ICONS.search.viewBox"
        width="14"
        height="14"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        v-html="TAB_ICONS.search.elements.join('')"
      ></svg>
      <input
        class="ss-dash-search"
        type="text"
        :value="modelValue"
        :placeholder="placeholder || 'Search...'"
        @input="onInput"
      />
      <button v-if="modelValue" type="button" class="ss-dash-search-clear" @click="handleClear">
        &times;
      </button>
    </div>
    <div v-if="$slots.default" class="ss-dash-filter-controls">
      <slot />
    </div>
  </div>
</template>
